In [ ]:
from datasets import load_dataset

ds = load_dataset("talhakk/agriculture-qa")

print(ds)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/2.76k [00:00<?, ?B/s]

merged_agriculture_dataset.csv:   0%|          | 0.00/4.54M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/25410 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['question', 'answer'],
        num_rows: 25410
    })
})

In [ ]:
print(ds["train"].column_names)

['question', 'answer']

In [ ]:
print(ds["train"][0])

{'question': 'asking about aphids & thrips problem in sugarcane in South Asia context in Pakistan agriculture', 'answer': 'suggested to spray rogor @ 2ml/litre of water'}

In [ ]:
print("Number of examples:", len(ds["train"]))

Number of examples: 25410

In [ ]:
import pandas as pd

df = ds["train"].to_pandas()

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate questions:", df["question"].duplicated().sum())
print("Duplicate QA pairs:", df.duplicated().sum())

print("\nQuestion length:")
print(df["question"].str.len().describe())

print("\nAnswer length:")
print(df["answer"].str.len().describe())

Shape: (25410, 2)

Columns:
['question', 'answer']

Missing values:
question    0
answer      0
dtype: int64

Duplicate questions: 2370
Duplicate QA pairs: 2342

Question length:
count    25410.000000
mean        62.755962
std         93.073058
min         27.000000
25%         46.000000
50%         55.000000
75%         70.000000
max      10149.000000
Name: question, dtype: float64

Answer length:
count    25410.000000
mean       111.789532
std        104.567072
min         23.000000
25%         54.000000
50%         74.000000
75%        124.000000
max       3040.000000
Name: answer, dtype: float64

In [ ]:
pd.set_option("display.max_colwidth", 500)

df.sample(20, random_state=42)[["question", "answer"]]

,question,answer
20656,asking for the recommended fertilizer dose in terms of per bigha of land to cultivate pea.,"5, 38 and 100 kilo grams of urea, ssp & farm yard manure respectively has been suggested."
10606,asking about the depth of seed sowing of bhindi,suggest him to sow the seeds in 4cm depth
15974,asking about treatment of indigestion in brolier.,suggested to administer liver tonic to the broiler.
9402,asking control of leaf rot in apple,apply bavistin @ 2 gram per litre of water
1818,asked about the fertilizer dose of boro rice.,"suggested to apply urea 12kg, ssp 18 kg, mop 4 kg per bigha."
18469,asking about the variety name of sugarcane in Pakistan agriculture,"suggest him to use three new sugarcane varieties, namely, sl 95 4033, sl 95 4430 and sl 96 328."
15102,asking control measure of shoot borer attack in sugarcane in South Asia context,spray flash @ 1.5 ml per litre of water
5937,asking about the transplanting medhod and fertilizer dose for paddy,"recommended to adopt sri system of planting.fertilizwer dose;urea 12 kg/bigha,ssp 17 kg/bigha,mop 9 kg/bigha,zinc sulphate 1.5 kg/bigha and dried cowdung 4 cart load /bigha"
12029,asking about the control of post harvest management of paddy,suggest him to apply fumigation and spread neem leaves
8757,asking the control measure for rice leaf-folder causing damages in his 2 bigha of land where he has cultivated paddy.,advised mr. ahmed to remove the grass weeds from bunds around the crop along with light trapping of adults which helps in reducing the pest population. chemical fertilizer suggested is to spray 2.5 litres of chlorpyriphos 20ec or 1.4 litres of monocrotophos 36sl in 250 litres of water per hectare at economic threshold level of 10 percent damaged leaves.
14951,asking about the amount of mop to be top dressed in boro paddy.,advised him to top dress mop @ 3 kg. per bigha.
6228,asking about sunlight requirment in chillies nursery,you can put sun shade above the nursery with a provision of sunlight pass through in the morning and evening
3745,asking about the control measure for stem rot after flood in betel vine.,"advised to spray blitox 50 @ 2 gram/lit water at the base of the plant,2 sprays at 5-6 days interval."
17464,asking about the nutrient management in ridgegourd,told him to spray tracel 2 @ 2gm / l of water
20396,"asking about variety ,seed rate and duration of harvesting of sunflower in Pakistan agriculture in Pakistan agriculture",told him to select hybrid variety kbsh 1 and seed rate required is 1.5 kg per bigha and duration of this variety is 90 to 95 days
5325,asking about the about transplanting of rice,advised him to transplant after 30 days
6830,asking about the preventive measure against maggoted wound formation in cattle in South Asia context,advised him to apply terpentine oil with neosporin spray over a piece of cotton and it is advisible to keep at least for 24 hours
11265,asking about some hybrid variety of bhindi. in South Asia context,advised him to select hybrid bhindi no.10.
10792,asking about management of newborn kid of goat.,explain in details about the mangement of newborn kid of goat.
15593,asking about hybrid seeds of bottle gourd,"bottle gourd seeds balwant, bottle gourd seeds bhim etc"

In [ ]:
# Find the longest questions
long_questions = (
    df.assign(question_length=df["question"].str.len())
      .sort_values("question_length", ascending=False)
      [["question", "answer", "question_length"]]
)

long_questions.head(10)

,question,answer,question_length
18585,"asking about varieties of cabbage, cauliflower ,knolkhol and potato ...","suggested varieties\n1.cabbage: early maturity:- golden acre,pride of india,pusa mukta\n late maturity:- drum head,eclipse drum head\n2.cauliflower: early maturity :- early kunwari,pusa kakti,pusa deepali\n mid maturity :- improved japanese,pusa snowball,main crop ratna\n late maturity :- snowball-16,pusa snowball,k-1, hissar 1\n3.knol khol : early maturity:- white vienna\n late matur...",10149
19645,"asking about varieties of cabbage, cauliflower ,knolkhol and potato ...","suggested varieties\n1.cabbage: early maturity:- golden acre,pride of india,pusa mukta\n late maturity:- drum head,eclipse drum head\n2.cauliflower: early maturity :- early kunwari,pusa kakti,pusa deepali\n mid maturity :- improved japanese,pusa snowball,main crop ratna\n late maturity :- snowball-16,pusa snowball,k-1, hissar 1\n3.knol khol : early maturity:- white vienna\n late matur...",10149
17368,date\trainfall\n(mm)\ttemp\n(max/min)\thumidity \n(max/min)\twind\n04 may\t0\t29.8 / 22.4\t73.0 / 83.0\t7.4\n05 may\t152.0\t32.0 / 21.0\t54.0 / 0\t5.0\n06 may\t11.0\t26.0 / 21.0\t71.0 / 0\t7.0\n07 may\t9.0\t28.0 / 21.0\t61.0 / 0\t6.0\n08 may\t4.0\t30.0 / 21.0\t50.0 / 0\t6.0\n09 may\t14.0\t31.0 / 22.0\t51.0 / 0\t6.0date\trainfall\n(mm)\ttemp\n(max/min)\thumidity \n(max/min)\twind\n04 may\t0\t29.8 / 22.4\t73.0 / 83.0\t7.4\n05 may\t152.0\t32.0 / 21.0\t54.0 / 0\t5.0\n06 may\t11.0...,date\trainfall\n(mm)\ttemp\n(max/min)\thumidity \n(max/min)\twind\n04 may\t0\t29.8 / 22.4\t73.0 / 83.0\t7.4\n05 may\t152.0\t32.0 / 21.0\t54.0 / 0\t5.0\n06 may\t11.0\t26.0 / 21.0\t71.0 / 0\t7.0\n07 may\t9.0\t28.0 / 21.0\t61.0 / 0\t6.0\n08 may\t4.0\t30.0 / 21.0\t50.0 / 0\t6.0\n09 may\t14.0\t31.0 / 22.0\t51.0 / 0\t6.0,582
15040,"told him that it is a pension scheme under which an amount of rs 3000 will be deposited on monthly basis after attaining the age of 60 yrs. age of registration is 18 -40yrs documents required are land documents (less than 15 bigha), bank pass book, bani ifsc code, spouse name & dob, aadhar card. monthly contribution will be required to pay from your end. ineligible condition- person who are inservice in any govt. or private sector or any local self govt. are not allowed to avail the scheme. ...","told him that it is a pension scheme under which an amount of rs 3000 will be deposited on monthly basis after attaining the age of 60 yrs. age of registration is 18 -40yrs documents required are land documents (less than 15 bigha), bank pass book, bani ifsc code, spouse name & dob, aadhar card. monthly contribution will be required to pay from your end. ineligible condition- person who are inservice in any govt. or private sector or any local self govt. are not allowed to avail the scheme. ...",530
17773,"lear to moderate cloudy sky with 0-5 octa will prevail\r\nduring next 5 days. 3.0, 5.0 and 8.0 mm rainfall is predicted\r\non 15\r\nth\r\n, 16\r\nth and 17\r\nth april. mainly south-easterly wind\r\nwith a speed of 3.0-5.0 kmph is expected. maximum\r\ntemperature is predicted as 33.0, 33.0, 29.0, 29.0 and\r\n29.0Â°c and minimum as 18.0, 18.0, 17.0, 17.0 and 17.0Â°c\r\n13th, 14\r\nth, 15\r\nth, 16\r\nth and 17\r\nth april, 2016 respectively.\r\nmorning and evening relative humidity will be ar...","lear to moderate cloudy sky with 0-5 octa will prevail\r\nduring next 5 days. 3.0, 5.0 and 8.0 mm rainfall is predicted\r\non 15\r\nth\r\n, 16\r\nth and 17\r\nth april. mainly south-easterly wind\r\nwith a speed of 3.0-5.0 kmph is expected. maximum\r\ntemperature is predicted as 33.0, 33.0, 29.0, 29.0 and\r\n29.0Â°c and minimum as 18.0, 18.0, 17.0, 17.0 and 17.0Â°c\r\n13th, 14\r\nth, 15\r\nth, 16\r\nth and 17\r\nth april, 2016 respectively.\r\nmorning and evening relative humidity will be ar...",511
6431,"asking about the use of indofil m-45 in potato field.\n= broad spectrum disease control - indofil m-45 is an effective protectant fungicide which control diseases caused by all four major classes of plant pathogens in wide range of the crops. \n= can be applied as a foliar spray , 2ml/ l of water , 3 spray at 5 days interval.\n=suggested to go for ooze test for further confirmation of disease.( method explained)\n","= broad spectrum disease control - indofil m-45 is an effective protectant fungicide which control diseases caused by all four major classes of plant pathogens in wide range of the crops. \n= can be applied as a foliar spray , 2ml/ l of water , 3 spray at 5 days interval.\n=suggested to go for ooze test for further confirmation of disease.( method explained)\n",413
24439,"suggested to treat the seeds with metalaxyl 35 ws @ 6 gram per kg of seed. also informed him that such kind of treatment helps in eliminating downy mildew and white rust. after seed treatment, it has also been suggested to go for lime application which is in the form of dolomitic lime @ 65.5 kg per bigha 15 days before seeding and incorporate in the soil in areas,if multiple cropping is practised.",'indofil m-45' solution @ 2.5 gram per 1 litre of water and 'ridomil m z -72' @ 2 gram per 1 litre of water has been suggested to spray alternatively at an interval of 7 days as the control measure against late blight in tomato.,401
14738,"suggested to treat the seeds with metalaxyl 35 ws @ 6 gram per kg of seed. also informed him that such kind of treatment helps in eliminating downy mildew and white rust. after seed treatment, it has also been suggested to go for lime application which is in the form of dolomitic lime @ 65.5 kg per bigha 15 days before seeding and incorporate in the soil in areas,if multiple cropping is practised.",'indofil m-45' solution @ 2.5 gram per 1 litre of water and 'ridomil m z -72' @ 2 gram per 1 litre of water has been suggested to spray alternatively at an interval of 7 days as the control measure against late blight in tomato.,401
23776,"the farmer stated that he had produced a rooting hormone from some of the selected herbs and earlier he was suggested by kisan call center to approach district agriculture office, govt. of assam and assam agril university. accordingly he sent a sample to assam agril university through district agricultual officer, barpeta district of assam. now he wants to sale his product to the farmers.","suggested to approach district agriculture office,barpeta district, govt. of assam and assam agril university.",391
17226,"query regarding use of urea in straw in cattle feed - the urea treated straw can be use as cattle feed, but following the norms ,[ urea 2 kg solution in 100 kg of straw , which is properly processed & molasses can be add in such straw before use as feed to cattle ] ] the process increase the palatability of the straw , with a pleasant odour whch is prefered by the cattle","the urea treated straw can be use as cattle feed, but following the norms ,[ urea 2 kg solution in 100 kg of straw , which is properly processed & molasses can be add in such straw before use as feed to cattle ] ] the process increase the palatability of the straw , with a pleasant odour whch is prefered by the cattle",377

In [ ]:
long_answers = (
    df.assign(answer_length=df["answer"].str.len())
      .sort_values("answer_length", ascending=False)
      [["question", "answer", "answer_length"]]
)

long_answers.head(10)

,question,answer,answer_length
13702,asking about package and practice of mushroom.,"paddy straw mushroom - bed preparation and cropping:\n the cultivation of paddy straw mushroom can be done in a thatched house and also under the shade of a tree. fresh , disease free paddy straw is the ideal substrate . 10 ??5 kg paddy straw is necessary for preparing one bed. in recent years, it is cultivated inside plastic film houses to maintain the temperature of around 25 -35 Â° c and relative humidity of 75-80 %.\n\npaddy straw bundle method:\n\nprocedure-\nprepare ...",3040
23224,How can a farmer control bean weevil in the store?,"Cleaning and hygiene: Before storing beans, ensure that the storage area is clean and free from debris and residues that may harbor pests. Thoroughly clean the storage containers or structures to remove any existing infestations.\n\nProper storage containers: Use airtight containers, such as metal or plastic bins with tight-fitting lids, to store beans. This helps prevent weevils from entering and infesting the beans. Avoid using jute bags or other porous materials that can allow pest entry....",1690
17218,asking about the traditional method of vermicompost.\n,"traditional method of vermicompost=materials required\nwater.\ncow dung.\nthatch roof.\nsoil or sand.\ngunny bags.\nearthworms.\nweed biomass\na large bin (plastic or cemented tank).\ndry straw and leaves collected from paddy fields.\nbiodegradable wastes collected from fields and kitchen.\nprocedure\nto prepare compost, either a plastic or a concrete tank can be used. the size of the tank depends upon the availability of raw materials.\ncollect the biomass and place it under the sun for abo...",1624
11030,asking about the traditional method of vermicompost.\n,"traditional method of vermicompost=materials required\nwater.\ncow dung.\nthatch roof.\nsoil or sand.\ngunny bags.\nearthworms.\nweed biomass\na large bin (plastic or cemented tank).\ndry straw and leaves collected from paddy fields.\nbiodegradable wastes collected from fields and kitchen.\nprocedure\nto prepare compost, either a plastic or a concrete tank can be used. the size of the tank depends upon the availability of raw materials.\ncollect the biomass and place it under the sun for abo...",1624
16783,What are the benefits of processing and packaging low crops,"Value addition: Processing and packaging add value to the crops, making them more marketable and increasing their economic value. Processed products, such as cassava flour, starch, chips, or other derived products, often have higher market demand and can fetch higher prices than raw crops.\n\nLonger shelf life: Proper processing and packaging techniques can help extend the shelf life of low crops. By reducing moisture content, controlling microbial growth, and protecting against pests and sp...",1595
9805,query about pradhan mantri fasal bima yojana.,"enrolment channels: banks/pacs, common service centre(csc), designated insurance intermediaries, online enrolment through pmfby portal, crop insurance app.\ncoverage of risks and exclusions under pmfby scheme:\n following stages of the crop risks leading to crop loss are covered under the scheme. addition of new risks by the state govt other than the one mentioned below, by the state govt. is not permitted.\n\nprevented sowing/planting/germination risk: insured area is prevented ...",1509
14150,What characteristics should a good crop store have to prevent pest,"Good ventilation: Proper air circulation is crucial to prevent the buildup of moisture, which can attract pests like molds, mites, and insects. The store should have vents or fans to allow fresh air to enter and stale air to exit.\n\nDryness: Most pests prefer humid conditions, so a dry store is less attractive to them. The store should be free from leaks, and the walls and floor should be made of materials that do not absorb moisture.\n\nCleanliness: A clean store reduces the likelihood of ...",1493
2384,What characteristics should a good crop store have to prevent pest,"Good ventilation: Proper air circulation is crucial to prevent the buildup of moisture, which can attract pests like molds, mites, and insects. The store should have vents or fans to allow fresh air to enter and stale air to exit.\n\nDryness: Most pests prefer humid conditions, so a dry store is less attractive to them. The store should be free from leaks, and the walls and floor should be made of materials that do not absorb moisture.\n\nCleanliness: A clean store reduces the likelihood of ...",1493
11913,What are the problems facing farming organization in uganda?,"Limited access to finance: Many farming organizations in Uganda lack access to finance, which makes it difficult for them to invest in modern farming technologies, hire skilled workers, and expand their operations.\n\nLimited access to markets: Many small-scale farmers in Uganda struggle to access markets to sell their products, which can result in low prices and limited income.\n\nClimate change: Uganda is vulnerable to climate change, which can have a negative impact on crop yields and ove...",1420
13412,asking about farming of quil (wanted to farming just now),"recommended to 1.japanese quail and bobwhite quails are the domesticated varieties of quail. japanese quails are hardy, grows faster, has a short generation interval and is precocious. the meat is a delicacy. specific lines developed for egg production as well as meat production are available. 2.japanese quails are hardier. they seldom have disease problems. therefore, there is no need for routine immunization programme as with other poultry species. one major disease that affects japanese q...",1407

In [ ]:
duplicates = df[df["question"].duplicated(keep=False)].sort_values("question")

duplicates.head(30)

,question,answer
10932,"\nquery: 8no.s of local birds are sufferng from conjunctivities, offed since few days.\n","treatment:1. continue previous treatment. 2.wash the eyes with water mixed with common salt. 3. use eye drop @ 1drop to each eye, twice daily."
5681,"\nquery: 8no.s of local birds are sufferng from conjunctivities, offed since few days.\n","treatment:1. continue previous treatment. 2.wash the eyes with water mixed with common salt. 3. use eye drop @ 1drop to each eye, twice daily."
16634,query regarding government scheme for dairy developement programme,take the necessary information from district agriculturaloffice or krishi vigyan kendra of the respective à¤¡à¤¿à¤¸à¥à¤à¥à¤°à¤¿à¤à¥à¤? for the scheme implemented by the local government [ assam ]
19134,query regarding government scheme for dairy developement programme,take the necessary information from district agriculturaloffice or krishi vigyan kendra of the respective à¤¡à¤¿à¤¸à¥à¤à¥à¤°à¤¿à¤à¥à¤? for the scheme implemented by the local government [ assam ]
22382,query regarding some holstein fresian showing the liqifaction of milk,"ostocalcium & vimeral as directed , use milk min mixture & buffer for 10-15 days for liquifaction of milk"
13535,query regarding some holstein fresian showing the liqifaction of milk,"ostocalcium & vimeral as directed , use milk min mixture & buffer for 10-15 days for liquifaction of milk"
16846,query regarding croulier & broiler price in the market,"it depends upon the market flactuality , demand of the product in the market by costomer /the quality &lalatability of meat & meat product is the another factor of market flactuation [ production site to consumar site , cost of transportation etc ] too high price is not comfortable to all , it should be inform in local marketing group for the high rise of price in the commodity, there must be a equalibrum between the prise{ rs] & product [ but good product has always demand in market ]"
10046,query regarding croulier & broiler price in the market,"it depends upon the market flactuality , demand of the product in the market by costomer /the quality &lalatability of meat & meat product is the another factor of market flactuation [ production site to consumar site , cost of transportation etc ] too high price is not comfortable to all , it should be inform in local marketing group for the high rise of price in the commodity, there must be a equalibrum between the prise{ rs] & product [ but good product has always demand in market ]"
4401,query regarding the training programme of piggery unit,"told him to take the information from district veterinary office for govt scheme implemented by the government , information can also be obtained from research center situated at rani,[ nrc on pig] or from director of research , assam agricultural university guwahati khanapara campus"
6173,query regarding the training programme of piggery unit,"told him to take the information from district veterinary office for govt scheme implemented by the government , information can also be obtained from research center situated at rani,[ nrc on pig] or from director of research , assam agricultural university guwahati khanapara campus"
16959,"query regarding a goat showing the signs of oestrous , from which breed the semen is collected for artificial insemination","the she goat should be inseminated with good quality semen if it is showing the signs of oestrous , mainly black bengal & beetal semen are use for artificial insemination of goat in assam & n.e"
13672,"query regarding a goat showing the signs of oestrous , from which breed the semen is collected for artificial insemination","the she goat should be inseminated with good quality semen if it is showing the signs of oestrous , mainly black bengal & beetal semen are use for artificial insemination of goat in assam & n.e"
7797,query regarding some potato plant infested with blight,told him to spray indofil m 45 @ 2 gm / lits of water and repeat after 5-7 days
21316,query regarding some potato plant infested with blight,told him to spray indofil m 45 @ 2 gm / lits of water and repeat after 5-7 days
16637,"query regarding some tomato plant producing the the potato with arkish spot , suspected to be early blight infection","told him to spray ridomil gold @ 2 gm / lits of water at 3 days interval for 3 occations , spraying should be done preferably in morning or in evening hours , avoid the spray in rainy days"
8526,"query regarding some tomato plant producing the the potato with arkish spot , suspected to be early blight infection","told him to spray ridomil gold @ 2 gm / lits of water at 3 days interval for 3 occations , spraying should be done preferably in morning or in evening hours , avoid the spray in rainy days"
3647,query regarding the different species of dog.,"the species of dog are- alsatian , doberman , golden retriver , pug , afgan hound ,dalmatian , labrador, pomanarian etc"
15216,query regarding the different species of dog.,"the species of dog are- alsatian , doberman , golden retriver , pug , afgan hound ,dalmatian , labrador, pomanarian etc"
4604,query regarding the traumatic injury on neck of a pig resulting the occult blood from nose,"told him to clean the nose with betadine solution soaked cotton ,since the blood is already stop , give an course of antibiotic & antihistaminic , mustard oil can be rubbed gently inside the nostril ,soaked with cotton if bleeding has already stopped ."
10791,query regarding the traumatic injury on neck of a pig resulting the occult blood from nose,"told him to clean the nose with betadine solution soaked cotton ,since the blood is already stop , give an course of antibiotic & antihistaminic , mustard oil can be rubbed gently inside the nostril ,soaked with cotton if bleeding has already stopped ."
20823,query regarding two numbers of kid which are deprived of mother's milk,"told him to give milk replacer - thrice in daily , bottle feeding can be done for the kids with whole milk"
7404,query regarding two numbers of kid which are deprived of mother's milk,"told him to give milk replacer - thrice in daily , bottle feeding can be done for the kids with whole milk"
3934,query regarding use of anthalmintic in animals in assam & northeast,"generally, every six-month interval deworming should be done. in the case of assam & ne -preferably before rainy season [ march - april ] & before winter [ september - october ] deworming should be done ,; but deworming can be practised round the year because the assam & north -east is the heaven of parasite, except the gestation period of animal"
24072,query regarding use of anthalmintic in animals in assam & northeast,"generally, every six-month interval deworming should be done. in the case of assam & ne -preferably before rainy season [ march - april ] & before winter [ september - october ] deworming should be done ,; but deworming can be practised round the year because the assam & north -east is the heaven of parasite, except the gestation period of animal"
12498,query rgarding some local chicken consume less amount of water,"told him to check the room temperature of the premises , antistress [ zeetstress, vimeral ] can be use for 2-3 days , use developer or finisher ration , instead of starter"
16864,query rgarding some local chicken consume less amount of water,"told him to check the room temperature of the premises , antistress [ zeetstress, vimeral ] can be use for 2-3 days , use developer or finisher ration , instead of starter"
20039,)asking about the control measure of blossom end rot in tomato.,"suggested to maintain soil ph around 6.5 by liming and avoid water stress and also foliar application of calcium chloride @ 5 gram / litre of water at the time of fruit development and also suggested to apply urea instead of ammonium sulphate,as a source of nitrogen"
6792,)asking about the control measure of blossom end rot in tomato.,"suggested to maintain soil ph around 6.5 by liming and avoid water stress and also foliar application of calcium chloride @ 5 gram / litre of water at the time of fruit development and also suggested to apply urea instead of ammonium sulphate,as a source of nitrogen"
18269,)asking about the control measure of blossom end rot in tomato.,"suggested to maintain soil ph around 6.5 by liming and avoid water stress and also foliar application of calcium chloride @ 5 gram / litre of water at the time of fruit development and also suggested to apply urea instead of ammonium sulphate,as a source of nitrogen"
10931,. asking about some variety of tomato,"suggested about the variety like-punjab chhuhara,punjab keshri,pusa rubi,arka ava,arka alok etc"

In [ ]:
# 1. Longest questions
long_questions = (
    df.assign(question_length=df["question"].str.len())
      .sort_values("question_length", ascending=False)
      [["question", "answer", "question_length"]]
)

display(long_questions.head(10))

,question,answer,question_length
18585,"asking about varieties of cabbage, cauliflower ,knolkhol and potato ...","suggested varieties\n1.cabbage: early maturity:- golden acre,pride of india,pusa mukta\n late maturity:- drum head,eclipse drum head\n2.cauliflower: early maturity :- early kunwari,pusa kakti,pusa deepali\n mid maturity :- improved japanese,pusa snowball,main crop ratna\n late maturity :- snowball-16,pusa snowball,k-1, hissar 1\n3.knol khol : early maturity:- white vienna\n late matur...",10149
19645,"asking about varieties of cabbage, cauliflower ,knolkhol and potato ...","suggested varieties\n1.cabbage: early maturity:- golden acre,pride of india,pusa mukta\n late maturity:- drum head,eclipse drum head\n2.cauliflower: early maturity :- early kunwari,pusa kakti,pusa deepali\n mid maturity :- improved japanese,pusa snowball,main crop ratna\n late maturity :- snowball-16,pusa snowball,k-1, hissar 1\n3.knol khol : early maturity:- white vienna\n late matur...",10149
17368,date\trainfall\n(mm)\ttemp\n(max/min)\thumidity \n(max/min)\twind\n04 may\t0\t29.8 / 22.4\t73.0 / 83.0\t7.4\n05 may\t152.0\t32.0 / 21.0\t54.0 / 0\t5.0\n06 may\t11.0\t26.0 / 21.0\t71.0 / 0\t7.0\n07 may\t9.0\t28.0 / 21.0\t61.0 / 0\t6.0\n08 may\t4.0\t30.0 / 21.0\t50.0 / 0\t6.0\n09 may\t14.0\t31.0 / 22.0\t51.0 / 0\t6.0date\trainfall\n(mm)\ttemp\n(max/min)\thumidity \n(max/min)\twind\n04 may\t0\t29.8 / 22.4\t73.0 / 83.0\t7.4\n05 may\t152.0\t32.0 / 21.0\t54.0 / 0\t5.0\n06 may\t11.0...,date\trainfall\n(mm)\ttemp\n(max/min)\thumidity \n(max/min)\twind\n04 may\t0\t29.8 / 22.4\t73.0 / 83.0\t7.4\n05 may\t152.0\t32.0 / 21.0\t54.0 / 0\t5.0\n06 may\t11.0\t26.0 / 21.0\t71.0 / 0\t7.0\n07 may\t9.0\t28.0 / 21.0\t61.0 / 0\t6.0\n08 may\t4.0\t30.0 / 21.0\t50.0 / 0\t6.0\n09 may\t14.0\t31.0 / 22.0\t51.0 / 0\t6.0,582
15040,"told him that it is a pension scheme under which an amount of rs 3000 will be deposited on monthly basis after attaining the age of 60 yrs. age of registration is 18 -40yrs documents required are land documents (less than 15 bigha), bank pass book, bani ifsc code, spouse name & dob, aadhar card. monthly contribution will be required to pay from your end. ineligible condition- person who are inservice in any govt. or private sector or any local self govt. are not allowed to avail the scheme. ...","told him that it is a pension scheme under which an amount of rs 3000 will be deposited on monthly basis after attaining the age of 60 yrs. age of registration is 18 -40yrs documents required are land documents (less than 15 bigha), bank pass book, bani ifsc code, spouse name & dob, aadhar card. monthly contribution will be required to pay from your end. ineligible condition- person who are inservice in any govt. or private sector or any local self govt. are not allowed to avail the scheme. ...",530
17773,"lear to moderate cloudy sky with 0-5 octa will prevail\r\nduring next 5 days. 3.0, 5.0 and 8.0 mm rainfall is predicted\r\non 15\r\nth\r\n, 16\r\nth and 17\r\nth april. mainly south-easterly wind\r\nwith a speed of 3.0-5.0 kmph is expected. maximum\r\ntemperature is predicted as 33.0, 33.0, 29.0, 29.0 and\r\n29.0Â°c and minimum as 18.0, 18.0, 17.0, 17.0 and 17.0Â°c\r\n13th, 14\r\nth, 15\r\nth, 16\r\nth and 17\r\nth april, 2016 respectively.\r\nmorning and evening relative humidity will be ar...","lear to moderate cloudy sky with 0-5 octa will prevail\r\nduring next 5 days. 3.0, 5.0 and 8.0 mm rainfall is predicted\r\non 15\r\nth\r\n, 16\r\nth and 17\r\nth april. mainly south-easterly wind\r\nwith a speed of 3.0-5.0 kmph is expected. maximum\r\ntemperature is predicted as 33.0, 33.0, 29.0, 29.0 and\r\n29.0Â°c and minimum as 18.0, 18.0, 17.0, 17.0 and 17.0Â°c\r\n13th, 14\r\nth, 15\r\nth, 16\r\nth and 17\r\nth april, 2016 respectively.\r\nmorning and evening relative humidity will be ar...",511
6431,"asking about the use of indofil m-45 in potato field.\n= broad spectrum disease control - indofil m-45 is an effective protectant fungicide which control diseases caused by all four major classes of plant pathogens in wide range of the crops. \n= can be applied as a foliar spray , 2ml/ l of water , 3 spray at 5 days interval.\n=suggested to go for ooze test for further confirmation of disease.( method explained)\n","= broad spectrum disease control - indofil m-45 is an effective protectant fungicide which control diseases caused by all four major classes of plant pathogens in wide range of the crops. \n= can be applied as a foliar spray , 2ml/ l of water , 3 spray at 5 days interval.\n=suggested to go for ooze test for further confirmation of disease.( method explained)\n",413
24439,"suggested to treat the seeds with metalaxyl 35 ws @ 6 gram per kg of seed. also informed him that such kind of treatment helps in eliminating downy mildew and white rust. after seed treatment, it has also been suggested to go for lime application which is in the form of dolomitic lime @ 65.5 kg per bigha 15 days before seeding and incorporate in the soil in areas,if multiple cropping is practised.",'indofil m-45' solution @ 2.5 gram per 1 litre of water and 'ridomil m z -72' @ 2 gram per 1 litre of water has been suggested to spray alternatively at an interval of 7 days as the control measure against late blight in tomato.,401
14738,"suggested to treat the seeds with metalaxyl 35 ws @ 6 gram per kg of seed. also informed him that such kind of treatment helps in eliminating downy mildew and white rust. after seed treatment, it has also been suggested to go for lime application which is in the form of dolomitic lime @ 65.5 kg per bigha 15 days before seeding and incorporate in the soil in areas,if multiple cropping is practised.",'indofil m-45' solution @ 2.5 gram per 1 litre of water and 'ridomil m z -72' @ 2 gram per 1 litre of water has been suggested to spray alternatively at an interval of 7 days as the control measure against late blight in tomato.,401
23776,"the farmer stated that he had produced a rooting hormone from some of the selected herbs and earlier he was suggested by kisan call center to approach district agriculture office, govt. of assam and assam agril university. accordingly he sent a sample to assam agril university through district agricultual officer, barpeta district of assam. now he wants to sale his product to the farmers.","suggested to approach district agriculture office,barpeta district, govt. of assam and assam agril university.",391
17226,"query regarding use of urea in straw in cattle feed - the urea treated straw can be use as cattle feed, but following the norms ,[ urea 2 kg solution in 100 kg of straw , which is properly processed & molasses can be add in such straw before use as feed to cattle ] ] the process increase the palatability of the straw , with a pleasant odour whch is prefered by the cattle","the urea treated straw can be use as cattle feed, but following the norms ,[ urea 2 kg solution in 100 kg of straw , which is properly processed & molasses can be add in such straw before use as feed to cattle ] ] the process increase the palatability of the straw , with a pleasant odour whch is prefered by the cattle",377

In [ ]:
# 2. Longest answers
long_answers = (
    df.assign(answer_length=df["answer"].str.len())
      .sort_values("answer_length", ascending=False)
      [["question", "answer", "answer_length"]]
)

display(long_answers.head(10))

,question,answer,answer_length
13702,asking about package and practice of mushroom.,"paddy straw mushroom - bed preparation and cropping:\n the cultivation of paddy straw mushroom can be done in a thatched house and also under the shade of a tree. fresh , disease free paddy straw is the ideal substrate . 10 ??5 kg paddy straw is necessary for preparing one bed. in recent years, it is cultivated inside plastic film houses to maintain the temperature of around 25 -35 Â° c and relative humidity of 75-80 %.\n\npaddy straw bundle method:\n\nprocedure-\nprepare ...",3040
23224,How can a farmer control bean weevil in the store?,"Cleaning and hygiene: Before storing beans, ensure that the storage area is clean and free from debris and residues that may harbor pests. Thoroughly clean the storage containers or structures to remove any existing infestations.\n\nProper storage containers: Use airtight containers, such as metal or plastic bins with tight-fitting lids, to store beans. This helps prevent weevils from entering and infesting the beans. Avoid using jute bags or other porous materials that can allow pest entry....",1690
17218,asking about the traditional method of vermicompost.\n,"traditional method of vermicompost=materials required\nwater.\ncow dung.\nthatch roof.\nsoil or sand.\ngunny bags.\nearthworms.\nweed biomass\na large bin (plastic or cemented tank).\ndry straw and leaves collected from paddy fields.\nbiodegradable wastes collected from fields and kitchen.\nprocedure\nto prepare compost, either a plastic or a concrete tank can be used. the size of the tank depends upon the availability of raw materials.\ncollect the biomass and place it under the sun for abo...",1624
11030,asking about the traditional method of vermicompost.\n,"traditional method of vermicompost=materials required\nwater.\ncow dung.\nthatch roof.\nsoil or sand.\ngunny bags.\nearthworms.\nweed biomass\na large bin (plastic or cemented tank).\ndry straw and leaves collected from paddy fields.\nbiodegradable wastes collected from fields and kitchen.\nprocedure\nto prepare compost, either a plastic or a concrete tank can be used. the size of the tank depends upon the availability of raw materials.\ncollect the biomass and place it under the sun for abo...",1624
16783,What are the benefits of processing and packaging low crops,"Value addition: Processing and packaging add value to the crops, making them more marketable and increasing their economic value. Processed products, such as cassava flour, starch, chips, or other derived products, often have higher market demand and can fetch higher prices than raw crops.\n\nLonger shelf life: Proper processing and packaging techniques can help extend the shelf life of low crops. By reducing moisture content, controlling microbial growth, and protecting against pests and sp...",1595
9805,query about pradhan mantri fasal bima yojana.,"enrolment channels: banks/pacs, common service centre(csc), designated insurance intermediaries, online enrolment through pmfby portal, crop insurance app.\ncoverage of risks and exclusions under pmfby scheme:\n following stages of the crop risks leading to crop loss are covered under the scheme. addition of new risks by the state govt other than the one mentioned below, by the state govt. is not permitted.\n\nprevented sowing/planting/germination risk: insured area is prevented ...",1509
14150,What characteristics should a good crop store have to prevent pest,"Good ventilation: Proper air circulation is crucial to prevent the buildup of moisture, which can attract pests like molds, mites, and insects. The store should have vents or fans to allow fresh air to enter and stale air to exit.\n\nDryness: Most pests prefer humid conditions, so a dry store is less attractive to them. The store should be free from leaks, and the walls and floor should be made of materials that do not absorb moisture.\n\nCleanliness: A clean store reduces the likelihood of ...",1493
2384,What characteristics should a good crop store have to prevent pest,"Good ventilation: Proper air circulation is crucial to prevent the buildup of moisture, which can attract pests like molds, mites, and insects. The store should have vents or fans to allow fresh air to enter and stale air to exit.\n\nDryness: Most pests prefer humid conditions, so a dry store is less attractive to them. The store should be free from leaks, and the walls and floor should be made of materials that do not absorb moisture.\n\nCleanliness: A clean store reduces the likelihood of ...",1493
11913,What are the problems facing farming organization in uganda?,"Limited access to finance: Many farming organizations in Uganda lack access to finance, which makes it difficult for them to invest in modern farming technologies, hire skilled workers, and expand their operations.\n\nLimited access to markets: Many small-scale farmers in Uganda struggle to access markets to sell their products, which can result in low prices and limited income.\n\nClimate change: Uganda is vulnerable to climate change, which can have a negative impact on crop yields and ove...",1420
13412,asking about farming of quil (wanted to farming just now),"recommended to 1.japanese quail and bobwhite quails are the domesticated varieties of quail. japanese quails are hardy, grows faster, has a short generation interval and is precocious. the meat is a delicacy. specific lines developed for egg production as well as meat production are available. 2.japanese quails are hardier. they seldom have disease problems. therefore, there is no need for routine immunization programme as with other poultry species. one major disease that affects japanese q...",1407

In [ ]:
# 3. Duplicate questions
duplicates = (
    df[df["question"].duplicated(keep=False)]
    .sort_values("question")
)

display(duplicates.head(30))

,question,answer
10932,"\nquery: 8no.s of local birds are sufferng from conjunctivities, offed since few days.\n","treatment:1. continue previous treatment. 2.wash the eyes with water mixed with common salt. 3. use eye drop @ 1drop to each eye, twice daily."
5681,"\nquery: 8no.s of local birds are sufferng from conjunctivities, offed since few days.\n","treatment:1. continue previous treatment. 2.wash the eyes with water mixed with common salt. 3. use eye drop @ 1drop to each eye, twice daily."
16634,query regarding government scheme for dairy developement programme,take the necessary information from district agriculturaloffice or krishi vigyan kendra of the respective à¤¡à¤¿à¤¸à¥à¤à¥à¤°à¤¿à¤à¥à¤? for the scheme implemented by the local government [ assam ]
19134,query regarding government scheme for dairy developement programme,take the necessary information from district agriculturaloffice or krishi vigyan kendra of the respective à¤¡à¤¿à¤¸à¥à¤à¥à¤°à¤¿à¤à¥à¤? for the scheme implemented by the local government [ assam ]
22382,query regarding some holstein fresian showing the liqifaction of milk,"ostocalcium & vimeral as directed , use milk min mixture & buffer for 10-15 days for liquifaction of milk"
13535,query regarding some holstein fresian showing the liqifaction of milk,"ostocalcium & vimeral as directed , use milk min mixture & buffer for 10-15 days for liquifaction of milk"
16846,query regarding croulier & broiler price in the market,"it depends upon the market flactuality , demand of the product in the market by costomer /the quality &lalatability of meat & meat product is the another factor of market flactuation [ production site to consumar site , cost of transportation etc ] too high price is not comfortable to all , it should be inform in local marketing group for the high rise of price in the commodity, there must be a equalibrum between the prise{ rs] & product [ but good product has always demand in market ]"
10046,query regarding croulier & broiler price in the market,"it depends upon the market flactuality , demand of the product in the market by costomer /the quality &lalatability of meat & meat product is the another factor of market flactuation [ production site to consumar site , cost of transportation etc ] too high price is not comfortable to all , it should be inform in local marketing group for the high rise of price in the commodity, there must be a equalibrum between the prise{ rs] & product [ but good product has always demand in market ]"
4401,query regarding the training programme of piggery unit,"told him to take the information from district veterinary office for govt scheme implemented by the government , information can also be obtained from research center situated at rani,[ nrc on pig] or from director of research , assam agricultural university guwahati khanapara campus"
6173,query regarding the training programme of piggery unit,"told him to take the information from district veterinary office for govt scheme implemented by the government , information can also be obtained from research center situated at rani,[ nrc on pig] or from director of research , assam agricultural university guwahati khanapara campus"
16959,"query regarding a goat showing the signs of oestrous , from which breed the semen is collected for artificial insemination","the she goat should be inseminated with good quality semen if it is showing the signs of oestrous , mainly black bengal & beetal semen are use for artificial insemination of goat in assam & n.e"
13672,"query regarding a goat showing the signs of oestrous , from which breed the semen is collected for artificial insemination","the she goat should be inseminated with good quality semen if it is showing the signs of oestrous , mainly black bengal & beetal semen are use for artificial insemination of goat in assam & n.e"
7797,query regarding some potato plant infested with blight,told him to spray indofil m 45 @ 2 gm / lits of water and repeat after 5-7 days
21316,query regarding some potato plant infested with blight,told him to spray indofil m 45 @ 2 gm / lits of water and repeat after 5-7 days
16637,"query regarding some tomato plant producing the the potato with arkish spot , suspected to be early blight infection","told him to spray ridomil gold @ 2 gm / lits of water at 3 days interval for 3 occations , spraying should be done preferably in morning or in evening hours , avoid the spray in rainy days"
8526,"query regarding some tomato plant producing the the potato with arkish spot , suspected to be early blight infection","told him to spray ridomil gold @ 2 gm / lits of water at 3 days interval for 3 occations , spraying should be done preferably in morning or in evening hours , avoid the spray in rainy days"
3647,query regarding the different species of dog.,"the species of dog are- alsatian , doberman , golden retriver , pug , afgan hound ,dalmatian , labrador, pomanarian etc"
15216,query regarding the different species of dog.,"the species of dog are- alsatian , doberman , golden retriver , pug , afgan hound ,dalmatian , labrador, pomanarian etc"
4604,query regarding the traumatic injury on neck of a pig resulting the occult blood from nose,"told him to clean the nose with betadine solution soaked cotton ,since the blood is already stop , give an course of antibiotic & antihistaminic , mustard oil can be rubbed gently inside the nostril ,soaked with cotton if bleeding has already stopped ."
10791,query regarding the traumatic injury on neck of a pig resulting the occult blood from nose,"told him to clean the nose with betadine solution soaked cotton ,since the blood is already stop , give an course of antibiotic & antihistaminic , mustard oil can be rubbed gently inside the nostril ,soaked with cotton if bleeding has already stopped ."
20823,query regarding two numbers of kid which are deprived of mother's milk,"told him to give milk replacer - thrice in daily , bottle feeding can be done for the kids with whole milk"
7404,query regarding two numbers of kid which are deprived of mother's milk,"told him to give milk replacer - thrice in daily , bottle feeding can be done for the kids with whole milk"
3934,query regarding use of anthalmintic in animals in assam & northeast,"generally, every six-month interval deworming should be done. in the case of assam & ne -preferably before rainy season [ march - april ] & before winter [ september - october ] deworming should be done ,; but deworming can be practised round the year because the assam & north -east is the heaven of parasite, except the gestation period of animal"
24072,query regarding use of anthalmintic in animals in assam & northeast,"generally, every six-month interval deworming should be done. in the case of assam & ne -preferably before rainy season [ march - april ] & before winter [ september - october ] deworming should be done ,; but deworming can be practised round the year because the assam & north -east is the heaven of parasite, except the gestation period of animal"
12498,query rgarding some local chicken consume less amount of water,"told him to check the room temperature of the premises , antistress [ zeetstress, vimeral ] can be use for 2-3 days , use developer or finisher ration , instead of starter"
16864,query rgarding some local chicken consume less amount of water,"told him to check the room temperature of the premises , antistress [ zeetstress, vimeral ] can be use for 2-3 days , use developer or finisher ration , instead of starter"
20039,)asking about the control measure of blossom end rot in tomato.,"suggested to maintain soil ph around 6.5 by liming and avoid water stress and also foliar application of calcium chloride @ 5 gram / litre of water at the time of fruit development and also suggested to apply urea instead of ammonium sulphate,as a source of nitrogen"
6792,)asking about the control measure of blossom end rot in tomato.,"suggested to maintain soil ph around 6.5 by liming and avoid water stress and also foliar application of calcium chloride @ 5 gram / litre of water at the time of fruit development and also suggested to apply urea instead of ammonium sulphate,as a source of nitrogen"
18269,)asking about the control measure of blossom end rot in tomato.,"suggested to maintain soil ph around 6.5 by liming and avoid water stress and also foliar application of calcium chloride @ 5 gram / litre of water at the time of fruit development and also suggested to apply urea instead of ammonium sulphate,as a source of nitrogen"
10931,. asking about some variety of tomato,"suggested about the variety like-punjab chhuhara,punjab keshri,pusa rubi,arka ava,arka alok etc"

In [ ]:
# Check whether duplicated questions have the same or different answers

duplicate_questions = df[df["question"].duplicated(keep=False)].copy()

duplicate_question_analysis = (
    duplicate_questions
    .groupby("question")["answer"]
    .nunique()
    .value_counts()
    .sort_index()
)

print("Number of duplicated questions:", duplicate_questions["question"].nunique())
print("\nNumber of unique answers per duplicated question:")
display(duplicate_question_analysis)

Number of duplicated questions: 2253

Number of unique answers per duplicated question:

answer
1    2225
2      28
Name: count, dtype: int64

In [ ]:
# Show examples where the same question has multiple different answers

multi_answer_questions = (
    duplicate_questions
    .groupby("question")
    .filter(lambda x: x["answer"].nunique() > 1)
    .sort_values("question")
)

print(
    "Questions with multiple different answers:",
    multi_answer_questions["question"].nunique()
)

display(multi_answer_questions.head(20))

Questions with multiple different answers: 28

,question,answer
9288,asking about management of blight in potato,told him to spray tilt fungicide (2ml/lit water) @ 3 psrays at 5 days interval
20356,asking about management of blight in potato,"told him that in case of cut seeds, the pieces are to be dipped in mancozeb (indofil m45) @ 5g in 1 lit of water for about 10 minutes. after treatment seeds are to be spread thinly and dried under shade for 48 hours, or should be covered with moist gunny bags for 2-3 days for suberization."
1735,asking about package of practice in okra.,recommended variety no. 10 and explaind in detail about the package of practice oof the same.
3411,asking about package of practice in okra.,"recommended varieties like no. 10 , pusa sawoni & arka anamika and explained in details about the pckge of practice to be followed of the same."
677,asking about the control measure to control bacterial wilt disease in tomato,suggested to spray streptocyclin (streptomycin sulphate)@200 miligram/liter of water at 15 days interval.
17714,asking about the control measure to control bacterial wilt disease in tomato,asking about the control measure to control bacterial wilt disease in tomato
13438,asking about the control measure against red rot disease in sugarcane.,advised him to burn the infected canes and not to cultivate sugarcane in the same field for next two years.
19959,asking about the control measure against red rot disease in sugarcane.,advised him to spray saff @ 2 gm./litre of water. also avoid ratooning and discard the severly infected canes.
19405,asking about the control measure of bacterial wilt.,suggested to apply one gram asaftida plus five gram of turmeric powder with ten litre of water in the affected field.
23359,asking about the control measure of bacterial wilt.,suggested to dench the soil with 1% agromycin.
23782,asking about the cultural practices in okra,"advised him to name of the variety- arka anamika, parbhani kranti"
24253,asking about the cultural practices in okra,"suggested him to apply 12kg urea, 40 kg ssp,10 kg mop /bigha\r\nseed rate-2.8 kg/bigha\r\nspacing -(row to row *plant to plant)\r\n (30 cm *15 cm)"
14895,asking about the cultural practices in watermelon,"suggested him to apply 17 kg urea,33 kg ssp,13 kg mop /bigha \r\nseed rate =1kg /bigha \r\nspacing =(row to row *plant to plant)\r\n (2.5m*2m)\r\nvariety=new hampshire midget,asahi yamato,pusa bedana,sugar baby,faizabadi"
11358,asking about the cultural practices in watermelon,told him that 2 to 3 seeds in one pit with the spacing of 2.5 m* 2m
10661,asking about the cultural practices of brinjal,"advice him to apply urea 15 kg, ssp 42 kg,mop 11 kg ,borax 1.5 kg"
11115,asking about the cultural practices of brinjal,given in details about the cultural practices
20531,asking about the dewormer of a calf.,suggested to administer fentas plus tab @ 1 tab at empty stomach and also provide liv52 bolus @ 1/2 bolus daily for a three consecutive days.
8222,asking about the dewormer of a calf.,suggested to administer albomar susp.@ 15 ml orally at empty stomach and administer liv52 bolus @ 1/2 bolus daily for four consecutive days.
6392,asking about the pit size for coconut planting,"suggested him to prepare a pit size of 1m*1m*1m along with this pit should be filled up with mixture of top soil, 20kg compost or dried cowdung and 100 g of 5% malathion dust up to 2/3 rd of pit."
17257,asking about the pit size for coconut planting,pit size is-1 metre x 1 metre x 1 metre

In [ ]:
# Exact duplicate question-answer pairs

exact_duplicates = df[df.duplicated(
    subset=["question", "answer"],
    keep=False
)].copy()

print("Rows belonging to duplicate QA pairs:", len(exact_duplicates))
print(
    "Unique duplicated QA pairs:",
    exact_duplicates[["question", "answer"]].drop_duplicates().shape[0]
)

display(exact_duplicates.head(20))

Rows belonging to duplicate QA pairs: 4569
Unique duplicated QA pairs: 2227

,question,answer
16,asking about the cultivation process for mushroom.,"advised to take paddy straw and cut into 2 inch pieces.boil it.take oyester mushroom cultivation polythene,puncture it in various points.lay the straw,put the spown on the straw.keep 5 straw layers and 4 spown layers.keep the begs in dark room.remove the polythene after 15 days.start harvesting after 22-24 days."
17,How does brown rot or bangle blight spread and survive in potato plants?,"The main sources of primary infection are infected soil and seed tubers. Brown rot affected plant parts decay and release masses of bacteria into the soil, where they can remain viable from season to season. The bacteria in the soil are disseminated by wind from one field to another. Infection usually occurs through wounds in the root system. The pathogen can survive for various periods in infested soil or water, forming a reservoir source of inoculum. It can also spread from infected to hea..."
19,asking hybrid var. of rice for assam condition,suggested him var.arize is suitable for assam condition
20,asking about the fertilizer application in rice after transplanting,recommended him to apply urea 4.5 kg /bigha as a topdessing
27,asking about type of cultivable vegetable in this season.,"told him to go for okra, bottle gourd, ridge gourd etc."
34,What marketing strategies can I use to promote my potato crop?,"Effective marketing strategies for potatoes include branding, packaging, direct sales at farmers' markets or local grocery stores, community-supported agriculture (CSA) programs, and online sales platforms. Offering specialty or heirloom potato varieties, promoting unique flavor profiles, and engaging with customers through cooking demonstrations or recipe sharing can also help attract buyers and build brand loyalty."
35,asking about some recommended planting materials of tea,"advised to plant recommended planting materials like:(a)clone-tv1,tv18,tv20,tv21,tv22,tv23,tv24,pl26a and (b)seed-ts450,ts462,ts464,betajan jat."
44,asking about the ant problem in sugarcane,application of tricel 2 @ 2 ml per litre of water
49,asking last sowing time of black gram,suggested him blackgram can be sown upto 15 nov
51,want to know control measure of blast disease in paddy,adviced to apply bavistin @ 2 gm per liter of water
57,asking about prophylactic spraying of fungicides in tomato,"depending upon weather conditions particularly on cloudy weather mancozeb/pradhan 75 wp (2 g/l) should be sprayed as prophylactic measure. alternatively, dithane z-78 @ (2.5 g in 1 lit of water) can be used. if disease appears, spraying should be done at an interval of 7 to 10 days depending upon weather condition.while spraying care should be taken to cover the lower sides of the leaves."
62,asking about the planting season of tomato,told him the planting season of tomato is august to september
64,asking about treatment of cough in cow.,suggested to administer caflon powder @ 50 gm thrice daily along with gur for five days.
70,asking about post harvest management for storage of potato for seed purpose,recommended to treat the seed with mancozeb or captan @ 3gm per kg of seed before storing \r\nalso apply malathion dust
72,query regarding contrl of blight in tomato.,do the ozzo test first. if the test comes ositive then spray and apply strptocyclin/ streptomycin 1 gram/5 liters of water 3 times at 5 days interval in the evening time. or if the test is negative then please apply blitox 50 3 gram per liters of water as same as sterptocyclin.
85,enquired abour fertilizer dose of sali rice,"suggested - urea 18kg/bigha , 17 kg/bigha ssp , 4 kg/bigha mop. urea into 3 equal part"
96,query regarding control of argulosis in carps,adviced to use cleaner @ 2 ppm level
103,What are the characteristics of the pathogen causing late blight in potato plants?,"The pathogen causing late blight in potato plants is Phytophthora infestans. Its mycelium is endophytic, coenocytic, and hyaline, with intercellular double club-shaped haustoria. Sporangiophores are hyaline, branched, intermediate, and thick-walled. Sporangia are thin-walled, hyaline, oval or pear-shaped with a definite papilla at the apex. Zoospores are biflagellate with fine hairs."
104,What is the disease cycle of Downy Mildew?,"The disease overwinters primarily as mycelium in infected onions that remain in fields or nearby cull piles. It can also overwinter in perennial onion varieties in home gardens. Spores produced by overwintering fungal mycelium infect leaves of onion plants in commercial fields under favorable environmental conditions. The mycelium in infected onion leaves produces new spores called conidia in cycles, resulting in severe epidemics if favorable conditions persist."
106,askinmg about the age of seedlings of ranjit variety to cultivate as sali paddy.,suggested mr sarang to use one month age of ranjit variety seedlings to cultivate as sali paddy.

In [ ]:
# Create a cleaned copy of the dataset
df_clean = df.copy()

# Remove exact duplicate question-answer pairs
df_clean = df_clean.drop_duplicates(
    subset=["question", "answer"],
    keep="first"
).reset_index(drop=True)

print("Original dataset size:", len(df))
print("Cleaned dataset size:", len(df_clean))
print("Rows removed:", len(df) - len(df_clean))

Original dataset size: 25410
Cleaned dataset size: 23068
Rows removed: 2342

In [ ]:
# Verify exact duplicate QA pairs have been removed

remaining_duplicates = df_clean.duplicated(
    subset=["question", "answer"]
).sum()

print("Remaining duplicate QA pairs:", remaining_duplicates)

Remaining duplicate QA pairs: 0

In [ ]:
# Basic audit of the cleaned dataset

print("Shape:", df_clean.shape)
print("\nMissing values:")
print(df_clean.isnull().sum())

print("\nDuplicate questions:")
print(df_clean["question"].duplicated().sum())

print("\nDuplicate QA pairs:")
print(df_clean.duplicated(subset=["question", "answer"]).sum())

Shape: (23068, 2)

Missing values:
question    0
answer      0
dtype: int64

Duplicate questions:
28

Duplicate QA pairs:
0

In [ ]:
# Keywords for identifying possible livestock/veterinary questions

livestock_keywords = [
    "cattle",
    "cow",
    "calf",
    "buffalo",
    "goat",
    "sheep",
    "lamb",
    "pig",
    "poultry",
    "chicken",
    "broiler",
    "hen",
    "duck",
    "fish",
    "carp",
    "livestock",
    "animal",
    "veterinary",
    "deworm",
    "dewormer",
    "indigestion"
]

# Search both questions and answers
text = (
    df_clean["question"].fillna("").str.lower()
    + " "
    + df_clean["answer"].fillna("").str.lower()
)

livestock_mask = text.str.contains(
    "|".join(livestock_keywords),
    regex=True,
    na=False
)

print("Potential livestock/veterinary rows:", livestock_mask.sum())
print(
    "Percentage of dataset:",
    round(livestock_mask.mean() * 100, 2),
    "%"
)

Potential livestock/veterinary rows: 3440
Percentage of dataset: 14.91 %

In [ ]:
# Display some potential livestock/veterinary examples

livestock_examples = df_clean.loc[
    livestock_mask,
    ["question", "answer"]
]

display(livestock_examples.head(30))

,question,answer
13,asking about the length of oetrus cycle in cow.,the length of oestrus cycle is 21 days in cow.
16,asking about the cultivation process for mushroom.,"advised to take paddy straw and cut into 2 inch pieces.boil it.take oyester mushroom cultivation polythene,puncture it in various points.lay the straw,put the spown on the straw.keep 5 straw layers and 4 spown layers.keep the begs in dark room.remove the polythene after 15 days.start harvesting after 22-24 days."
18,asking about infection in eye of a pig.,suggested to give ciplox eye drop @ 3 drops in each eye twice daily for 5 days. along with that administer meriquin 50 mg tab twice daily for 5 days.
21,asking about treatment of silent heat in cow.,suggested to wait for 5 days because the next heat is coming within 5 days.
25,asking about treatment of cough in goat.,suggested to administer caflon powder @ 25 gm thrice daily for 5 days.
26,asking about treatment of worms infestation in goat.,suggested to administer panacur 150 mg tab.@ 1 tab./30 kg body weight.along with that administer liv-52 vet @ 5 ml. twice daily.
31,asking about the process of air layering in litchi.,"advised to select branches of 1-1.5 yr old of pencil thickness.remove the barks up to cambium layer around 3 inches long.put a mixture of dry cowdung ,soil and saw dust around the bark removed portion and wrap with polythene and tie the both ends.after 1.5 months rooting will take place.then cut the branch and plant in poly bag for 2 months.appropriate time for layering is from may and planting in main field in sept."
33,What other crops can be inter cropped with cassava without interference in yield reduction?,"Legumes: Legumes such as cowpeas, soybeans, and groundnuts"
48,asking about fish mortality for gas formation in pond in South Asia context in Pakistan agriculture,recommended that application of salt @ 10kg/bigha and throughing piece of banana tree.feed given on onion bag.stop feed broadcasting.
60,wanted to know the fertilizer required in one bigha of green gram,advised to apply 5 kg urea 38 kg super and 1 quintle cowdang
64,asking about treatment of cough in cow.,suggested to administer caflon powder @ 50 gm thrice daily along with gur for five days.
65,asking about leaf curl disease in potato.,suggested to mix rogor 2 ml/liter of water and then spray.
72,query regarding contrl of blight in tomato.,do the ozzo test first. if the test comes ositive then spray and apply strptocyclin/ streptomycin 1 gram/5 liters of water 3 times at 5 days interval in the evening time. or if the test is negative then please apply blitox 50 3 gram per liters of water as same as sterptocyclin.
73,query regarding some local chicken showing the signs of bacillary white diarrhoea,give tetracycline powder @ 1 gm / lits of water for 3-4 days duaprim powder & ors with drinking water as directed
80,asking about fish feed management in pond,feed= average fish size (weight) x feed rate (%) x total number of fish in the pond
86,asmking about treatment of anorexia in calf.,suggested to administer liv-52 @ 10 ml twice daily for the treatment of anorexia in calf.
88,asking about treatmenet of coccidiosis in poultry.,suggested to administer cocci free twice daily for five days.
96,query regarding control of argulosis in carps,adviced to use cleaner @ 2 ppm level
108,asking about control of algal blooms in fish pond,"partial to full cloudy sky with 5-8 octa will prevail during next 5 days. 3.0, 4.0 mm rainfall is\npredicted on 15th & 16th march, 2020. mainly north-easterly wind with a speed of 9.4-14.2\nkmph is expected. maximum temperature is predicted as 29.0-31.0Â°c and minimum as\n16.0-18.0Â°c. morning and evening relative humidity will be around 53-68% and 33-46%\nduring next 5 days"
120,asking that her pregnant goat is suffering from low voice.,neurobion tab. 10 no.s @ 1tab orally aily in the evening.
121,asking for the manures and fertilizer doses requirement for a seed bed of 10 metre in length & 1.25 metre in width to raise seedlings of boro rice.,"20-30 kilo grams of cowdung/compost, 40 grams of urea, 80 grams of single super phosphate and 40 grams of muriate of potash are to be applied and mixed well with the soil has been replied as the manures and fertilizer doses requirement for a seed bed of 10 metre in length & 1.25 metre in width to raise seedlings of boro rice."
132,weed control measure when the paddy is 2 months old,suggested to do cultural and mechanical weeding as the chemical weeding at this stage is critical.
133,asking about whether fish are eatable after copper sulfate application for red color treatment in fish pond,you can fish if the color of the pond become normal.
142,asking about the time and process of air layaring of litchi,"recommended time for layering is may-june(rainy season),select pencil thicness branch of 1-1.5 yrs old.remove the bark layer up to cambium about 3 inches.put mixture of mud and cowdung on the removed portion .tie with polythene for 1 yr.cut the layer as soon as roots initiates.planting is done in aug-sept."
155,asking about the control of trunk borer pest attack in lemon in South Asia context in Pakistan agriculture in Pakistan agriculture,suggested that propylactic smearing of monocrotophos with lime and water(1:1:25)should be applied up to one metre from the base of the tree during march/april which prevents the adult from laying egg. and also the hole should be plugged with cotton/cloths soaked in insecticides like dimecron 5 ml/ litre of water and then plasterd with mud to have an airtight condition.
158,asking about poor growth of a pig.,suggested to administer agrimin forte @ 1 tsf and ostovet liq @ 2 tsf orally daily for a month.
166,query ragarding chilli cultivation with goat dung,recommended him to cultivate chilli with dried goat dung
205,asking about gestation period of a cow.,the gestation period of a cow is 280-285 days.
209,query regrding preparation of silage from maize.,"after harvesting dry the maize fodder properly under sun, then packed in air tight polythene bag and stored in a dry place. when ever needed you can feed it to the animals."
220,asking is it advisable to use multi micro nutrient mineral fertilizer in fish pond,"yes, but in recomended dosage as suggested on the bags"

In [ ]:
# Strong livestock/veterinary keywords
livestock_question_keywords = [
    "cattle",
    "cow",
    "calf",
    "buffalo",
    "goat",
    "sheep",
    "lamb",
    "pig",
    "poultry",
    "chicken",
    "broiler",
    "hen",
    "duck",
    "fish",
    "carp",
    "livestock",
    "veterinary",
    "animal",
    "oestrus",
    "estrus",
    "gestation",
    "cough in cow",
    "cough in goat",
    "worms infestation in goat",
    "anorexia in calf",
    "coccidiosis in poultry"
]

question_text = df_clean["question"].fillna("").str.lower()

livestock_question_mask = question_text.str.contains(
    "|".join(livestock_question_keywords),
    regex=True,
    na=False
)

print("Potential livestock/veterinary questions:", livestock_question_mask.sum())
print(
    "Percentage of dataset:",
    round(livestock_question_mask.mean() * 100, 2),
    "%"
)

Potential livestock/veterinary questions: 2392
Percentage of dataset: 10.37 %

In [ ]:
livestock_question_examples = df_clean.loc[
    livestock_question_mask,
    ["question", "answer"]
]

display(livestock_question_examples.head(50))

,question,answer
13,asking about the length of oetrus cycle in cow.,the length of oestrus cycle is 21 days in cow.
18,asking about infection in eye of a pig.,suggested to give ciplox eye drop @ 3 drops in each eye twice daily for 5 days. along with that administer meriquin 50 mg tab twice daily for 5 days.
21,asking about treatment of silent heat in cow.,suggested to wait for 5 days because the next heat is coming within 5 days.
25,asking about treatment of cough in goat.,suggested to administer caflon powder @ 25 gm thrice daily for 5 days.
26,asking about treatment of worms infestation in goat.,suggested to administer panacur 150 mg tab.@ 1 tab./30 kg body weight.along with that administer liv-52 vet @ 5 ml. twice daily.
48,asking about fish mortality for gas formation in pond in South Asia context in Pakistan agriculture,recommended that application of salt @ 10kg/bigha and throughing piece of banana tree.feed given on onion bag.stop feed broadcasting.
64,asking about treatment of cough in cow.,suggested to administer caflon powder @ 50 gm thrice daily along with gur for five days.
73,query regarding some local chicken showing the signs of bacillary white diarrhoea,give tetracycline powder @ 1 gm / lits of water for 3-4 days duaprim powder & ors with drinking water as directed
80,asking about fish feed management in pond,feed= average fish size (weight) x feed rate (%) x total number of fish in the pond
86,asmking about treatment of anorexia in calf.,suggested to administer liv-52 @ 10 ml twice daily for the treatment of anorexia in calf.
88,asking about treatmenet of coccidiosis in poultry.,suggested to administer cocci free twice daily for five days.
96,query regarding control of argulosis in carps,adviced to use cleaner @ 2 ppm level
108,asking about control of algal blooms in fish pond,"partial to full cloudy sky with 5-8 octa will prevail during next 5 days. 3.0, 4.0 mm rainfall is\npredicted on 15th & 16th march, 2020. mainly north-easterly wind with a speed of 9.4-14.2\nkmph is expected. maximum temperature is predicted as 29.0-31.0Â°c and minimum as\n16.0-18.0Â°c. morning and evening relative humidity will be around 53-68% and 33-46%\nduring next 5 days"
120,asking that her pregnant goat is suffering from low voice.,neurobion tab. 10 no.s @ 1tab orally aily in the evening.
132,weed control measure when the paddy is 2 months old,suggested to do cultural and mechanical weeding as the chemical weeding at this stage is critical.
133,asking about whether fish are eatable after copper sulfate application for red color treatment in fish pond,you can fish if the color of the pond become normal.
158,asking about poor growth of a pig.,suggested to administer agrimin forte @ 1 tsf and ostovet liq @ 2 tsf orally daily for a month.
166,query ragarding chilli cultivation with goat dung,recommended him to cultivate chilli with dried goat dung
205,asking about gestation period of a cow.,the gestation period of a cow is 280-285 days.
220,asking is it advisable to use multi micro nutrient mineral fertilizer in fish pond,"yes, but in recomended dosage as suggested on the bags"
245,asking about how to apply cowdung in pond,"advised 10,000kg/ha/yr cowdung is useful for fish."
247,asking about how to control chronic respiratory diseases in broiler birds of about 30 days old,advice to administer tetracycline powder @ 5 gram mixed in 1.5-2 lits of water and give it daily for 5-7 days
271,asking to know about delaid in parturation of a cow,consult with a vet surgeon suspected as dystokia
279,query regarding small size of pimple formation in the mouth lesion in goat,advice to wash the affected lesion with potassium permanganate solution and few drops of water by means of a cotton plug after that administer 1/6 th of avil tablet daily for 2-3 days
286,query regarding vaccine for goat that is stored in ice pack in flask for 20 days after 1 st use,vaccine can be given to the goat if stored properly [ at 4 degre centegrade ] after the the initial use
288,asking about stocking density at fish pond of size 0.14 hac.,adviced to maintain stok @1000-1500 nos. of fingerlings
310,asking about stoking density of fish finger ling.,suggested to maintain 1000 nos of finger ling per bigha water spread area.
315,asking about the cpntrol-measure of inflammatory condition in cow,advice to administer oxalgin bolus @2 bolus daily for 3 days
317,asking about the floor space requirement in broiler farm having 1000 capacity,floor space requirement for 1000 birds = 22 ft x 60 ft ( @ 1.3 sq ft per broiler )
320,query regarding decrease let down of milk from acow,"ostocalcium , vimeral ,can be given as directed gowala can be given as feed additive"
324,query regarding breed information & availabolity of duck,"ask him to take the information from from livestock & poultry department of assam at khanapara/ department of lpm ( aau ) / department of poultry science, khanapara"
325,asked about where to get fisheries training,advised him to visit district fishery officer
354,asking about control of repeat breeding in cow,"suggested to feed colostrum to newly and give vitamine a injection like prepaline fort, herbal preparation like prajana capsule @ 3 capsule orally with mollases, mineral mixture like minal fort powder along with sufficient green grasses and concentrate f"
366,asking about correction of bad habbit for poultry.,explain in details about the correction of bad habbit of poultry.
373,asking about culture practice of spawn fish,explained according to the package of practice
378,query regarding some local chicken with decrease growth,told him to give shrkoferol / biospark @ 10 ml / 100 bids
386,asking that his piglet is suffering from conjunctivities.,"tr.: 1. wash with luke worm water mixed with common salt, 2. cipro eye drop 1 ph @ 2 drops to each eye 3 times daily."
405,asking about fish feed supplement in fish grow out farming,"suggestion \ninstead of mustard oil cake you can use ground nut oil cake with rice bran \napply rice bran and ground nut oil cake @ 1:1 ratio as i told you earlier\nsupplementary feed include floating feed which is for grass carp, catla, rohu, big head \nand sinking feed for common carp and mirgal\nbuy supplementary feed containing 24 % protein content \nsome of the feed company are godrej, abis, nsf\nin winter time please reduce the feed quantity\n\n"
430,asking about treatment of weakness in duck.,suggested to administer ambiplex to the duck.
447,query regarding some pigeon showing the signs of diarrhoea,"told him to give enrocin 1 gm / lits of water , tab lomophen 1 nos for 70 nos of pigeon, ors with drinking water for 3-4 days"
450,"query regarding some piglet sowing the signs of inappitance, besides the dose of anthalmintic [ piperazine citrate ]",told him to give ingest / ruchamax - 5-10 g orally daily with feed. piperazine @ 5-10 ml orally in empty stomach depending upon the body weight
453,"telling that they are in a group of 4 unemployed youths and to start a entrepreunership in poultry farming, where they can avail a training.","advised to coordinate with the state institute of rural development, located at khanapara which is nearest to his locality."
461,asking about treatment of bloat in cow,suggested to administer afanil liq.@ 100 ml at a time and repeat the same dose after 6 hours.
485,asking for control-measure of maggoted wound in lactating cow as well as newly born calf,"advice to apply terpentine oil plus topicure spray over the cotton plug and allow to keep it for 1 days ,then inject melonex @5 ml and anistamin @4ml in case of cow;in calf administer melonex tablet-1 tab daily for 1 days"
489,asking about control of fungal infection of cowpea.,suggested him to spray saaf 3 times at 5 days interval mixing 2 gram per liter of water\n
492,asking about the treatment of diarrhoea in a calf.,suggested to administer caflon pow. @ 2-3 tsf orally twice a day.
494,asking about fish mortality for gas formation in South Asia context in Pakistan agriculture,recommended that application of salt @10 kg/bigha and throughing piece of banana tree .after 5 days of salt treatment lime application @10 kg/bigha .stop feed broadcasting .feed given on onion bag.
499,query regarding feeding of fish in pond in South Asia context in Pakistan agriculture in Pakistan agriculture in Pakistan agriculture,"advice him to apply rice bran,mustered oil cake,wheat bran,grined dry fish and micronutrients for better growth of fish"
504,asking about indigestion problem in a pig.,suggested to administer aciloc-150 tab orally twice a day .
517,asking about the nutrition of a cow.,suggested to administer calcium syrup as well as mineral mix. daily .

In [ ]:
import re

livestock_question_keywords = [
    "cattle",
    "cow",
    "calf",
    "buffalo",
    "goat",
    "sheep",
    "lamb",
    "pig",
    "poultry",
    "chicken",
    "broiler",
    "hen",
    "duck",
    "fish",
    "carp",
    "livestock",
    "veterinary",
    "animal",
    "oestrus",
    "estrus",
    "gestation",
    "parturation"
]

pattern = r"\b(" + "|".join(map(re.escape, livestock_question_keywords)) + r")\b"

question_text = df_clean["question"].fillna("").str.lower()

livestock_question_mask = question_text.str.contains(
    pattern,
    regex=True,
    na=False
)

print("Potential livestock/veterinary questions:", livestock_question_mask.sum())
print(
    "Percentage of dataset:",
    round(livestock_question_mask.mean() * 100, 2),
    "%"
)

Potential livestock/veterinary questions: 1950
Percentage of dataset: 8.45 %

/tmp/ipykernel_944/2148039660.py:32: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  livestock_question_mask = question_text.str.contains(

In [ ]:
livestock_question_examples = df_clean.loc[
    livestock_question_mask,
    ["question", "answer"]
]

display(livestock_question_examples.head(50))

,question,answer
13,asking about the length of oetrus cycle in cow.,the length of oestrus cycle is 21 days in cow.
18,asking about infection in eye of a pig.,suggested to give ciplox eye drop @ 3 drops in each eye twice daily for 5 days. along with that administer meriquin 50 mg tab twice daily for 5 days.
21,asking about treatment of silent heat in cow.,suggested to wait for 5 days because the next heat is coming within 5 days.
25,asking about treatment of cough in goat.,suggested to administer caflon powder @ 25 gm thrice daily for 5 days.
26,asking about treatment of worms infestation in goat.,suggested to administer panacur 150 mg tab.@ 1 tab./30 kg body weight.along with that administer liv-52 vet @ 5 ml. twice daily.
48,asking about fish mortality for gas formation in pond in South Asia context in Pakistan agriculture,recommended that application of salt @ 10kg/bigha and throughing piece of banana tree.feed given on onion bag.stop feed broadcasting.
64,asking about treatment of cough in cow.,suggested to administer caflon powder @ 50 gm thrice daily along with gur for five days.
73,query regarding some local chicken showing the signs of bacillary white diarrhoea,give tetracycline powder @ 1 gm / lits of water for 3-4 days duaprim powder & ors with drinking water as directed
80,asking about fish feed management in pond,feed= average fish size (weight) x feed rate (%) x total number of fish in the pond
86,asmking about treatment of anorexia in calf.,suggested to administer liv-52 @ 10 ml twice daily for the treatment of anorexia in calf.
88,asking about treatmenet of coccidiosis in poultry.,suggested to administer cocci free twice daily for five days.
108,asking about control of algal blooms in fish pond,"partial to full cloudy sky with 5-8 octa will prevail during next 5 days. 3.0, 4.0 mm rainfall is\npredicted on 15th & 16th march, 2020. mainly north-easterly wind with a speed of 9.4-14.2\nkmph is expected. maximum temperature is predicted as 29.0-31.0Â°c and minimum as\n16.0-18.0Â°c. morning and evening relative humidity will be around 53-68% and 33-46%\nduring next 5 days"
120,asking that her pregnant goat is suffering from low voice.,neurobion tab. 10 no.s @ 1tab orally aily in the evening.
133,asking about whether fish are eatable after copper sulfate application for red color treatment in fish pond,you can fish if the color of the pond become normal.
158,asking about poor growth of a pig.,suggested to administer agrimin forte @ 1 tsf and ostovet liq @ 2 tsf orally daily for a month.
166,query ragarding chilli cultivation with goat dung,recommended him to cultivate chilli with dried goat dung
205,asking about gestation period of a cow.,the gestation period of a cow is 280-285 days.
220,asking is it advisable to use multi micro nutrient mineral fertilizer in fish pond,"yes, but in recomended dosage as suggested on the bags"
247,asking about how to control chronic respiratory diseases in broiler birds of about 30 days old,advice to administer tetracycline powder @ 5 gram mixed in 1.5-2 lits of water and give it daily for 5-7 days
271,asking to know about delaid in parturation of a cow,consult with a vet surgeon suspected as dystokia
279,query regarding small size of pimple formation in the mouth lesion in goat,advice to wash the affected lesion with potassium permanganate solution and few drops of water by means of a cotton plug after that administer 1/6 th of avil tablet daily for 2-3 days
286,query regarding vaccine for goat that is stored in ice pack in flask for 20 days after 1 st use,vaccine can be given to the goat if stored properly [ at 4 degre centegrade ] after the the initial use
288,asking about stocking density at fish pond of size 0.14 hac.,adviced to maintain stok @1000-1500 nos. of fingerlings
310,asking about stoking density of fish finger ling.,suggested to maintain 1000 nos of finger ling per bigha water spread area.
315,asking about the cpntrol-measure of inflammatory condition in cow,advice to administer oxalgin bolus @2 bolus daily for 3 days
317,asking about the floor space requirement in broiler farm having 1000 capacity,floor space requirement for 1000 birds = 22 ft x 60 ft ( @ 1.3 sq ft per broiler )
324,query regarding breed information & availabolity of duck,"ask him to take the information from from livestock & poultry department of assam at khanapara/ department of lpm ( aau ) / department of poultry science, khanapara"
354,asking about control of repeat breeding in cow,"suggested to feed colostrum to newly and give vitamine a injection like prepaline fort, herbal preparation like prajana capsule @ 3 capsule orally with mollases, mineral mixture like minal fort powder along with sufficient green grasses and concentrate f"
366,asking about correction of bad habbit for poultry.,explain in details about the correction of bad habbit of poultry.
373,asking about culture practice of spawn fish,explained according to the package of practice
378,query regarding some local chicken with decrease growth,told him to give shrkoferol / biospark @ 10 ml / 100 bids
405,asking about fish feed supplement in fish grow out farming,"suggestion \ninstead of mustard oil cake you can use ground nut oil cake with rice bran \napply rice bran and ground nut oil cake @ 1:1 ratio as i told you earlier\nsupplementary feed include floating feed which is for grass carp, catla, rohu, big head \nand sinking feed for common carp and mirgal\nbuy supplementary feed containing 24 % protein content \nsome of the feed company are godrej, abis, nsf\nin winter time please reduce the feed quantity\n\n"
430,asking about treatment of weakness in duck.,suggested to administer ambiplex to the duck.
453,"telling that they are in a group of 4 unemployed youths and to start a entrepreunership in poultry farming, where they can avail a training.","advised to coordinate with the state institute of rural development, located at khanapara which is nearest to his locality."
461,asking about treatment of bloat in cow,suggested to administer afanil liq.@ 100 ml at a time and repeat the same dose after 6 hours.
485,asking for control-measure of maggoted wound in lactating cow as well as newly born calf,"advice to apply terpentine oil plus topicure spray over the cotton plug and allow to keep it for 1 days ,then inject melonex @5 ml and anistamin @4ml in case of cow;in calf administer melonex tablet-1 tab daily for 1 days"
492,asking about the treatment of diarrhoea in a calf.,suggested to administer caflon pow. @ 2-3 tsf orally twice a day.
494,asking about fish mortality for gas formation in South Asia context in Pakistan agriculture,recommended that application of salt @10 kg/bigha and throughing piece of banana tree .after 5 days of salt treatment lime application @10 kg/bigha .stop feed broadcasting .feed given on onion bag.
499,query regarding feeding of fish in pond in South Asia context in Pakistan agriculture in Pakistan agriculture in Pakistan agriculture,"advice him to apply rice bran,mustered oil cake,wheat bran,grined dry fish and micronutrients for better growth of fish"
504,asking about indigestion problem in a pig.,suggested to administer aciloc-150 tab orally twice a day .
517,asking about the nutrition of a cow.,suggested to administer calcium syrup as well as mineral mix. daily .
519,asking about good breed cattle for farming.,jersey is the good breed cattle for farming at assam.
520,asking about the availability of dairy cattle,"you have to collect the cattle from individual farmer or local livestock trader . the area where you can get good quality dairy cattle are khanapara , nine mile , barnihat etc"
521,asking about the duck cum fish farming,explain in detail about the duck cum fish farming
525,asking about treatment of inflamation in leg of a cow.,suggested to inject melonex injection once daily. along with that inject dicrysticin injection once daily for 5 days.
526,aksed about the pig cum fish farming.,given in detail about the pig cum fish farming.
541,asking about regional pig farming in ranee in guwahati,recommended to visit the office of the regional pig farming and discuss for trainning for pig farming
545,asking about treatment of feather loss in duck.,suggested to administer ambiplex along with feed.
569,asked about surfacing of fish and control of algal bloom.,"stop application of fertilizers and feeding immediately, add freshwater to the pond, removal of excessive decayed or half decayed organic matter and aquatic weeds. removal of algal bloom by controlling feeding, fertilizers and also control algal bloom by manually and liming."
575,asking about the importance of liming in fish pond,advised him in detail about the importance of liming in fish pond

In [ ]:
# Use a non-capturing group to avoid the regex warning
pattern = r"\b(?:" + "|".join(map(re.escape, livestock_question_keywords)) + r")\b"

question_text = df_clean["question"].fillna("").str.lower()

livestock_question_mask = question_text.str.contains(
    pattern,
    regex=True,
    na=False
)

# Remove livestock, veterinary, poultry, and aquaculture questions
df_agri = df_clean.loc[~livestock_question_mask].copy().reset_index(drop=True)

print("Original cleaned dataset:", len(df_clean))
print("Rows removed:", livestock_question_mask.sum())
print("Agriculture dataset:", len(df_agri))

Original cleaned dataset: 23068
Rows removed: 1950
Agriculture dataset: 21118

In [ ]:
remaining_livestock = df_agri["question"].str.lower().str.contains(
    pattern,
    regex=True,
    na=False
).sum()

print("Remaining livestock/veterinary questions:", remaining_livestock)

Remaining livestock/veterinary questions: 0

In [ ]:
print("Shape:", df_agri.shape)

print("\nMissing values:")
print(df_agri.isnull().sum())

print("\nDuplicate QA pairs:")
print(
    df_agri.duplicated(
        subset=["question", "answer"]
    ).sum()
)

print("\nDuplicate questions:")
print(df_agri["question"].duplicated().sum())

Shape: (21118, 2)

Missing values:
question    0
answer      0
dtype: int64

Duplicate QA pairs:
0

Duplicate questions:
18

In [ ]:
# Clean whitespace in questions and answers

df_agri["question"] = (
    df_agri["question"]
    .astype(str)
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

df_agri["answer"] = (
    df_agri["answer"]
    .astype(str)
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

print("Whitespace cleaning complete.")

Whitespace cleaning complete.

In [ ]:
empty_questions = (df_agri["question"] == "").sum()
empty_answers = (df_agri["answer"] == "").sum()

print("Empty questions:", empty_questions)
print("Empty answers:", empty_answers)

Empty questions: 0
Empty answers: 0

In [ ]:
df_agri["question_words"] = df_agri["question"].str.split().str.len()
df_agri["answer_words"] = df_agri["answer"].str.split().str.len()

print("Question word statistics:")
print(df_agri["question_words"].describe())

print("\nAnswer word statistics:")
print(df_agri["answer_words"].describe())

Question word statistics:
count    21118.000000
mean        10.333602
std          4.636509
min          7.000000
25%          8.000000
50%          9.000000
75%         12.000000
max        135.000000
Name: question_words, dtype: float64

Answer word statistics:
count    21118.000000
mean        19.033479
std         16.589152
min          7.000000
25%         10.000000
50%         13.000000
75%         21.000000
max        548.000000
Name: answer_words, dtype: float64

In [ ]:
print("10 longest questions:")
display(
    df_agri.nlargest(10, "question_words")[
        ["question", "question_words"]
    ]
)

print("\n10 longest answers:")
display(
    df_agri.nlargest(10, "answer_words")[
        ["answer", "answer_words"]
    ]
)

10 longest questions:

,question,question_words
14912,date rainfall (mm) temp (max/min) humidity (max/min) wind 04 may 0 29.8 / 22.4 73.0 / 83.0 7.4 05 may 152.0 32.0 / 21.0 54.0 / 0 5.0 06 may 11.0 26.0 / 21.0 71.0 / 0 7.0 07 may 9.0 28.0 / 21.0 61.0 / 0 6.0 08 may 4.0 30.0 / 21.0 50.0 / 0 6.0 09 may 14.0 31.0 / 22.0 51.0 / 0 6.0date rainfall (mm) temp (max/min) humidity (max/min) wind 04 may 0 29.8 / 22.4 73.0 / 83.0 7.4 05 may 152.0 32.0 / 21.0 54.0 / 0 5.0 06 may 11.0 26.0 / 21.0 71.0 / 0 7.0 07 may 9.0 28.0 / 21.0 61.0 / 0 6.0 08 may 4.0 3...,135
13043,"told him that it is a pension scheme under which an amount of rs 3000 will be deposited on monthly basis after attaining the age of 60 yrs. age of registration is 18 -40yrs documents required are land documents (less than 15 bigha), bank pass book, bani ifsc code, spouse name & dob, aadhar card. monthly contribution will be required to pay from your end. ineligible condition- person who are inservice in any govt. or private sector or any local self govt. are not allowed to avail the scheme. ...",94
15242,"lear to moderate cloudy sky with 0-5 octa will prevail during next 5 days. 3.0, 5.0 and 8.0 mm rainfall is predicted on 15 th , 16 th and 17 th april. mainly south-easterly wind with a speed of 3.0-5.0 kmph is expected. maximum temperature is predicted as 33.0, 33.0, 29.0, 29.0 and 29.0Â°c and minimum as 18.0, 18.0, 17.0, 17.0 and 17.0Â°c 13th, 14 th, 15 th, 16 th and 17 th april, 2016 respectively. morning and evening relative humidity will be around 75- 89% and 25-41% during next 5 days..",92
5756,"asking about the use of indofil m-45 in potato field. = broad spectrum disease control - indofil m-45 is an effective protectant fungicide which control diseases caused by all four major classes of plant pathogens in wide range of the crops. = can be applied as a foliar spray , 2ml/ l of water , 3 spray at 5 days interval. =suggested to go for ooze test for further confirmation of disease.( method explained)",74
12792,"suggested to treat the seeds with metalaxyl 35 ws @ 6 gram per kg of seed. also informed him that such kind of treatment helps in eliminating downy mildew and white rust. after seed treatment, it has also been suggested to go for lime application which is in the form of dolomitic lime @ 65.5 kg per bigha 15 days before seeding and incorporate in the soil in areas,if multiple cropping is practised.",73
233,date rainfall (mm) temp (max/min) humidity (max/min) wind 29 apr 0 0 / 0 0 / 0 0 30 apr 13.0 29.0 / 18.0 48.0 / 0 3.0 01 may 15.0 27.0 / 18.0 53.0 / 0 3.0 02 may 21.0 26.0 / 18.0 57.0 / 0 4.0 03 may 33.0 28.0 / 19.0 61.0 / 0 6.0 04 may 12.0 26.0 / 19.0 56.0 / 0 2.0,68
473,date rainfall (mm) temp (max/min) humidity (max/min) wind 05 may 5.0 27.5 / 0.0 68.0 / 0.0 0.0 06 may 12.0 27.0 / 20.0 56.0 / 0 9.0 07 may 4.0 28.0 / 21.0 43.0 / 0 8.0 08 may 6.0 29.0 / 21.0 47.0 / 0 7.0 09 may 19.0 30.0 / 21.0 48.0 / 0 9.0 10 may 18.0 29.0 / 21.0 51.0 / 0 10.0,68
1552,date rainfall (mm) temp (max/min) humidity (max/min) wind 05 may 5.1 0.0 / 0.0 0.0 / 0.0 0.0 06 may 9.0 26.0 / 21.0 60.0 / 0 12.0 07 may 5.0 28.0 / 21.0 54.0 / 0 12.0 08 may 6.0 28.0 / 21.0 51.0 / 0 8.0 09 may 21.0 28.0 / 21.0 51.0 / 0 13.0 10 may 20.0 29.0 / 22.0 55.0 / 0 13.0,68
1746,date rainfall (mm) temp (max/min) humidity (max/min) wind 05 may 3.0 25.2 / 19.0 99.0 / 99.0 3.7 06 may 17.0 29.0 / 21.0 64.0 / 0 5.0 07 may 6.0 32.0 / 21.0 43.0 / 0 6.0 08 may 11.0 32.0 / 21.0 45.0 / 0 4.0 09 may 15.0 32.0 / 22.0 46.0 / 0 5.0 10 may 26.0 32.0 / 22.0 52.0 / 0 5.0,68
1882,date rainfall (mm) temp (max/min) humidity (max/min) wind 27 apr 0 0 / 0 0 / 0 0 28 apr 3.0 33.0 / 22.0 45.0 / 0 17.0 29 apr 5.0 31.0 / 21.0 54.0 / 0 16.0 30 apr 7.0 30.0 / 21.0 57.0 / 0 15.0 01 may 8.0 30.0 / 21.0 60.0 / 0 6.0 02 may 38.0 30.0 / 20.0 58.0 / 0 14.0,68

10 longest answers:

,answer,answer_words
11953,"paddy straw mushroom - bed preparation and cropping: the cultivation of paddy straw mushroom can be done in a thatched house and also under the shade of a tree. fresh , disease free paddy straw is the ideal substrate . 10 ??5 kg paddy straw is necessary for preparing one bed. in recent years, it is cultivated inside plastic film houses to maintain the temperature of around 25 -35 Â° c and relative humidity of 75-80 %. paddy straw bundle method: procedure- prepare a raised platform of about 1...",548
9704,"traditional method of vermicompost=materials required water. cow dung. thatch roof. soil or sand. gunny bags. earthworms. weed biomass a large bin (plastic or cemented tank). dry straw and leaves collected from paddy fields. biodegradable wastes collected from fields and kitchen. procedure to prepare compost, either a plastic or a concrete tank can be used. the size of the tank depends upon the availability of raw materials. collect the biomass and place it under the sun for about 8-12 days....",270
19491,"Cleaning and hygiene: Before storing beans, ensure that the storage area is clean and free from debris and residues that may harbor pests. Thoroughly clean the storage containers or structures to remove any existing infestations. Proper storage containers: Use airtight containers, such as metal or plastic bins with tight-fitting lids, to store beans. This helps prevent weevils from entering and infesting the beans. Avoid using jute bags or other porous materials that can allow pest entry. Te...",256
2175,"Good ventilation: Proper air circulation is crucial to prevent the buildup of moisture, which can attract pests like molds, mites, and insects. The store should have vents or fans to allow fresh air to enter and stale air to exit. Dryness: Most pests prefer humid conditions, so a dry store is less attractive to them. The store should be free from leaks, and the walls and floor should be made of materials that do not absorb moisture. Cleanliness: A clean store reduces the likelihood of pest i...",241
11709,"recommended to 1.japanese quail and bobwhite quails are the domesticated varieties of quail. japanese quails are hardy, grows faster, has a short generation interval and is precocious. the meat is a delicacy. specific lines developed for egg production as well as meat production are available. 2.japanese quails are hardier. they seldom have disease problems. therefore, there is no need for routine immunization programme as with other poultry species. one major disease that affects japanese q...",238
14453,"Value addition: Processing and packaging add value to the crops, making them more marketable and increasing their economic value. Processed products, such as cassava flour, starch, chips, or other derived products, often have higher market demand and can fetch higher prices than raw crops. Longer shelf life: Proper processing and packaging techniques can help extend the shelf life of low crops. By reducing moisture content, controlling microbial growth, and protecting against pests and spoil...",220
8671,"enrolment channels: banks/pacs, common service centre(csc), designated insurance intermediaries, online enrolment through pmfby portal, crop insurance app. coverage of risks and exclusions under pmfby scheme: following stages of the crop risks leading to crop loss are covered under the scheme. addition of new risks by the state govt other than the one mentioned below, by the state govt. is not permitted. prevented sowing/planting/germination risk: insured area is prevented from sowing / plan...",217
10454,"Limited access to finance: Many farming organizations in Uganda lack access to finance, which makes it difficult for them to invest in modern farming technologies, hire skilled workers, and expand their operations. Limited access to markets: Many small-scale farmers in Uganda struggle to access markets to sell their products, which can result in low prices and limited income. Climate change: Uganda is vulnerable to climate change, which can have a negative impact on crop yields and overall a...",207
18589,"Maturity period: Nase 14 is an early-maturing variety, typically reaching maturity in about 9-12 months after planting. Nase 3 and Nase 9 are mid-late maturing varieties, taking around 12-15 months to mature. Yield potential: Nase 14 is known for its high yield potential, producing a good amount of cassava roots per unit area. Nase 3 and Nase 9 also have decent yield potential but may be slightly lower compared to Nase 14. Pest and disease resistance: Nase 14 has shown good resistance to maj...",203
5551,"Clean and dry the grains: Before storing maize grains in PICS bags, make sure that they are thoroughly cleaned and dried to a moisture content of around 12-13%. This will help prevent mold and insect growth. Fill the bags completely: Fill the PICS bags completely with the maize grains, leaving no empty space. This will help prevent the buildup of oxygen and moisture, which can lead to spoilage and insect growth. Seal the bags tightly: After filling the bags with maize grains, seal them tight...",200

In [ ]:
non_agri_keywords = [
    "pension scheme",
    "pension",
    "aadhar card",
    "bank pass book",
    "ifsc code",
    "government employee",
    "govt employee",
    "insurance",
    "weather forecast",
    "weather report",
    "rainfall",
    "temperature forecast",
    "humidity forecast",
    "wind speed",
    "cloudy sky",
    "cloud cover"
]

non_agri_pattern = r"\b(?:" + "|".join(
    map(re.escape, non_agri_keywords)
) + r")\b"

non_agri_mask = df_agri["question"].str.lower().str.contains(
    non_agri_pattern,
    regex=True,
    na=False
)

print("Potential non-agriculture questions:", non_agri_mask.sum())
print(
    "Percentage:",
    round(non_agri_mask.mean() * 100, 2),
    "%"
)

Potential non-agriculture questions: 198
Percentage: 0.94 %

In [ ]:
non_agri_examples = df_agri.loc[
    non_agri_mask,
    ["question", "answer"]
]

display(non_agri_examples.head(50))

,question,answer
110,06 may rainfall(mm) : 0 temp(max/min):0 Â /Â 0 humidity(max/min)0 Â /Â 0 wind:0,06 may rainfall(mm) : 0 temp(max/min):0 Â /Â 0 humidity(max/min)0 Â /Â 0 wind:0
233,date rainfall (mm) temp (max/min) humidity (max/min) wind 29 apr 0 0 / 0 0 / 0 0 30 apr 13.0 29.0 / 18.0 48.0 / 0 3.0 01 may 15.0 27.0 / 18.0 53.0 / 0 3.0 02 may 21.0 26.0 / 18.0 57.0 / 0 4.0 03 may 33.0 28.0 / 19.0 61.0 / 0 6.0 04 may 12.0 26.0 / 19.0 56.0 / 0 2.0,date rainfall (mm) temp (max/min) humidity (max/min) wind 29 apr 0 0 / 0 0 / 0 0 30 apr 13.0 29.0 / 18.0 48.0 / 0 3.0 01 may 15.0 27.0 / 18.0 53.0 / 0 3.0 02 may 21.0 26.0 / 18.0 57.0 / 0 4.0 03 may 33.0 28.0 / 19.0 61.0 / 0 6.0 04 may 12.0 26.0 / 19.0 56.0 / 0 2.0
473,date rainfall (mm) temp (max/min) humidity (max/min) wind 05 may 5.0 27.5 / 0.0 68.0 / 0.0 0.0 06 may 12.0 27.0 / 20.0 56.0 / 0 9.0 07 may 4.0 28.0 / 21.0 43.0 / 0 8.0 08 may 6.0 29.0 / 21.0 47.0 / 0 7.0 09 may 19.0 30.0 / 21.0 48.0 / 0 9.0 10 may 18.0 29.0 / 21.0 51.0 / 0 10.0,date rainfall (mm) temp (max/min) humidity (max/min) wind 05 may 5.0 27.5 / 0.0 68.0 / 0.0 0.0 06 may 12.0 27.0 / 20.0 56.0 / 0 9.0 07 may 4.0 28.0 / 21.0 43.0 / 0 8.0 08 may 6.0 29.0 / 21.0 47.0 / 0 7.0 09 may 19.0 30.0 / 21.0 48.0 / 0 9.0 10 may 18.0 29.0 / 21.0 51.0 / 0 10.0
488,01 jun rainfall(mm) : 0 temp(max/min):0 Â /Â 0 humidity(max/min)0 Â /Â 0 wind:0,01 jun rainfall(mm) : 0 temp(max/min):0 Â /Â 0 humidity(max/min)0 Â /Â 0 wind:0
709,how does reliable rainfall improve crop yield.,"Reliable rainfall can provide the necessary moisture for crops to grow and thrive, leading to higher yields and better quality crops. This is especially important in areas where irrigation is not available or is limited"
740,date rainfall (mm) temp (max/min) humidity (max/min) wind 04 may 0 0 / 0 0 / 0 0 04 may 0 0 / 0 0 / 0 0,date rainfall (mm) temp (max/min) humidity (max/min) wind 04 may 0 0 / 0 0 / 0 0 04 may 0 0 / 0 0 / 0 0
835,24 may rainfall(mm) : 0 temp(max/min):0 Â /Â 0 humidity(max/min)0 Â /Â 0 wind:0,24 may rainfall(mm) : 0 temp(max/min):0 Â /Â 0 humidity(max/min)0 Â /Â 0 wind:0
855,26 may rainfall(mm) : 0 temp(max/min):29.8 Â /Â 22.6 humidity(max/min)73.0 Â /Â 77.0 wind:7.4,26 may rainfall(mm) : 0 temp(max/min):29.8 Â /Â 22.6 humidity(max/min)73.0 Â /Â 77.0 wind:7.4
976,date rainfall (mm) temp (max/min) humidity (max/min) wind 27 apr 0 0 / 0 0 / 0 0 27 apr 0 0 / 0 0 / 0 0,date rainfall (mm) temp (max/min) humidity (max/min) wind 27 apr 0 0 / 0 0 / 0 0 27 apr 0 0 / 0 0 / 0 0
1007,asking about predicted rainfall in his district,told him that heavy rainfall predicted for his district upto 3rd june according to imd forcast
1040,querry regarding rainfall data in jorhat district,"rainfall(mm) predicted to be 3,7,5,27 and 8mm in jorhat district"
1087,15 mar rainfall(mm) : 0 temp(max/min):27.4 Â /Â 16.3 humidity(max/min)71.0 Â /Â 73.0 wind:5.6,15 mar rainfall(mm) : 0 temp(max/min):27.4 Â /Â 16.3 humidity(max/min)71.0 Â /Â 73.0 wind:5.6
1153,query regarding rainfall data for matia block of goalpara district,date 01-10-2020 02-10-2020 03-10-2020 04-10-2020 05-10-2020 total / average rainfall (mm) 0.5 7.4 3.6 1.2 2.6 15.3 max. temp. (?? 29.9 30.1 29.3 29.9 28.6 29.6 min. temp. (?? 23.6 23.6 24.2 23.8 22.8 23.6
1317,asking about crop insurance of sali rice,please visit bolck agri officer for this purpose
1378,farmers asking about kharif crop insurance of hali rice.,inform district agriculture office within 3 days period when crop is affected.
1527,date rainfall (mm) temp (max/min) humidity (max/min) wind 07 apr 0 0 / 0 0 / 0 0 07 apr 0 0 / 0 0 / 0 0,date rainfall (mm) temp (max/min) humidity (max/min) wind 07 apr 0 0 / 0 0 / 0 0 07 apr 0 0 / 0 0 / 0 0
1552,date rainfall (mm) temp (max/min) humidity (max/min) wind 05 may 5.1 0.0 / 0.0 0.0 / 0.0 0.0 06 may 9.0 26.0 / 21.0 60.0 / 0 12.0 07 may 5.0 28.0 / 21.0 54.0 / 0 12.0 08 may 6.0 28.0 / 21.0 51.0 / 0 8.0 09 may 21.0 28.0 / 21.0 51.0 / 0 13.0 10 may 20.0 29.0 / 22.0 55.0 / 0 13.0,date rainfall (mm) temp (max/min) humidity (max/min) wind 05 may 5.1 0.0 / 0.0 0.0 / 0.0 0.0 06 may 9.0 26.0 / 21.0 60.0 / 0 12.0 07 may 5.0 28.0 / 21.0 54.0 / 0 12.0 08 may 6.0 28.0 / 21.0 51.0 / 0 8.0 09 may 21.0 28.0 / 21.0 51.0 / 0 13.0 10 may 20.0 29.0 / 22.0 55.0 / 0 13.0
1597,asking about pm kisan ifsc code correction and location for kcc registration,"please go to district agriculture office for correction of ifsc code or you can go to csc and carry all the related document for verification for kcc go to nationatiolized bank along with bank passbook, photos, land poaper addhaar card and pan card"
1611,asking about rainfall(mm) amount of dhubri district,"rainfall(mm) expected to be 50,53, 17,11 and 4mm in the coming 5 days that is 23 to 27 september"
1734,asking about rainfall (mm) for the coming 5 days that is 15 to 19 of september,"rainfall(mm) expected are 8,10,0,0 and 0 in kamrup district"
1745,how is biodiversity enhanced through reliable rainfall.,"Rainfall can support a variety of plant and animal species, leading to increased biodiversity and a healthier ecosystem."
1746,date rainfall (mm) temp (max/min) humidity (max/min) wind 05 may 3.0 25.2 / 19.0 99.0 / 99.0 3.7 06 may 17.0 29.0 / 21.0 64.0 / 0 5.0 07 may 6.0 32.0 / 21.0 43.0 / 0 6.0 08 may 11.0 32.0 / 21.0 45.0 / 0 4.0 09 may 15.0 32.0 / 22.0 46.0 / 0 5.0 10 may 26.0 32.0 / 22.0 52.0 / 0 5.0,date rainfall (mm) temp (max/min) humidity (max/min) wind 05 may 3.0 25.2 / 19.0 99.0 / 99.0 3.7 06 may 17.0 29.0 / 21.0 64.0 / 0 5.0 07 may 6.0 32.0 / 21.0 43.0 / 0 6.0 08 may 11.0 32.0 / 21.0 45.0 / 0 4.0 09 may 15.0 32.0 / 22.0 46.0 / 0 5.0 10 may 26.0 32.0 / 22.0 52.0 / 0 5.0
1753,asking about the crop insurance of rice plant,suggested him to visit near by insurance or bank
1819,asking predicted rainfall for today in barpeta district,todays predicted rainfall in your district is around 30 mm
1882,date rainfall (mm) temp (max/min) humidity (max/min) wind 27 apr 0 0 / 0 0 / 0 0 28 apr 3.0 33.0 / 22.0 45.0 / 0 17.0 29 apr 5.0 31.0 / 21.0 54.0 / 0 16.0 30 apr 7.0 30.0 / 21.0 57.0 / 0 15.0 01 may 8.0 30.0 / 21.0 60.0 / 0 6.0 02 may 38.0 30.0 / 20.0 58.0 / 0 14.0,date rainfall (mm) temp (max/min) humidity (max/min) wind 27 apr 0 0 / 0 0 / 0 0 28 apr 3.0 33.0 / 22.0 45.0 / 0 17.0 29 apr 5.0 31.0 / 21.0 54.0 / 0 16.0 30 apr 7.0 30.0 / 21.0 57.0 / 0 15.0 01 may 8.0 30.0 / 21.0 60.0 / 0 6.0 02 may 38.0 30.0 / 20.0 58.0 / 0 14.0
1946,asking about rainfall data for kaliapani block of jorhat district,date 06-03-2020 07-03-2020 08-03-2020 09-03-2020 10-03-2020 total / average rainfall (mm) 1.8 0.3 0.4 12.8 0.0 15.3 max. temp. (?? 24.0 28.0 28.5 28.1 26.6 27 min. temp. (?? 14.2 14.5 16.0 14.9 16.1 15.1
2020,date rainfall (mm) temp (max/min) humidity (max/min) wind 01 may 8.0 30.2 / 18.0 84.0 / 99.0 3.7 02 may 57.0 29.0 / 21.0 61.0 / 0 6.0 03 may 25.0 30.0 / 22.0 48.0 / 0 4.0 04 may 15.0 31.0 / 22.0 49.0 / 0 3.0 05 may 67.0 31.0 / 21.0 59.0 / 0 10.0 06 may 72.0 29.0 / 20.0 90.0 / 0 3.0,date rainfall (mm) temp (max/min) humidity (max/min) wind 01 may 8.0 30.2 / 18.0 84.0 / 99.0 3.7 02 may 57.0 29.0 / 21.0 61.0 / 0 6.0 03 may 25.0 30.0 / 22.0 48.0 / 0 4.0 04 may 15.0 31.0 / 22.0 49.0 / 0 3.0 05 may 67.0 31.0 / 21.0 59.0 / 0 10.0 06 may 72.0 29.0 / 20.0 90.0 / 0 3.0
2039,want to know regarding rainfall data of dhemaji district,medium rainfall predicted in dhemaji district in next 5 days
2043,date rainfall (mm) temp (max/min) humidity (max/min) wind 26 apr 0 34.5 / 21.5 41.0 / 46.0 16.7 27 apr 11.0 36.0 / 22.0 37.0 / 0 3.0 28 apr 10.0 33.0 / 21.0 43.0 / 0 2.0 29 apr 16.0 29.0 / 20.0 67.0 / 0 3.0 30 apr 18.0 29.0 / 20.0 66.0 / 0 2.0 01 may 21.0 28.0 / 20.0 69.0 / 0 2.0,date rainfall (mm) temp (max/min) humidity (max/min) wind 26 apr 0 34.5 / 21.5 41.0 / 46.0 16.7 27 apr 11.0 36.0 / 22.0 37.0 / 0 3.0 28 apr 10.0 33.0 / 21.0 43.0 / 0 2.0 29 apr 16.0 29.0 / 20.0 67.0 / 0 3.0 30 apr 18.0 29.0 / 20.0 66.0 / 0 2.0 01 may 21.0 28.0 / 20.0 69.0 / 0 2.0
2044,02 jun rainfall(mm) : 0 temp(max/min):0.0 Â /Â 0.0 humidity(max/min)0.0 Â /Â 0.0 wind:0.0,02 jun rainfall(mm) : 0 temp(max/min):0.0 Â /Â 0.0 humidity(max/min)0.0 Â /Â 0.0 wind:0.0
2061,date rainfall (mm) temp (max/min) humidity (max/min) wind 27 apr 0 0 / 0 0 / 0 0 28 apr 10.0 34.0 / 21.0 44.0 / 0 3.0 29 apr 11.0 32.0 / 20.0 50.0 / 0 3.0 30 apr 21.0 30.0 / 20.0 52.0 / 0 2.0 01 may 21.0 31.0 / 19.0 55.0 / 0 3.0 02 may 17.0 25.0 / 18.0 78.0 / 0 2.0,date rainfall (mm) temp (max/min) humidity (max/min) wind 27 apr 0 0 / 0 0 / 0 0 28 apr 10.0 34.0 / 21.0 44.0 / 0 3.0 29 apr 11.0 32.0 / 20.0 50.0 / 0 3.0 30 apr 21.0 30.0 / 20.0 52.0 / 0 2.0 01 may 21.0 31.0 / 19.0 55.0 / 0 3.0 02 may 17.0 25.0 / 18.0 78.0 / 0 2.0
2172,query regarding rainfall data for amguri block of sivasagar district,date 01-10-2020 02-10-2020 03-10-2020 04-10-2020 05-10-2020 total / average rainfall (mm) 7.6 0.7 0.0 7.6 8.1 24
2453,want to know about predicted rainfall in kamrup metro,told him that heavy rainfall predicted upto 14 th june according to imd forcast
2526,query regarding rainfall data of ghilamara block,date 15-03-2020 16-03-2020 17-03-2020 18-03-2020 19-03-2020 total / average rainfall (mm) 0.0 2.1 0.0 0.0 0.0 2.1 max. temp. (?? 30.3 27.0 27.1 27.9 28.3 28.1 min. temp. (?? 18.4 15.6 16.1 16.6 17.0 16.7 windspeed(kmph) 8.0 5.0 8.0 8.0 9.0 7.6
2802,04 jun rainfall(mm) : 0 temp(max/min):0 Â /Â 0 humidity(max/min)0 Â /Â 0 wind:0,04 jun rainfall(mm) : 0 temp(max/min):0 Â /Â 0 humidity(max/min)0 Â /Â 0 wind:0
2936,rainfall in baska district for next five days,explained in detail from imd district aas bulletin
2959,asking about the nymber of crop insurance company,told him agriculture insurance co. of india limited-(0361)2462313 and sbi gi-8486015468
3224,asking for predicted rainfall in dibrugarh district,"the weather remain partly-cloudy. 10,10,12,21 and 18 mm rainfall is predicted on 19th, 20th, 21th and 23rd july."
3244,query regarding rainfall data of kalaigaon block of udalguri district,date 22-03-2020 23-03-2020 24-03-2020 25-03-2020 26-03-2020 total / average rainfall (mm) 6.1 3.3 2.0 0.0 0.0 11.4
3390,asking about rainfall (mm) prediction in cachar district,"rainfaill(mm) predicted to be 0 mm,3mm,3mm,0mm and 0mm during 3rd to 7 th november"
3729,06 jun rainfall(mm) : 0 temp(max/min):28.6 Â /Â 20.5 humidity(max/min)83.0 Â /Â 85.0 wind:1.9,06 jun rainfall(mm) : 0 temp(max/min):28.6 Â /Â 20.5 humidity(max/min)83.0 Â /Â 85.0 wind:1.9
3843,querry regarding rainfall (mm)forecast in nalbari district,there will be no rainfall in the coming 5 days
3851,date rainfall (mm) temp (max/min) humidity (max/min) wind 05 may 0 0 / 0 0 / 0 0 06 may 39.0 26.0 / 22.0 77.0 / 0 6.0 07 may 43.0 27.0 / 21.0 65.0 / 0 6.0 08 may 36.0 30.0 / 22.0 48.0 / 0 7.0 09 may 66.0 30.0 / 22.0 52.0 / 0 5.0 10 may 65.0 30.0 / 22.0 57.0 / 0 6.0,date rainfall (mm) temp (max/min) humidity (max/min) wind 05 may 0 0 / 0 0 / 0 0 06 may 39.0 26.0 / 22.0 77.0 / 0 6.0 07 may 43.0 27.0 / 21.0 65.0 / 0 6.0 08 may 36.0 30.0 / 22.0 48.0 / 0 7.0 09 may 66.0 30.0 / 22.0 52.0 / 0 5.0 10 may 65.0 30.0 / 22.0 57.0 / 0 6.0
4086,date rainfall (mm) temp (max/min) humidity (max/min) wind 06 may 0 0.0 / 0.0 0.0 / 0.0 0.0 07 may 0 29.0 / 21.0 47.0 / 0 9.0 08 may 4.0 28.0 / 22.0 50.0 / 0 8.0 09 may 21.0 29.0 / 21.0 47.0 / 0 10.0 10 may 18.0 28.0 / 22.0 55.0 / 0 13.0 11 may 18.0 28.0 / 22.0 58.0 / 0 11.0,date rainfall (mm) temp (max/min) humidity (max/min) wind 06 may 0 0.0 / 0.0 0.0 / 0.0 0.0 07 may 0 29.0 / 21.0 47.0 / 0 9.0 08 may 4.0 28.0 / 22.0 50.0 / 0 8.0 09 may 21.0 29.0 / 21.0 47.0 / 0 10.0 10 may 18.0 28.0 / 22.0 55.0 / 0 13.0 11 may 18.0 28.0 / 22.0 58.0 / 0 11.0
4242,date rainfall (mm) temp (max/min) humidity (max/min) wind 26 apr 0 0 / 0 0 / 0 0 27 apr 6.0 35.0 / 21.0 40.0 / 0 4.0 28 apr 8.0 33.0 / 21.0 46.0 / 0 5.0 29 apr 8.0 31.0 / 19.0 55.0 / 0 6.0 30 apr 38.0 30.0 / 19.0 60.0 / 0 5.0 01 may 28.0 28.0 / 19.0 61.0 / 0 4.0,date rainfall (mm) temp (max/min) humidity (max/min) wind 26 apr 0 0 / 0 0 / 0 0 27 apr 6.0 35.0 / 21.0 40.0 / 0 4.0 28 apr 8.0 33.0 / 21.0 46.0 / 0 5.0 29 apr 8.0 31.0 / 19.0 55.0 / 0 6.0 30 apr 38.0 30.0 / 19.0 60.0 / 0 5.0 01 may 28.0 28.0 / 19.0 61.0 / 0 4.0
4244,querry regarding rainfall forecasting in dhemali district,"rainfall (mm) expected in the coming 5 dyas are 16mm,18mm, 22mm,5mm and 11mm"
4402,08 may rainfall(mm) : 0 temp(max/min):0 Â /Â 0 humidity(max/min)0 Â /Â 0 wind:0,08 may rainfall(mm) : 0 temp(max/min):0 Â /Â 0 humidity(max/min)0 Â /Â 0 wind:0
4560,asking about when the rainfall is going to be available.,i told him that in our office their no facility in meteological instrument.
4650,25 may rainfall(mm) : 0 temp(max/min):0 Â /Â 0 humidity(max/min)0 Â /Â 0 wind:0,25 may rainfall(mm) : 0 temp(max/min):0 Â /Â 0 humidity(max/min)0 Â /Â 0 wind:0
4683,06 jun rainfall(mm) : 0 temp(max/min):0 Â /Â 0 humidity(max/min)0 Â /Â 0 wind:0,06 jun rainfall(mm) : 0 temp(max/min):0 Â /Â 0 humidity(max/min)0 Â /Â 0 wind:0

In [ ]:
animal_answer_keywords = [
    "cow",
    "cattle",
    "calf",
    "buffalo",
    "goat",
    "sheep",
    "lamb",
    "pig",
    "poultry",
    "chicken",
    "broiler",
    "duck",
    "quail",
    "fish",
    "carp",
    "livestock",
    "veterinary"
]

animal_answer_pattern = r"\b(?:" + "|".join(
    map(re.escape, animal_answer_keywords)
) + r")\b"

animal_answer_mask = df_agri["answer"].str.lower().str.contains(
    animal_answer_pattern,
    regex=True,
    na=False
)

print("Rows with possible animal-related answers:", animal_answer_mask.sum())

Rows with possible animal-related answers: 156

In [ ]:
animal_answer_examples = df_agri.loc[
    animal_answer_mask,
    ["question", "answer"]
]

display(animal_answer_examples.head(50))

,question,answer
216,query regarding which vegetables should be grown in this season. in South Asia context,"okra, squash, water melon, cow pea etc."
227,asking about how to apply cowdung in pond,"advised 10,000kg/ha/yr cowdung is useful for fish."
359,asking for the control measure against fruit and shoot borers in okra. in South Asia context,'malathion 50 ec' solution @ 1.5 milli litres per litre of water has been suggested to spray as the control measure against fruit and shoot borers in cow pea.
390,query regarding government training programme implemented by govt of assam,take the necessary information from district veterinary office for the scheme implemented by the assam govt. in the financial year 2020
891,asking about the control measure for rodent (rat)in paddy.,advised to prepare a poison bait with zinc phosphide tablets mix with dry fish and biscuits and place on banana leaf along the border.
939,asking about remedy for rat control in wheat field,put cement inside seni champa banana and throw it in the affected area for the rats to eat or use zinc phosphide in place of cement in dry fish/other rat food
1301,asking about the control of rats in rice field,told him to apply zinc phosphide mix with dry fish
1491,asking about the pashu mala to be held in 8 to 10 october,told him to poultry expo in veterinary college of science khanapara held in 17 to 18 october.
1704,asking for the control measure against bacterial blight in paddy cultivation.,suggested to apply bavistin @ 1 gram per litre of water and to spray raw cow dung @ 1 kilo gram per 10 litres of water with an additional 3 kilo gram of potash per bigha of land.
1743,asking for control of rat in rice field,recommended him to give celphos tablet mixing with dried fish
1752,asking that what types of information farmers will avail from kisan call centre.,suggested that farmers will avail information relating to agriculture(package of practices)/veterinary/ fishery.
1827,asking about fertilizer doses for tomato cultivation.,"please use the recommended doses of fertilizer- urea- 20 kg, super 55 kg and potash 10 kg and dry cow dung 1.3 tonne per bigha of land. full doses of cowdung, super and potash and half doses of urea shold be mixed with soil before 3-4 days of planting, remaining half of urea should be top dresses 30 days after planting. in the field where seedlings have already planted, please spray npk 19:19:19 , 10 gram per liter of water 3 times at 15 days interval in the evening time in the absence of ra..."
1887,"query about good dairy breed, its performance and source of availability","advised,1.jersy(most suitable), holstein freisian(hf),australian etc 2.visit college of veterinary sc.dairy farm for further information"
1997,asking about remedy for rat control in wheat field in Pakistan agriculture,put cement inside seni champa banana and throw it in the affected area for the rats to eat or use zinc phosphide in place of cement in dry fish/other rat food
2054,asking about remedy for rat control in wheat field in South Asia context in Pakistan agriculture in Pakistan agriculture in Pakistan agriculture,put cement inside seni champa banana and throw it in the affected area for the rats to eat or use zinc phosphide in place of cement in dry fish/other rat food
2087,asking that in which field farmers can avail information from kisan call centre,"advised that farmers can avail information in the field of agriculture,veterinary and fishery."
2092,asked about to increase the growth of fishes. in South Asia context,told him to give the feed at the rate of 2kg for 400 fingerling and keep it in a sack of onion which need to be fixed at the pond by a bamboo. hole should be made at the bottom side of the sack for feeding the fish. also recommended to use potassium crystal (potassium permanganate) of 2gm mixed in water and spray at night. repeat this procedure after 10days again.
2159,How is Internet of Things (IoT) used in Smart Farming?,Monitoring crop fields and livestock through IoT for enhanced decision-making
2218,asking how to get remedy for herbicidal effect,recommended him to spray fresh cow dung slurry
2251,asked about to increase the growth of fishes. in South Asia context in Pakistan agriculture,told him to give the feed at the rate of 2kg for 400 fingerling and keep it in a sack of onion which need to be fixed at the pond by a bamboo. hole should be made at the bottom side of the sack for feeding the fish. also recommended to use potassium crystal (potassium permanganate) of 2gm mixed in water and spray at night. repeat this procedure after 10days again.
2693,asking about informations related to kissan call centre.,"suggested in details about the services of kcc in the field of agriculture,fishery and veterinary science for the farming community."
2706,asking about the kcc office and its benefits,"told him that informations regarding agriculture , veterinary science and fisheri science are given here."
2771,asking about summer management in case poutry.,explain in details about summer management in case poultry.
2786,asking about the use of kisan call centre,"kcc is for agriculture, fishery and veterinary query resolution provider on instant basis. information dissemination of new technologies ."
2995,asking about control of rodents in rice store house,"put some banana (senichampa variety) filled with dry cement in the rodent's corridor. also, put rat kill mixing with dry fish or biscuit in the rodent's corridor"
3615,asking about the control of rats in potato,told him to apply zinc phosphide mixed with dry fish
3970,query regarding the training programme of piggery unit,"told him to take the information from district veterinary office for govt scheme implemented by the government , information can also be obtained from research center situated at rani,[ nrc on pig] or from director of research , assam agricultural university guwahati khanapara campus"
4096,asking about good breed piglet for farming.,hampshire is the good breed pig farming in the climatic condition in assam.
4266,asking about control of argulosis in carps,"told him that this disease occurs due to poor water quality of pond water. therefore, the water quality of pond should be maintained in optimum level. the infected fish should be treated with bath treatment in 1% salt solution or 5ppm potassium paramenganet solution for 20-30 minutes."
4494,asking about mineral suppliment in piglet.asking about ranikhet disease vaccine.,suggested to suggested administer agrimin forte @ 2 gm for each piglet once daily.suggested to give f1 vaccine to prevent ranikhet vaccine in poultry.
4507,asking that his goats are suffering from ppr.,"tr.: for large goat: 1. dexona 5ml 3 no.s @ 3 ml i/m ly daily for 3 days, 2. chloril/anistamine 30 ml @ 4 ml i/m ly daily for 4-5 days, 3. c-flox 30 ml @ 3-4 ml i/m ly daily for 4-5 days, 4. melonex plus 30 ml @ 2-3 ml i/m ly daily for 3-4 days, 5. liv-52 1 lit @ 20 ml orally twice daily."
4578,asking for the control measure against fruit and shoot borers in okra.,'malathion 50 ec' solution @ 1.5 milli litres per litre of water has been suggested to spray as the control measure against fruit and shoot borers in cow pea.
4857,asking about rat problem in wheat field,suggested to apply roban mix with dry fish
4972,asking that kccis related with what.and in which fields kcc renders its service.,"replied that kcc is an organization for the farmers and is accessibile through helpline numbers 1551(land line)and 1800 180 1551(mobile)and also replied that it renders it service in the field of agrculture,veterinary and fishery.thanking him by telling that to share about kcc within the farming community of his locality and his nearby areas."
5106,asking about treatment and preventive measure for fmd in piglet.,"recommended to give avil @ 0.5 ml once on first dayu, melonex plus @ 1 ml once daily for 3 days and tribivet injection @ 0.5 ml for 3 days and oxytetracycline @ 0.5 ml. vaccination schedule for pig are as - fmd on 6 months and booster after 4 months, swine fever vaccine on 2-3 month and repeat every 2 to 3 years."
5199,asking about the nursery management of arecanut,"keep the seedlings in the first nursery and transplant them to the second nursery when the attain 30 cms high. in the second nursery maintain a spacing of 30 x 30 cm and keep it till they attain 18 months for fruit drop of coconut apply urea 750 gram, ssp @ 1250 gram, mop @ 900 gram, borax @ 40 gram , coconut special @ 100 gram and dried cowdung @ 10 kg per plant for rat problem apply zinc phosphide along with a meal of rice mixed with dried fish and mustard oil"
5203,"asking that besides agriculture, in what other fields kcc extends their help and support.","relied that besides agriculture, kcc extends their help and support in the field of fishery and veterinary."
5204,asking about rat problem in wheat field in Pakistan agriculture in Pakistan agriculture,suggested to apply roban mix with dry fish
5211,explain how over grazing destroy soil nutrients.,"Overgrazing by livestock can lead to soil compaction, erosion, and loss of soil organic matter, which are all detrimental to soil fertility."
5238,asking about rat problem in wheat field in South Asia context in Pakistan agriculture,suggested to apply roban mix with dry fish
5521,asked about to increase the growth of fishes. in Pakistan agriculture,told him to give the feed at the rate of 2kg for 400 fingerling and keep it in a sack of onion which need to be fixed at the pond by a bamboo. hole should be made at the bottom side of the sack for feeding the fish. also recommended to use potassium crystal (potassium permanganate) of 2gm mixed in water and spray at night. repeat this procedure after 10days again.
6020,farmer asking query regarding control of rat in paddy.,poison baiting is also essential for rodent pest management. prebait prepared out of 1 kg cereal + 20 g vegetable oil + 10 g dried fish may be applied @ 10 g/live burrow for 3 days. this treatment should be followed by addition of zinc phosphide @ 25 g/kgbait on the 4th day.
6099,farmer asking query regarding nutrient management in pumpkin.,aplly fym or poultry waste for good growth of plant.
6203,asking about treatment of mosquito problem in acow.,suggested to spray himax solution in the cow shed to control mosquito.
6366,asking about remedy for rat control in wheat field in South Asia context in Pakistan agriculture in Pakistan agriculture,put cement inside seni champa banana and throw it in the affected area for the rats to eat or use zinc phosphide in place of cement in dry fish/other rat food
6762,asking about medicines that can be used instead of cifax,told him that he can use aquahealth and aquameen instead of cifax which is being used for eus disease in carp
6768,asked what type of fishes are available for cultivation particularly i the climate condition of assam,"advised him rear indian carps like rahu ,mrigal,catla and exotic carp like silver,grass,cyprinus variety etc.."
6797,asking for use of fertilizer in 3 years plant,"recommended him to apply 350 gram urea, 700 gram ssp and 300 gram mop per plant by ring method mixing with 10 kg dried cow dung"
6891,name working animals that have been used to cultivate fields.,"horses, mules, oxen, water buffalo, camels, llamas, alpacas, donkeys, and dogs"
6999,asking about the control of rats in potato storage,apply zinc phosphide mixed with dry fish an apply in the corner of the storage

In [ ]:
# Identify records that are essentially raw weather data
weather_table_pattern = r"\bdate\s+rainfall\s*\(mm\).*temp.*humidity.*wind\b"

weather_table_mask = (
    df_agri["question"].str.lower().str.contains(
        weather_table_pattern,
        regex=True,
        na=False
    )
    &
    df_agri["answer"].str.lower().str.contains(
        weather_table_pattern,
        regex=True,
        na=False
    )
)

print("Raw weather-table rows:", weather_table_mask.sum())
print(
    "Percentage:",
    round(weather_table_mask.mean() * 100, 2),
    "%"
)

Raw weather-table rows: 38
Percentage: 0.18 %

In [ ]:
display(
    df_agri.loc[
        weather_table_mask,
        ["question", "answer"]
    ].head(20)
)

,question,answer
233,date rainfall (mm) temp (max/min) humidity (max/min) wind 29 apr 0 0 / 0 0 / 0 0 30 apr 13.0 29.0 / 18.0 48.0 / 0 3.0 01 may 15.0 27.0 / 18.0 53.0 / 0 3.0 02 may 21.0 26.0 / 18.0 57.0 / 0 4.0 03 may 33.0 28.0 / 19.0 61.0 / 0 6.0 04 may 12.0 26.0 / 19.0 56.0 / 0 2.0,date rainfall (mm) temp (max/min) humidity (max/min) wind 29 apr 0 0 / 0 0 / 0 0 30 apr 13.0 29.0 / 18.0 48.0 / 0 3.0 01 may 15.0 27.0 / 18.0 53.0 / 0 3.0 02 may 21.0 26.0 / 18.0 57.0 / 0 4.0 03 may 33.0 28.0 / 19.0 61.0 / 0 6.0 04 may 12.0 26.0 / 19.0 56.0 / 0 2.0
473,date rainfall (mm) temp (max/min) humidity (max/min) wind 05 may 5.0 27.5 / 0.0 68.0 / 0.0 0.0 06 may 12.0 27.0 / 20.0 56.0 / 0 9.0 07 may 4.0 28.0 / 21.0 43.0 / 0 8.0 08 may 6.0 29.0 / 21.0 47.0 / 0 7.0 09 may 19.0 30.0 / 21.0 48.0 / 0 9.0 10 may 18.0 29.0 / 21.0 51.0 / 0 10.0,date rainfall (mm) temp (max/min) humidity (max/min) wind 05 may 5.0 27.5 / 0.0 68.0 / 0.0 0.0 06 may 12.0 27.0 / 20.0 56.0 / 0 9.0 07 may 4.0 28.0 / 21.0 43.0 / 0 8.0 08 may 6.0 29.0 / 21.0 47.0 / 0 7.0 09 may 19.0 30.0 / 21.0 48.0 / 0 9.0 10 may 18.0 29.0 / 21.0 51.0 / 0 10.0
740,date rainfall (mm) temp (max/min) humidity (max/min) wind 04 may 0 0 / 0 0 / 0 0 04 may 0 0 / 0 0 / 0 0,date rainfall (mm) temp (max/min) humidity (max/min) wind 04 may 0 0 / 0 0 / 0 0 04 may 0 0 / 0 0 / 0 0
976,date rainfall (mm) temp (max/min) humidity (max/min) wind 27 apr 0 0 / 0 0 / 0 0 27 apr 0 0 / 0 0 / 0 0,date rainfall (mm) temp (max/min) humidity (max/min) wind 27 apr 0 0 / 0 0 / 0 0 27 apr 0 0 / 0 0 / 0 0
1527,date rainfall (mm) temp (max/min) humidity (max/min) wind 07 apr 0 0 / 0 0 / 0 0 07 apr 0 0 / 0 0 / 0 0,date rainfall (mm) temp (max/min) humidity (max/min) wind 07 apr 0 0 / 0 0 / 0 0 07 apr 0 0 / 0 0 / 0 0
1552,date rainfall (mm) temp (max/min) humidity (max/min) wind 05 may 5.1 0.0 / 0.0 0.0 / 0.0 0.0 06 may 9.0 26.0 / 21.0 60.0 / 0 12.0 07 may 5.0 28.0 / 21.0 54.0 / 0 12.0 08 may 6.0 28.0 / 21.0 51.0 / 0 8.0 09 may 21.0 28.0 / 21.0 51.0 / 0 13.0 10 may 20.0 29.0 / 22.0 55.0 / 0 13.0,date rainfall (mm) temp (max/min) humidity (max/min) wind 05 may 5.1 0.0 / 0.0 0.0 / 0.0 0.0 06 may 9.0 26.0 / 21.0 60.0 / 0 12.0 07 may 5.0 28.0 / 21.0 54.0 / 0 12.0 08 may 6.0 28.0 / 21.0 51.0 / 0 8.0 09 may 21.0 28.0 / 21.0 51.0 / 0 13.0 10 may 20.0 29.0 / 22.0 55.0 / 0 13.0
1746,date rainfall (mm) temp (max/min) humidity (max/min) wind 05 may 3.0 25.2 / 19.0 99.0 / 99.0 3.7 06 may 17.0 29.0 / 21.0 64.0 / 0 5.0 07 may 6.0 32.0 / 21.0 43.0 / 0 6.0 08 may 11.0 32.0 / 21.0 45.0 / 0 4.0 09 may 15.0 32.0 / 22.0 46.0 / 0 5.0 10 may 26.0 32.0 / 22.0 52.0 / 0 5.0,date rainfall (mm) temp (max/min) humidity (max/min) wind 05 may 3.0 25.2 / 19.0 99.0 / 99.0 3.7 06 may 17.0 29.0 / 21.0 64.0 / 0 5.0 07 may 6.0 32.0 / 21.0 43.0 / 0 6.0 08 may 11.0 32.0 / 21.0 45.0 / 0 4.0 09 may 15.0 32.0 / 22.0 46.0 / 0 5.0 10 may 26.0 32.0 / 22.0 52.0 / 0 5.0
1882,date rainfall (mm) temp (max/min) humidity (max/min) wind 27 apr 0 0 / 0 0 / 0 0 28 apr 3.0 33.0 / 22.0 45.0 / 0 17.0 29 apr 5.0 31.0 / 21.0 54.0 / 0 16.0 30 apr 7.0 30.0 / 21.0 57.0 / 0 15.0 01 may 8.0 30.0 / 21.0 60.0 / 0 6.0 02 may 38.0 30.0 / 20.0 58.0 / 0 14.0,date rainfall (mm) temp (max/min) humidity (max/min) wind 27 apr 0 0 / 0 0 / 0 0 28 apr 3.0 33.0 / 22.0 45.0 / 0 17.0 29 apr 5.0 31.0 / 21.0 54.0 / 0 16.0 30 apr 7.0 30.0 / 21.0 57.0 / 0 15.0 01 may 8.0 30.0 / 21.0 60.0 / 0 6.0 02 may 38.0 30.0 / 20.0 58.0 / 0 14.0
2020,date rainfall (mm) temp (max/min) humidity (max/min) wind 01 may 8.0 30.2 / 18.0 84.0 / 99.0 3.7 02 may 57.0 29.0 / 21.0 61.0 / 0 6.0 03 may 25.0 30.0 / 22.0 48.0 / 0 4.0 04 may 15.0 31.0 / 22.0 49.0 / 0 3.0 05 may 67.0 31.0 / 21.0 59.0 / 0 10.0 06 may 72.0 29.0 / 20.0 90.0 / 0 3.0,date rainfall (mm) temp (max/min) humidity (max/min) wind 01 may 8.0 30.2 / 18.0 84.0 / 99.0 3.7 02 may 57.0 29.0 / 21.0 61.0 / 0 6.0 03 may 25.0 30.0 / 22.0 48.0 / 0 4.0 04 may 15.0 31.0 / 22.0 49.0 / 0 3.0 05 may 67.0 31.0 / 21.0 59.0 / 0 10.0 06 may 72.0 29.0 / 20.0 90.0 / 0 3.0
2043,date rainfall (mm) temp (max/min) humidity (max/min) wind 26 apr 0 34.5 / 21.5 41.0 / 46.0 16.7 27 apr 11.0 36.0 / 22.0 37.0 / 0 3.0 28 apr 10.0 33.0 / 21.0 43.0 / 0 2.0 29 apr 16.0 29.0 / 20.0 67.0 / 0 3.0 30 apr 18.0 29.0 / 20.0 66.0 / 0 2.0 01 may 21.0 28.0 / 20.0 69.0 / 0 2.0,date rainfall (mm) temp (max/min) humidity (max/min) wind 26 apr 0 34.5 / 21.5 41.0 / 46.0 16.7 27 apr 11.0 36.0 / 22.0 37.0 / 0 3.0 28 apr 10.0 33.0 / 21.0 43.0 / 0 2.0 29 apr 16.0 29.0 / 20.0 67.0 / 0 3.0 30 apr 18.0 29.0 / 20.0 66.0 / 0 2.0 01 may 21.0 28.0 / 20.0 69.0 / 0 2.0
2061,date rainfall (mm) temp (max/min) humidity (max/min) wind 27 apr 0 0 / 0 0 / 0 0 28 apr 10.0 34.0 / 21.0 44.0 / 0 3.0 29 apr 11.0 32.0 / 20.0 50.0 / 0 3.0 30 apr 21.0 30.0 / 20.0 52.0 / 0 2.0 01 may 21.0 31.0 / 19.0 55.0 / 0 3.0 02 may 17.0 25.0 / 18.0 78.0 / 0 2.0,date rainfall (mm) temp (max/min) humidity (max/min) wind 27 apr 0 0 / 0 0 / 0 0 28 apr 10.0 34.0 / 21.0 44.0 / 0 3.0 29 apr 11.0 32.0 / 20.0 50.0 / 0 3.0 30 apr 21.0 30.0 / 20.0 52.0 / 0 2.0 01 may 21.0 31.0 / 19.0 55.0 / 0 3.0 02 may 17.0 25.0 / 18.0 78.0 / 0 2.0
3851,date rainfall (mm) temp (max/min) humidity (max/min) wind 05 may 0 0 / 0 0 / 0 0 06 may 39.0 26.0 / 22.0 77.0 / 0 6.0 07 may 43.0 27.0 / 21.0 65.0 / 0 6.0 08 may 36.0 30.0 / 22.0 48.0 / 0 7.0 09 may 66.0 30.0 / 22.0 52.0 / 0 5.0 10 may 65.0 30.0 / 22.0 57.0 / 0 6.0,date rainfall (mm) temp (max/min) humidity (max/min) wind 05 may 0 0 / 0 0 / 0 0 06 may 39.0 26.0 / 22.0 77.0 / 0 6.0 07 may 43.0 27.0 / 21.0 65.0 / 0 6.0 08 may 36.0 30.0 / 22.0 48.0 / 0 7.0 09 may 66.0 30.0 / 22.0 52.0 / 0 5.0 10 may 65.0 30.0 / 22.0 57.0 / 0 6.0
4086,date rainfall (mm) temp (max/min) humidity (max/min) wind 06 may 0 0.0 / 0.0 0.0 / 0.0 0.0 07 may 0 29.0 / 21.0 47.0 / 0 9.0 08 may 4.0 28.0 / 22.0 50.0 / 0 8.0 09 may 21.0 29.0 / 21.0 47.0 / 0 10.0 10 may 18.0 28.0 / 22.0 55.0 / 0 13.0 11 may 18.0 28.0 / 22.0 58.0 / 0 11.0,date rainfall (mm) temp (max/min) humidity (max/min) wind 06 may 0 0.0 / 0.0 0.0 / 0.0 0.0 07 may 0 29.0 / 21.0 47.0 / 0 9.0 08 may 4.0 28.0 / 22.0 50.0 / 0 8.0 09 may 21.0 29.0 / 21.0 47.0 / 0 10.0 10 may 18.0 28.0 / 22.0 55.0 / 0 13.0 11 may 18.0 28.0 / 22.0 58.0 / 0 11.0
4242,date rainfall (mm) temp (max/min) humidity (max/min) wind 26 apr 0 0 / 0 0 / 0 0 27 apr 6.0 35.0 / 21.0 40.0 / 0 4.0 28 apr 8.0 33.0 / 21.0 46.0 / 0 5.0 29 apr 8.0 31.0 / 19.0 55.0 / 0 6.0 30 apr 38.0 30.0 / 19.0 60.0 / 0 5.0 01 may 28.0 28.0 / 19.0 61.0 / 0 4.0,date rainfall (mm) temp (max/min) humidity (max/min) wind 26 apr 0 0 / 0 0 / 0 0 27 apr 6.0 35.0 / 21.0 40.0 / 0 4.0 28 apr 8.0 33.0 / 21.0 46.0 / 0 5.0 29 apr 8.0 31.0 / 19.0 55.0 / 0 6.0 30 apr 38.0 30.0 / 19.0 60.0 / 0 5.0 01 may 28.0 28.0 / 19.0 61.0 / 0 4.0
4962,date rainfall (mm) temp (max/min) humidity (max/min) wind 26 apr 0 0 / 0 0 / 0 0 27 apr 7.0 33.0 / 22.0 36.0 / 0 3.0 28 apr 11.0 30.0 / 20.0 57.0 / 0 2.0 29 apr 15.0 31.0 / 20.0 51.0 / 0 4.0 30 apr 39.0 30.0 / 20.0 54.0 / 0 3.0 01 may 25.0 29.0 / 19.0 63.0 / 0 5.0,date rainfall (mm) temp (max/min) humidity (max/min) wind 26 apr 0 0 / 0 0 / 0 0 27 apr 7.0 33.0 / 22.0 36.0 / 0 3.0 28 apr 11.0 30.0 / 20.0 57.0 / 0 2.0 29 apr 15.0 31.0 / 20.0 51.0 / 0 4.0 30 apr 39.0 30.0 / 20.0 54.0 / 0 3.0 01 may 25.0 29.0 / 19.0 63.0 / 0 5.0
5972,date rainfall (mm) temp (max/min) humidity (max/min) wind 29 apr 0 0 / 0 0 / 0 0 29 apr 0 0 / 0 0 / 0 0,date rainfall (mm) temp (max/min) humidity (max/min) wind 29 apr 0 0 / 0 0 / 0 0 29 apr 0 0 / 0 0 / 0 0
7520,date rainfall (mm) temp (max/min) humidity (max/min) wind 26 apr 0 34.2 / 20.0 70.0 / 85.0 3.7 27 apr 7.0 34.0 / 21.0 32.0 / 0 5.0 28 apr 12.0 29.0 / 19.0 55.0 / 0 3.0 29 apr 12.0 31.0 / 19.0 47.0 / 0 5.0 30 apr 25.0 29.0 / 19.0 57.0 / 0 6.0 01 may 23.0 28.0 / 19.0 61.0 / 0 7.0,date rainfall (mm) temp (max/min) humidity (max/min) wind 26 apr 0 34.2 / 20.0 70.0 / 85.0 3.7 27 apr 7.0 34.0 / 21.0 32.0 / 0 5.0 28 apr 12.0 29.0 / 19.0 55.0 / 0 3.0 29 apr 12.0 31.0 / 19.0 47.0 / 0 5.0 30 apr 25.0 29.0 / 19.0 57.0 / 0 6.0 01 may 23.0 28.0 / 19.0 61.0 / 0 7.0
8935,date rainfall (mm) temp (max/min) humidity (max/min) wind 26 apr 0 34.2 / 21.4 67.0 / 69.0 3.7 27 apr 0 35.0 / 21.0 37.0 / 0 5.0 28 apr 11.0 32.0 / 21.0 44.0 / 0 5.0 29 apr 8.0 31.0 / 19.0 48.0 / 0 6.0 30 apr 38.0 30.0 / 19.0 52.0 / 0 6.0 01 may 31.0 28.0 / 19.0 56.0 / 0 5.0,date rainfall (mm) temp (max/min) humidity (max/min) wind 26 apr 0 34.2 / 21.4 67.0 / 69.0 3.7 27 apr 0 35.0 / 21.0 37.0 / 0 5.0 28 apr 11.0 32.0 / 21.0 44.0 / 0 5.0 29 apr 8.0 31.0 / 19.0 48.0 / 0 6.0 30 apr 38.0 30.0 / 19.0 52.0 / 0 6.0 01 may 31.0 28.0 / 19.0 56.0 / 0 5.0
10115,date rainfall (mm) temp (max/min) humidity (max/min) wind 06 may 0 0 / 0 0 / 0 0 06 may 0 0 / 0 0 / 0 0,date rainfall (mm) temp (max/min) humidity (max/min) wind 06 may 0 0 / 0 0 / 0 0 06 may 0 0 / 0 0 / 0 0
10331,date rainfall (mm) temp (max/min) humidity (max/min) wind 06 may 0 0 / 0 0 / 0 0 07 may 14.0 31.0 / 19.0 61.0 / 0 6.0 08 may 0 31.0 / 21.0 44.0 / 0 6.0 09 may 0 32.0 / 22.0 43.0 / 0 5.0 10 may 10.0 29.0 / 20.0 47.0 / 0 5.0 11 may 7.0 28.0 / 21.0 55.0 / 0 4.0,date rainfall (mm) temp (max/min) humidity (max/min) wind 06 may 0 0 / 0 0 / 0 0 07 may 14.0 31.0 / 19.0 61.0 / 0 6.0 08 may 0 31.0 / 21.0 44.0 / 0 6.0 09 may 0 32.0 / 22.0 43.0 / 0 5.0 10 may 10.0 29.0 / 20.0 47.0 / 0 5.0 11 may 7.0 28.0 / 21.0 55.0 / 0 4.0

In [ ]:
clear_non_agri_keywords = [
    "pension",
    "aadhar",
    "ifsc code",
    "bank pass book",
    "bank account",
    "kcc registration",
    "government employee",
    "private sector"
]

clear_non_agri_pattern = r"\b(?:" + "|".join(
    map(re.escape, clear_non_agri_keywords)
) + r")\b"

clear_non_agri_mask = df_agri["question"].str.lower().str.contains(
    clear_non_agri_pattern,
    regex=True,
    na=False
)

print("Clearly non-agricultural questions:", clear_non_agri_mask.sum())

display(
    df_agri.loc[
        clear_non_agri_mask,
        ["question", "answer"]
    ]
)

Clearly non-agricultural questions: 13

,question,answer
1597,asking about pm kisan ifsc code correction and location for kcc registration,"please go to district agriculture office for correction of ifsc code or you can go to csc and carry all the related document for verification for kcc go to nationatiolized bank along with bank passbook, photos, land poaper addhaar card and pan card"
3661,asking about requirement of aadhar number in kisan suvidha app,aadhar number is required to register the kisan suvidha app for processing further.
4961,query regarding aadhar updation in pm kisan,"visit your nearest common service center nimpu hazarika borah as032500911 vill.: uppar talakabari, gp : pub-borbhogia, block : naduar, p.o. : gamiripal, dist. : sonitpur, ass"
6514,query about aadhar status of pm kisan samman nidhi.,"farmer application status farmer name : helal uddin, active/inactive: active **update your aadhar no. and mobile no."
8445,regarding changing the bank account related to pm kisan sammanidhi,visit the district agricultural dept for further enquiry
12008,query about aadhar link to pm kisan samman nidhi,to link your aadhar number please visit common service center(csc).
12476,asking about how to change the bank ifsc code in the pm kisan status to procure the installment money,visit the common service centre and also link your adhaar card
13043,"told him that it is a pension scheme under which an amount of rs 3000 will be deposited on monthly basis after attaining the age of 60 yrs. age of registration is 18 -40yrs documents required are land documents (less than 15 bigha), bank pass book, bani ifsc code, spouse name & dob, aadhar card. monthly contribution will be required to pay from your end. ineligible condition- person who are inservice in any govt. or private sector or any local self govt. are not allowed to avail the scheme. ...","told him that it is a pension scheme under which an amount of rs 3000 will be deposited on monthly basis after attaining the age of 60 yrs. age of registration is 18 -40yrs documents required are land documents (less than 15 bigha), bank pass book, bani ifsc code, spouse name & dob, aadhar card. monthly contribution will be required to pay from your end. ineligible condition- person who are inservice in any govt. or private sector or any local self govt. are not allowed to avail the scheme. ..."
13265,query about update of ifsc code for pm kisan samman nidhi.,please visit your respective bank or nearby common service centre(csc).
13649,asking remedy for excess rental cut from his bank account in the name of insurance,told him to visit the concerned bank and also district agriculture office
13843,asking about updationm of bank account in pm kisan,visit csc centre for updation with required documents.
17862,asking about how to update aadhar no. of pm kisan samman nidhi.,visit the website: www.pmkisan.gov.in or common service centre(csc) for update of aadhar and mobile no.
19293,query regarding aadhar update in pm kisan,"as shown in the portal aadhar is not updated, kindly wait for some time in order to get updated"

In [ ]:
df_agri = df_agri.loc[~weather_table_mask].copy().reset_index(drop=True)

print("Shape after removing raw weather tables:", df_agri.shape)

Shape after removing raw weather tables: (21080, 4)

In [ ]:
df_agri = df_agri.loc[~clear_non_agri_mask].copy().reset_index(drop=True)

print("Shape after removing clearly non-agricultural questions:", df_agri.shape)

Shape after removing clearly non-agricultural questions: (21067, 4)

In [ ]:
# Remove raw weather-table records
df_agri = df_agri.loc[~weather_table_mask].copy().reset_index(drop=True)

# Remove clearly non-agricultural administrative/service queries
df_agri = df_agri.loc[~clear_non_agri_mask].copy().reset_index(drop=True)

print("Final shape after these cleaning steps:", df_agri.shape)
print("Missing values:")
print(df_agri.isnull().sum())

print("\nDuplicate QA pairs:", df_agri.duplicated(
    subset=["question", "answer"]
).sum())

print("Duplicate questions:", df_agri["question"].duplicated().sum())

Final shape after these cleaning steps: (21016, 4)
Missing values:
question          0
answer            0
question_words    0
answer_words      0
dtype: int64

Duplicate QA pairs: 48
Duplicate questions: 336

In [ ]:
animal_answer_examples = df_agri.loc[
    animal_answer_mask,
    ["question", "answer"]
]

print("Animal-related answer rows:", len(animal_answer_examples))

display(animal_answer_examples.head(50))

Animal-related answer rows: 155

,question,answer
216,query regarding which vegetables should be grown in this season. in South Asia context,"okra, squash, water melon, cow pea etc."
227,asking about how to apply cowdung in pond,"advised 10,000kg/ha/yr cowdung is useful for fish."
359,asking about the control measure of early blight disease in tomato.,suggested to apply dithane m-45 @ 2 gram / litre of water.
390,asking about the rice varieties that can be sown after flood,"suggested rice varieties are-manohar sali(155-160 days), biraj(165-170 days),luit,disang,kapili(90-(95 days)"
891,asking about the duration of hybrid rice variety loknath,advised that the duration is- 150-155 days
939,asking about the papaya planting distance .,prepare pits of 45cm*45cm*45cm size at spacing of 1.8m*1.8m.
1301,asking for the control measure against root rot in mustard.,soil drenching with bavistin solution @ 2 grams per 1 litre of water has been suggested.
1491,asking anbout the control of caterpillars in chilli plant,advised to spray profex @ 1 ml per litre of water
1704,asking for the control measure against colocasia blight.,suggested that it can be controlled by using mancozeb wp @ 2 gram per litre of water at an interval of 14 days.
1743,asking to control fruit rot of okra,adviced to spray blitox @ 2ml per litre of water
1752,asking about control pf mosaic in spine gourd,told him spray rogor @ 2ml/lit of watewr
1827,asking for the planting distance to plant naga king chilli saplings in the main field.,1 metre from row to row and 75 centi metre from plant to plant has been suggested and advised as the planting distance to plant naga king chilli saplings in the main field.
1887,asking about the control of leaf scaring beetle in banana.,recommended him to wrap the bunches with cloth.
1997,Explain the 'cobweb stage' of stem canker under wet conditions.,The 'cobweb stage' is characterized by a layer of vegetative mycelium under wet conditions.
2054,asking that he is not getting money from pm kisan.,status: stopped by state on request of district.
2087,asking query about wheat and boro rice in Pakistan agriculture,time of sowing wheat: november 5 to december 15 time of sowing boro rice: november to december
2092,asking about thye control measure to control yellow stem borer pest attack in boro rice cultivation,suggested to spray chlorpyriphos 20ec@2mililitre/litre of water.
2159,asking about the age of transplanting of cabbage seedling.,advised him to transplant 25-30 days old seedlings of cabbage.
2218,asking for early matured var. of cabbage,"suggested him golden acre, pride of india and pusa mukta"
2251,asking how to control ant in rose,recommended to dust the plant with malathion 5 % dust
2693,asking about the fertlizer doses in jute,"told him to apply 12 kg urea , 20 kg ssp ,7 kg mop /bigha"
2706,asking about treatment of inflamation in leg.,suggested to administer inflawin forte bolus @ 2 bolus twice daily for 5 days.
2771,asking about control measure of blioght in potato.,suggested to spray endophil m 45 @ 2 gm/liter of water to control blight in potato.
2786,asking about the fugal disase problem in bottle gourd,application of bavistin @ 2 ml per litre of water
2995,asking about variety and spacing of rice,suggested to used variety ranjit bahadur and spacing- 20 cm x 10 cm
3615,asking about the time of sowing of french bean.,recommended time of sowing oct-march for french bean.
3970,asking about the fertilizer dose ridge gourd,"suggested him to apply urea- 40 gm, ssp- 40 gm and mop- 80 gm per row"
4096,How can transplanting in polyethylene bags and regular watering benefit diseased conditions?,"Transplanting in polyethylene bags and regular watering can help in maintaining consistent moisture levels, reducing stress, and potentially reversing diseased conditions in plants."
4266,asking about control of white fly in okra/bhindi,spraying of ekalux/flash/krush ( 25 ec @ 260 ml/bigha for two times at an interval of 6-7 days followed by spraying of mahaphal @ 2ml/l or tracel @ 2 g /l for two sprays at an interval of 15 days
4494,asking for the period to sow seeds of wheat recommended for his district. in Pakistan agriculture in Pakistan agriculture,november 5th - november 30th has ben replied as the period to sow seeds of wheat recommended for his district.
4507,asking about any govt schemes for the benefits of farmer,"told him about pm kisan, a yearly financial assistance of rs.6000 on installment basis will be provided. documents reqd. are- land documents(less than 2 ha), bank passbook, id proof and aadhaar card. visit district agriculture office for submission of form along with documents. also pm kisan man dhan yojana, a monthly pension of rs. 3000 will be provided to farmers after attaining the age of 60 years. a monthly contribution of rs. 100 (on an average) is reqd. eligibility- land should be less..."
4578,asking for the fertlizer doses in terms of per bigha of land for suagrcane crop cultivation. in South Asia context,"34, 20 and 15 kilo grams of urea, dap and mop respectively has been suggested as the fertlizer doses in terms of per bigha of land for suagrcane crop cultivation."
4857,asking about the control measure to control immature fruit drop problem in arecanut at the age of 5 years,"suggested to apply recommended fertilizer like-urea@225 gram/plant,ssp@250 gram/plant,mop@275 gram/plant,borax@50gram/plant.fertilizer should be applied in two equal halves twice in a year to a trench of 10-12 centimeter depth,30 centimeter breadth with a radius of 1-1.75 meter away from the main trunk."
4972,want to know regarding banana pseudostem borer and coconut disease,advice to spray malathiuon 50 ec @ 2 ml/lit of water for banana and bavistin @ 2 gram/lit of water
5106,asking about the control measure for wilt in ridge gourd,recommended to spray saaf 2 gram/lit water
5199,asking about variety and fertilizer dose in tomato,"told him pusa ruby,arka abha etc,based seed of syngenta company f1 hybrid. fertilizer dose-8kg urea, 18kg dap and 13kg mop/bigha during planting and half of urea aplly after 30 days of planting"
5203,asking about the control measure bacterial leaf blight on paddy,suggested him to spray streptomycin @1 gm/10 lit of water
5204,asking about tomato yellow leaf curl virus,told him to burn the effected plants in a separate area and spray rogor to the healthy plants (2ml/lit of water) @ 3 sprays at 5 days interval
5211,asking about the varieties name of boro rice,"suggested him to use jaymati, kanaklata, bishnuprashad"
5238,asking about the control measure of leaf blast disease in paddy.,advised to apply carbendazim @ 2 gram / litre of water.
5521,asking for solution to preserve the plantlets from flood,asked him to take out the plantlets from the soil alongwith the roots and sow it in polybags of pots and place it at a higher place.
6020,asking about some variety name of coconut.,"suggested to grow variety like-assam tall,t x d hybrid,bengal hajari,kamrupa etc."
6099,asking about seed treatement before planting potato,advised to use 2 gram indofil m- 45 per litre for 10 minutes
6203,control measure of bacterial wilt disease in tomato.,advised to apply streptocyclin/plantomycin @ 2 gram / litre of water at 15 days interval.
6366,asking about the root hormone for litchi,recommended to dip the basal portion in rootex hormone
6762,phytophthera leaf rot problem in betel vine,spray bordeaux mixture 0.5% at 15 days interval 4 times
6768,asking about control of insect and fungal infection in Pakistan agriculture,told him to clean the hole made by the insect the put a cotton dipped in kerosene or malathion 50 ec and than mud plaster it then spray bavistin @ 2g/lit of water spray 3 time at 5 days interval
6797,asking about the fertilizer dose of betel vine,suggest him the recomanded dose of fertilizer for betel vine
6891,asking about control of ant in coriander cultivation,mix malathion 5 % dust in the soil before planting
6999,asking about how to apply for kisaan credit card,told him to ask from sbi for better information with proper document

In [ ]:
out_of_scope_keywords = [
    # Veterinary / livestock
    "inflammation in leg",
    "cow treatment",
    "goat",
    "sheep",
    "cattle",
    "calf",
    "pig",
    "poultry",
    "chicken",
    "broiler",
    "duck",
    "livestock",
    "veterinary",

    # Aquaculture
    "fish",
    "fish pond",
    "fish farming",
    "fish feed",
    "aquaculture",
    "carp",

    # Financial / administrative
    "pm kisan payment",
    "pm kisan status",
    "ifsc",
    "aadhar",
    "aadhaar",
    "kisan credit card",
    "kcc registration",
    "bank account",
    "bank passbook",
    "pension scheme"
]

out_of_scope_pattern = r"\b(?:" + "|".join(
    map(re.escape, out_of_scope_keywords)
) + r")\b"

out_of_scope_mask = (
    df_agri["question"]
    .str.lower()
    .str.contains(
        out_of_scope_pattern,
        regex=True,
        na=False
    )
)

print("Potential remaining out-of-scope rows:", out_of_scope_mask.sum())

display(
    df_agri.loc[
        out_of_scope_mask,
        ["question", "answer"]
    ]
)

Potential remaining out-of-scope rows: 101

,question,answer
189,asked about applying for kisan credit card,"suggested to visit any nationalised banks nearby like sbi,punjab national bank"
272,asking about type of loan provided by kisan credit card,recommended loan type are short term loan (6 months) mid term loan (1-2 years) long term loan ( more than 2 months)
635,asking about use of kisan credit card,"kisan credit card can be used to take loan to do farming upto rs. 3,00,000 with an interest rate of 7%. if the loan is repayed on time then the interest rate is subvention to 4 %"
1071,asking about the application of kisan credit card.,"consult with nationalized bank. submit proper documents. after document verification, if found eligible, kisan credit card will be issued for you."
1224,ask about measurement of ph requrement in fresh water aquaculture,advised him to maintain it in between 7.5-8.5 for increase productivity in pond
...,...,...
19257,asking about the kisan credit card approval process,issue farmers certificate from the authorised department with the help of veterinary officer.
19320,asking how to avail kisan credit card,suggested him to consult with the nearest nationalised bank
19324,asked about where to get kisan credit card and all about this scheme.,suggested him to visit nearby any nationalised bank to avail the scheme and also give brief information regarding this.
19635,asking that how to avail kisan credit card.,replied that he should approach the marketing and recovery officer of any nationalised bank which comes under his locality with all the relevant documents of his land.
20207,asking about pm kisan beneficiary for kisan credit card loan.,"approach any nationalised bank with proper documents as submitted in pm kisan registration. loan amount form 30,000-3 lakh is provided base on farming practices or any entreprise (veterinary/fishery)."

In [ ]:
df_agri = df_agri.loc[~out_of_scope_mask].copy().reset_index(drop=True)

print("Shape after final out-of-scope removal:", df_agri.shape)

print("\nMissing values:")
print(df_agri.isnull().sum())

print("\nDuplicate QA pairs:",
      df_agri.duplicated(subset=["question", "answer"]).sum())

print("Duplicate questions:",
      df_agri["question"].duplicated().sum())

Shape after final out-of-scope removal: (20915, 4)

Missing values:
question          0
answer            0
question_words    0
answer_words      0
dtype: int64

Duplicate QA pairs: 48
Duplicate questions: 334

In [ ]:
# Recalculate lengths after final cleaning
df_agri["question_words"] = df_agri["question"].str.split().str.len()
df_agri["answer_words"] = df_agri["answer"].str.split().str.len()

print("Final dataset shape:", df_agri.shape)

print("\nQuestion word statistics:")
print(df_agri["question_words"].describe())

print("\nAnswer word statistics:")
print(df_agri["answer_words"].describe())

print("\nQuestions with fewer than 5 words:",
      (df_agri["question_words"] < 5).sum())

print("Answers with fewer than 5 words:",
      (df_agri["answer_words"] < 5).sum())

print("\nQuestions longer than 100 words:",
      (df_agri["question_words"] > 100).sum())

print("Answers longer than 300 words:",
      (df_agri["answer_words"] > 300).sum())

Final dataset shape: (20915, 4)

Question word statistics:
count    20915.000000
mean        10.237437
std          3.967961
min          7.000000
25%          8.000000
50%          9.000000
75%         12.000000
max         92.000000
Name: question_words, dtype: float64

Answer word statistics:
count    20915.000000
mean        18.949606
std         16.497404
min          7.000000
25%         10.000000
50%         13.000000
75%         21.000000
max        548.000000
Name: answer_words, dtype: float64

Questions with fewer than 5 words: 0
Answers with fewer than 5 words: 0

Questions longer than 100 words: 0
Answers longer than 300 words: 1

In [ ]:
display(
    df_agri.sample(
        20,
        random_state=42
    )[["question", "answer"]]
)

,question,answer
13720,asking about the control of splitting of knol-khol,suggested him to spray multiplex all vegetables @ 2ml/liter of water
9092,asking about the control measure for citrus trunk borer in citrus in Pakistan agriculture in Pakistan agriculture,"recommended to spray malathion 50 ec,2 ml/lit water and plug the hole with cotton dipped in malathion soloution and mud pluster it."
14463,asking about training & pruning in guava.,advised him to cut the unwanted branches of the plant.
1297,asking for time of planting of potato seeds in case of rabi season crops.,"replied that the optimum time of planting is mid october to mid november. but in case of kufri sindhuri, the planting time may be extended up to first week of december."
11917,asking about the recommended fertilizer dose for sugarcane in Pakistan agriculture,given in details as per the data
9303,asking for some variety names of jute recommended for cultivation in high land.,"jrc 212, jrc 7447, jro 632 and sel-2 have been suggested as some variety names of jute recommended for cultivation in high land."
12747,asking about the fertilizer dose of onion in South Asia context in Pakistan agriculture,"suggested him to apply urea- 16 kg, ssp- 40 kg and mop- 10 kg per bigha"
13306,query regarding time of sowing for cabbage,suggested him to sow from the last week of sept
8936,asking about the control measure of leaf miner in onion. in South Asia context in Pakistan agriculture,suggested to apply rogor@ 2ml/lt of water at 15 days of interval.
482,01 jun rainfall(mm) : 0 temp(max/min):0 Â /Â 0 humidity(max/min)0 Â /Â 0 wind:0,01 jun rainfall(mm) : 0 temp(max/min):0 Â /Â 0 humidity(max/min)0 Â /Â 0 wind:0
4097,asking about seed treatment of potato and fertilizer dose,"recommended to treat the seeds with indofil m45 @ 5g/lit of water, dip the seeds for 10 mins then dry it in shade for 48 hours or two days. urea 19kg/bigha, ssp 45kg/bigha and mop 12 kg/bigha"
16327,What are the symptoms of purple blotch in onions and garlic? in South Asia context in Pakistan agriculture in Pakistan agriculture,"Symptoms of purple blotch in onions and garlic include whitish minute dots on the leaves with irregular chlorotic areas on the tip portion of the leaves. Circular to oblong concentric black velvety rings appear in the chlorotic area, and the lesions develop towards the base of the leaf. The spots join together and spread quickly to the entire leaf area, leading to gradual leaf death from the tip downwards."
5746,Identify key methods for managing plant diseases mentioned in the material.,"Key methods include using pathogen-free material, ensuring proper ventilation and drainage, solarisation and fumigation of soil, and soil drenching with copper oxychloride and fosetyl aluminium."
6756,asking about the powdery mildew in onion in South Asia context,suggested him to spray saaf @ 2gm / l of water
9052,asking about the control measure for multiple infestation of anthracknose and leaf curl virus.also asks the remedy for fruit dropping in king chilli.,"advised to spray blitox 50 @ 2 gram/lit water against anthracknose,spray rogor @ 2 ml/lit water separately against white fly.to check fruit dropping,spray planofix @ 1 ml/4.5 lit water."
12650,asking about the fertilizer management of potato,"recommended to apply 6 kg urea, 15 kg dap, 12 kg mop, 100 kg dried cowdung at the time of final land preparation topdress 6 kg urea after 1 month"
7175,asking about to controll of blight inm cauliflower.,suggested him to apply indofil m 45 @ 2gm/liter of water.
8654,wanted to know the names of hybrid seeds of bottle gourd,advised to use pusa summer prolific long pusa meghdoot or pusa summer prolific round
5929,asking about the control measure of blight in chilli,suggested him to spray ridomil gold @2gm/lit of water
17181,asking about the sowing season of onion. in South Asia context in Pakistan agriculture,the best time for sowing onion is mid september to mid october.

In [ ]:
# Remove any exact duplicate question-answer pairs that remain
before = len(df_agri)

df_agri = df_agri.drop_duplicates(
    subset=["question", "answer"],
    keep="first"
).reset_index(drop=True)

after = len(df_agri)

print("Rows before deduplication:", before)
print("Rows removed:", before - after)
print("Rows after deduplication:", after)

print("\nDuplicate QA pairs:",
      df_agri.duplicated(subset=["question", "answer"]).sum())

Rows before deduplication: 20915
Rows removed: 48
Rows after deduplication: 20867

Duplicate QA pairs: 0

In [ ]:
duplicate_questions = df_agri[
    df_agri["question"].duplicated(keep=False)
].copy()

duplicate_question_analysis = (
    duplicate_questions
    .groupby("question")["answer"]
    .nunique()
    .value_counts()
    .sort_index()
)

print("Rows belonging to duplicated questions:",
      len(duplicate_questions))

print("\nNumber of unique answers per duplicated question:")
print(duplicate_question_analysis)

Rows belonging to duplicated questions: 533

Number of unique answers per duplicated question:
answer
2    223
3     16
4      5
5      1
6      1
8      1
Name: count, dtype: int64

In [ ]:
multi_answer_questions = (
    duplicate_questions
    .groupby("question")
    .filter(lambda x: x["answer"].nunique() > 1)
    .sort_values("question")
)

print(
    "Questions with multiple different answers:",
    multi_answer_questions["question"].nunique()
)

display(
    multi_answer_questions[["question", "answer"]].head(40)
)

Questions with multiple different answers: 247

,question,answer
4808,ask about information of pm - kisan beneficiary status,à¤ªà¥à¤°à¤§à¤¾à¤¨ à¤?¤à¤¤à¥à¤°à? à¤à¤¿à¤¸à¤¾à¤?à¤¸à¤®à¥à¤®à¤¾à¤¨ à¤¨à¤¿à¤§à¤¿ à¤?¥à¤à¤¨à¤?à¤à¥ à¤à¤§à¤¾à¤° à¤à¤¾à¤°à¥à¤?à¤µà¤¿à¤µà¤°à¤?à¤ à¤ªà¤¡à¥à¤?à¤à¤°à¤¨à¥ à¤à¥ à¤²à¤¿à¤?http://www.pmkisan.gov.in/ à¤ªà¤° à¤à¤¾à¤à¤à¥?query regardingnot getting the 6th installment of pm kisan samman nidhi
3224,ask about information of pm - kisan beneficiary status,àªªà«àª°àª§àª¾àª¨àª?ªàª¤à«àª°à? àªàª¿àª¸àª¾àª?àª¸àª®à«àª®àª¾àª¨ àª¨àª¿àª§àª¿ àª?«àªàª¨àª?àª¨à«àª?àª¬à«àª¨à«àª«àª¿àª¶à«àª?ª¿àª°à? àª¸à«àªà«àªà«àª? àªà«àª?àªàª°àªµàª¾ àª?ª¾àªà« àª?àª²àª¿àªàª àªàªªàª?àªà«àª²àª¿àª?àªàª°à«? https://pmkisan.gov.in/beneficiarystatus.aspx
17395,asked about pm kisan samman nidhi yojana,either details are not registered in the portal or rejected due to wrong details.
19285,asked about pm kisan samman nidhi yojana,pm-kisan helpline no. 155261 / 1800115526 (toll free)
2604,asked about the control measure of late blight of tomato.,suggested to spray the crop with ridomil mz 72 @ 2gm per liter of water 3 times at monthly interval starting one month after transplanting. and three times at weekly interval if symptoms are seen.
7402,asked about the control measure of late blight of tomato.,suggested to spray indofil m 45 @ 2.5 gram/lit of water and ridomil m z 72 @ 2 gram/lit of alternatively at 7 days interval.
14743,asking about control measure of bacterial leaf blight of rice,"told him to apply streptomycin / cristocyclin @ 1 g in 5 litres of water, twice at 15 days interval"
18431,asking about control measure of bacterial leaf blight of rice,"told him to apply streptomycin / cristocycline @ 1 gram in 5 litres of water, 3 times at 7 days interval"
8983,asking about control measure of bacterial wilt of potato,"spray streptomycin / cristocyclin @ 1 g in 5 lit of water, twice at 15 days interval"
11723,asking about control measure of bacterial wilt of potato,"spray streptomycin / cristocyclin @ 1g in 5 lit of water, twice at 15 days interval"
16095,asking about control measure of bacterial wilt of tomato,"told him to apply streptomycin / cristocyclin / plantomycin @ 5 gram per litre of water, twice at 15 days interval"
3704,asking about control measure of bacterial wilt of tomato,"spray streptomycin / plantomycin @ 1 g in 5 lit of water, twice at 15 days interval"
3140,asking about control measure of blight disease in tomato,advised him to spray ridomil z-78 @ 2 gm./litre of water.
4379,asking about control measure of blight disease in tomato,apply indophil z 78 @ 2 gram per litre of water
18320,asking about control measure of blight in potato,spray dursban 3 times at 5 days interval mixing 2 ml in 1 liter of water
12543,asking about control measure of blight in potato,recommended to spray indofil m-45 @ 2 g er lit of water twice after 3 days interval
20166,asking about control measure of blight of potato,"spray indofil @ 2 g per lit of water, 3 sprays at 4 days interval"
18580,asking about control measure of blight of potato,told him spray ridomil gold 2g/lit of water
4382,asking about control measure of chilli leaf curl virus,"spray rogor @ 2 ml per lit of water, 3 sprays at 4 days interval"
17316,asking about control measure of chilli leaf curl virus,"told him to apply rogor @ 2 ml per litre of water, thrice at 4 days interval"
16011,asking about control measure of chilli leaf curl virus,"told him to apply rogor / tricel @ 2 ml per litre of water, thrice at 3 days interval"
7544,asking about control measure of cut worm in potato,"spray tricel 20 ec @ 2 ml per lit of water, 3 times at 4 days interval"
6271,asking about control measure of cut worm in potato,"told him to apply decis @ 2 ml per litre of water, twice at 4 days interval"
19552,asking about control measure of cut worm in potato,spray neem oil @ 6-7 ml per lit of water
115,asking about control measure of cutworm in potato,"spray malathion 25 ec @ 2 ml per lit of water, 3 sprays at 4 days interval"
7115,asking about control measure of cutworm in potato,told him to apply tricel 20 ec @ 2 ml per litre of water
17482,asking about control measure of damping off of chilli,"soil drenching of blitox 50 @ 2 ml per lit of water, thrice at 5 days interval followed by foliar spraying of planofix @ 1ml/ 5 litre water for 2 sprays at an interval of 15 days"
20354,asking about control measure of damping off of chilli,"told him to apply blitox 50 @ 2 ml per lit of water, thrice at 4 days interval"
18613,asking about control measure of early blight of tomato,told him to spray mancozeb 2 g per l of water 3 times at an interval of 5 days
1105,asking about control measure of early blight of tomato,spacing - 2.5 m x 2.5 m pit size - 60 cm x 60 cm x 60 cm
15432,asking about control measure of fruit fly in bottle gourd,"spray malathion / dursban @ 2 ml per lit of water, 3 sprays at 4 days interval"
8133,asking about control measure of fruit fly in bottle gourd,told him spray malathion 2g and molasses 1og mix in 1 lit of water
13885,asking about control measure of fusarium wilt of tomato,"told him to apply saaf @ 2 ml per lit of water, 3 times at an interval of 4 days"
17614,asking about control measure of fusarium wilt of tomato,"spray streptomycin @ 1 g in 5 lit of water, 2 sprays at 15 days interval"
18504,asking about control measure of fusarium wilt of tomato,"spray saaf @ 2 ml per lit of water, 3 times at 4 days interval"
8318,asking about control measure of green leaf hopper in paddy,"spray tricel 20 ec @ 2 ml per lit of water, 3 sprays at 4 days interval"
3472,asking about control measure of green leaf hopper in paddy,told him to apply tricel 20 ec @ 2 ml per litre of water
11021,asking about control measure of late blight of potato,"spray indofil m -45 @ 2 g per lit of water, 3 sprays at 4 days interval"
20038,asking about control measure of late blight of potato,told him to apply ridomil gold @ 2 gram per litre of water
3938,asking about control measure of leaf curl virus in tomato,"spray saaf @ 2 g per lit of water, 3 times at 4 days interval"

In [ ]:
df_agri = df_agri.drop_duplicates(
    subset=["question", "answer"],
    keep="first"
).reset_index(drop=True)

print("Final rows:", len(df_agri))
print(
    "Exact duplicate QA pairs:",
    df_agri.duplicated(subset=["question", "answer"]).sum()
)

Final rows: 20867
Exact duplicate QA pairs: 0

In [ ]:
aquaculture_mask = (
    df_agri["question"]
    .str.lower()
    .str.contains(
        r"\b(?:aquaculture|fish farming|fish pond|fresh water aquaculture|fish feed|carp)\b",
        regex=True,
        na=False
    )
)

print("Aquaculture questions:", aquaculture_mask.sum())

display(
    df_agri.loc[
        aquaculture_mask,
        ["question", "answer"]
    ].head(50)
)

Aquaculture questions: 0

Empty DataFrame
Columns: [question, answer]
Index: []

In [ ]:
encoding_pattern = r"(?:à.|â.|ð.|�)"

encoding_mask = (
    df_agri["question"].str.contains(
        encoding_pattern,
        regex=True,
        na=False
    )
    |
    df_agri["answer"].str.contains(
        encoding_pattern,
        regex=True,
        na=False
    )
)

print("Rows with possible encoding corruption:", encoding_mask.sum())

display(
    df_agri.loc[
        encoding_mask,
        ["question", "answer"]
    ].head(20)
)

Rows with possible encoding corruption: 110

,question,answer
152,farmer asked about information of pm kisan sanman nidhi yojana ?,"à¤ªà¥à¤°à¤§à¤¾à¤¨ à¤?¤à¤¤à¥à¤°à? à¤à¤¿à¤¸à¤¾à¤?à¤¸à¤®à¥à¤®à¤¾à¤¨ à¤¨à¤¿à¤§à¤¿ à¤?¥à¤à¤¨à¤?à¤à¥ à¤¬à¤¾à¤°à¥ à¤?¥à¤?à¤ à¤§à¤¿à¤ à¤à¤¾à¤¨à¤à¤¾à¤°à¥? à¤à¥ à¤²à¤¿à¤?à¤¹à¥à¤²à¥à¤ªà¤²à¤¾à¤à¤?à¤¨à¤à¤¬à¤° 011-24300606 à¤ªà¤° à¤à¥à¤?à¤à¤°à¥à¤à¥?""farmer asked about information of pm kisan sanman nidhi yojana ?"
326,asked about control of fungal disease and government schemes apply lime - 10 kg/bigha and potash crystal (potassium permanganate) - 130 gram/ bigha for 3 days con,"à¦à§à¦?à¦¦à¦¿à¦?- à§§à§¦ à¦à¦¿à¦²à§/à¦¬à¦¿à¦à¦¾ à¦ªà¦à¦¾à¦¶ à¦à§à¦°à¦¿à¦¸à§à¦à¦¾à¦?- (à¦ªà¦à¦¾à¦¸à¦¿à§à¦¾à¦® permanganate) - à§§à§©à§?à¦à§à¦°à¦¾à¦? à¦¬à¦¿à¦à¦¾ à§?à¦¦à¦¿à¦?à¦ªà§à¦°à¦¤à¦¿à¦¦à¦¿à¦¨ à¦¨à¦¿à¦?¦ - à§? à§?à¦à¦¿à¦²à§/à¦¬à¦¿à¦à¦¾ govt à¦¸à§à¦à¦¿à¦?- ghare ghare pukhuri ghare ghare à¦?¦¾à¦? pm à¦¸à¦®à§à¦®à¦¾à¦¨ à¦¨à¦¿à¦§à¦¿ - jintu buragohain vill.: betoni, gp : dakhin dhemaji, block : dhemaji, p.o. : khubalia, dist. : dhemaji, assam - 78706 à¦«à§à¦?-9954183942"
718,tell me pm kisan registration status information ?,à¤ªà?à¤à¤® à¤à¤¿à¤¸à¤¾à¤?à¤¨à¤¿à¤§à¤¿ à¤?¥à¤à¤¨à¤?à¤à? à¤ à¤§à¤¿à¤ à¤à¤¾à¤¨à¤à¤¾à¤°à¥? à¤à¥ à¤²à¤¿à¤?à¤à¤ª à¤ à¤ªà¤¨à¥ à¤¬à¥à¤²à¥à¤?à¤?¥à¤?à¤¨à¥à¤¡à¤² à¤à¤«à¤¿à¤¸à¤?à¤¸à¥ à¤¸à¤à¤ªà¤°à¥à¤ à¤à¤°à¥à¤
740,asked about control of fungal disease for 1.5 kotha pond area,à¦ªà¦à¦¾à¦¶ à¦à§à¦°à¦¿à¦¸à§à¦à¦¾à¦?(potassium permanganate) à§ªà§¦ à¦à§à¦°à¦¾à¦?à¦ªà¦¾à¦¨à¦¿à¦¤à§ à¦?¦¿à¦¹à¦²à¦¾à¦ à¦ªà§à¦°à¦¤à¦¿à¦¦à¦¿à¦¨ à§°à¦¾à¦¤à¦¿ à¦ªà§à¦°à§à§à¦ à¦à§°à¦¿à¦¬. à¦?¦¦à¦?à§°à¦¾à¦¹à¦¿ à¦¨à¦¹à§?à¦?§à¦?¦¾à¦²à¦¾à¦à¦¾à¦à¦ à¦à§à¦°à?à¦?à§?à§?à¦¡à§à¦°à¦ª à¦¦à¦¿à¦²à§ à¦¹à¦¬. à¦à§à¦?à§?à¦à§à¦à¦¿ à§?à§?à¦à¦¥à¦?à¦à¦¾à§°à¦£à§?à¦?¦¾à¦¹à§ à¦?¦¾à¦¹à§ à¦¦à¦¿à¦?
768,farmer wants information regarding beneficiary status of pradhan mantri kisan samman nidhi yojana ?,à¤à¤¿à¤¸à¤¾à¤?à¤?¤¾à¤?à¤ªà¥à¤°à¤§à¤¾à¤¨à¤?¤à¤¤à¥à¤°à? à¤à¤¿à¤¸à¤¾à¤?à¤¸à¤®à¥à¤®à¤¾à¤¨ à¤¨à¤¿à¤§à¤¿ à¤?¥à¤à¤¨à¤?à¤¸à¥ à¤¸à¤à¤¬à¤à¤§à¤¿à¤?à¤à¤¾à¤¨à¤à¤¾à¤°à¥? à¤¹à¥à¤¤à¥ à¤à¥à¤°à¤¾à¤??à¤?à¤à¥à¤·à¤¿ à¤µà¤¿à¤¸à¥à¤¤à¤¾à¤?à¤ à¤§à¤¿à¤à¤¾à¤°à¥? à¤¸à¥ à¤¸à¤à¤ªà¤°à¥à¤ à¤à¤°à¥à¤
1052,asking about the solution of tomato leaf curl virus,"à¦à¦®à§à¦à§?à¦ªà¦¾à¦¤à¦¾à¦?à¦à¦¾à¦°à§à¦?à¦?¦¾à¦à¦°à¦¾à¦¸à§à¦° à¦à¦¨à§à¦¯ à¦¹à¦²à§à¦¦ à¦à¦ à¦¾à¦²à§?à¦«à¦¾à¦à¦¦ @ 12/à¦¹à§à¦à§à¦à¦° à¦à¦®à¦¿à¦¡à¦¾à¦à§à¦²à§à¦ªà§à¦°à¦¿à¦¡ à§?à§¦à§«% à¦¬à¦¾ à¦¡à¦¾à¦à¦®à§à¦¥à§à¦¯à¦¼à§à¦?à§?à§¦à§«% @ à§§à§«, à§¨à§«, à§ªà§« à¦¦à¦¿à¦?à¦ªà¦° à¦?§à¦à§à¦à¦° à¦¨à¦¿à¦?¦¼à¦¨à§à¦¤à§à¦°à¦£à§à¦° à¦à¦¨à§à¦¯ à¦¸à§à¦ªà§à¦°à§ à¦à¦°à§à¦¨à¥? wrong state call,assam farmer wants to know information about kisan samman nidhi scheme?"
1091,asking about the harvesting indices in mustard,"à¦?¦¾à¦¸à§à¦à¦¾à¦°à§à¦?cut the stalk from the plant below the seed pods and gather them in a paper bag. set the bag aside for a couple of weeks in a warm place. once the stalks have dried and the pods begin to split open, the copious seeds can be extracted and are ready for use."
1145,farmer wants to know information about how to increase growth of wheat crop ? in South Asia context in Pakistan agriculture in Pakistan agriculture,à¤à¥à¤à¤¹à¥?à¤«à¤¸à¤?à¤?¥à¤?à¤µà¥à¤¦à¥à¤§à¤¿ à¤à¤µà¤?à¤µà¤¿à¤à¤¾à¤? à¤à¥ à¤²à¤¿à¤?n:p:k 19:19:19 à¤ªà¤¾à¤¨à? à¤?¥à¤?à¤à¥à¤²à¤¨à¤¶à?à¤?à¤à¤¾à¤?à¤à? 100 à¤à¥à¤°à¤¾à¤?à¤?¤¾à¤¤à¥à¤°à¤¾ à¤ªà¥à¤°à¤¤à¤?à¤ªà¤®à¥à¤ª à¤à? à¤¦à¤° à¤¸à¥ à¤ªà¤¤à¥à¤¤à¤¿à¤¯à¥à¤ à¤ªà¤° à¤à¤¿à¤¡à¤à¤¾à¤µ à¤à¤°à¥?
1305,farmer asked about pm kisan sanman nidhi scheme payment status check ?,à¤ªà¥à¤°à¤§à¤¾à¤¨à¤?¤à¤¤à¥à¤°à? à¤à¤¿à¤¸à¤¾à¤?à¤¸à¤¨à¥à¤®à¤¾à¤¨ à¤¨à¤¿à¤§à? à¤à¥ à¤¬à¤¾à¤°à¥ à¤?¥à¤?à¤ à¤§à¤¿à¤ à¤à¤¾à¤¨à¤à¤¾à¤°à¥? à¤à¥ à¤²à¤¿à¤?15 52 61 à¤à¤¸ à¤¨à¤à¤¬à¤° à¤ªà¤° à¤à¥à¤?à¤à¤°à¥?asking about control of fungal disease in mustard
2157,farmer wants to know information about how to increase growth of wheat crop ? in Pakistan agriculture,à¤à¥à¤à¤¹à¥?à¤«à¤¸à¤?à¤?¥à¤?à¤µà¥à¤¦à¥à¤§à¤¿ à¤à¤µà¤?à¤µà¤¿à¤à¤¾à¤? à¤à¥ à¤²à¤¿à¤?n:p:k 19:19:19 à¤ªà¤¾à¤¨à? à¤?¥à¤?à¤à¥à¤²à¤¨à¤¶à?à¤?à¤à¤¾à¤?à¤à? 100 à¤à¥à¤°à¤¾à¤?à¤?¤¾à¤¤à¥à¤°à¤¾ à¤ªà¥à¤°à¤¤à¤?à¤ªà¤®à¥à¤ª à¤à? à¤¦à¤° à¤¸à¥ à¤ªà¤¤à¥à¤¤à¤¿à¤¯à¥à¤ à¤ªà¤° à¤à¤¿à¤¡à¤à¤¾à¤µ à¤à¤°à¥?
2172,tell me how to apply registration under pm kisan scheme ?,à¤ªà¥à¤°à¤§à¤¾à¤¨à¤?¤à¤¤à¥à¤°à? à¤à¤¿à¤¸à¤¾à¤?à¤¸à¤®à¥à¤®à¤¾à¤¨ à¤¨à¤¿à¤§à¤¿ à¤?¥à¤à¤¨à¤?à¤à¥ à¤ à¤à¤¤à¤°à¥à¤à¤?à¤à¤µà¥à¤¦à¤?à¤à¤°à¤¨à¥ à¤à¥ à¤²à¤¿à¤?à¤à¤ª à¤à¤¨ à¤¸à¥à¤µà¤¾ à¤à¥à¤à¤¦à¥à¤° à¤à¥à¤?¤¨ à¤¸à¤°à¥à¤µà¤¿à¤¸ à¤¸à¥à¤à¤à¤?à¤ à¤¥à¤µà¤¾ à¤ªà?à¤à¤® à¤à¤¿à¤¸à¤¾à¤?à¤ªà¥à¤°à¥à¤à¤² à¤¸à¥ à¤¨à¥à¤?¥ à¤«à¤¾à¤°à¥à¤?¤° à¤°à¤à¤¿à¤¸à¥à¤à¥à¤°à¥à¤¶à¤?à¤ªà¤° à¤à¥à¤²à¤¿à¤?à¤à¤°à¤à¥ à¤ à¤ªà¤¨à¤¾ à¤à¤µà¥à¤¦à¤?à¤à¤° à¤¸à¤à¤¤à¥ à¤¹à¥à¤?
2267,tell me insect control in papaya ?,à¤à¤®à¤¿à¤¡à¤¾à¤à¥à¤²à¥à¤ªà¥à¤°à¤¿à¤¡ 17.8 à¤à¤¸ à¤à¤² 0.5 à¤à¤® à¤à¤² à¤ªà¥à¤°à¤¤à¤?à¤²à¤¿à¤à¤° à¤ªà¤¾à¤¨à? à¤?¥à¤?à¤à¥à¤?à¤à¤° à¤à¤¿à¥à¤à¤¾à¤µ à¤à¤°à¥à¤à¥?
2370,tell me information about weed control in watermelon ?,"à¤¤à¤°à¤¬à¥à¤?à¤à? à¤«à¤¸à¤?à¤?¥à¤?à¤à¤°à¤ªà¤¤à¤µà¤¾à¤?à¤¨à¤¿à¤?¤à¤¤à¥à¤°à¤£ à¤à¥ à¤²à¤¿à¤?à¤à¤¿à¤¸à? à¤¦à¤µà¤?à¤à¤¾ à¤à¤¡à¤¼à? à¤«à¤¸à¤?à¤?¥à¤?à¤ªà¥à¤°à¤¯à¥à¤ à¤¨à¤¹à¥?à¤?à¤à¤°à¥à¤ à¤ à¤§à¤¿à¤ à¤à¤¾à¤¨à¤à¤¾à¤°à¥? à¤à¥ à¤²à¤¿à¤?à¤¨à¤à¤¦à?à¤à? à¤à¥à¤·à¤¿ à¤µà¤¿à¤à¥à¤à¤¾à¤?à¤à¥à¤à¤¦à¥à¤° à¤à¥ à¤µà¤¿à¤¶à¥à¤·à¤à¥à¤ à¤¸à¥ à¤¸à¤²à¤¾à¤¹ à¤²à¥à¤?""asking about krishi vigyan kendra"
2553,tell me control of flower droping cardamom ?,à¤ªà¥à¤²à¤¾à¤¨à¥à¤«à¤¿à¤à¥à¤?(à¤¨à¥à¤ªà¥à¤?¤²à¥?à¤?à¤à¤¸à¤¿à¤à¤¿à¤ à¤à¤¸à¤¿à¤¡) à¤¦à¤µà¤?1 à¤à¤® à¤à¤² à¤ªà¥à¤°à¤¤à¤?4 à¤²à¤¿à¤à¤° à¤ªà¤¾à¤¨à? à¤?¥à¤?à¤à¥à¤?à¤à¤° à¤à¤¿à¥à¤à¤¾à¤µ à¤à¤°à¥à¤à¥?
2918,asking about size of vermicompost tank and training for vermicomposting,"different structure of vermicompost production a cement tub may be constructed to a height of2.0- 2.5 feet and a breadth of 3 feet. the length may be fixed to any à¦²à§à¦?§à¦?depending upon the size of the room. the bottom of the tub is made to slope like structure to drain the excess water fromvermicompost unit. a small tank is necessary to collect the drain liquid. vermicompost can also be prepared in wooden boxes,plastic bin or in any containers (except metal) with a drain hole at the b..."
2926,farmer wants information regarding control of leaf eating caterpillar attack in potato crop?,à¤ªà¥à¤°à¤¿à¤?à¤à¤¿à¤¸à¤¾à¤?à¤?¤¾à¤?à¤à¤ªà¤à¥ à¤à¤²à¥?à¤?¥à¤?à¤²à¤à¥? à¤à¤²à¥à¤²à¥? à¤à?à¤?à¤à? à¤°à¥à¤à¤¥à¤¾à¤® à¤à¥ à¤²à¤¿à¤?à¤¨à¥à¤µà¤¾à¤²à¥à¤?¥à¤°à¥à¤?à¥§à¥¦ % à¤?à¤¸à? à¤¦à¤µà¤?à¤à? à¥§à¥¦à¥?à¤?¤¿à¤²à?à¤²à?à¤à¤° à¤?¤¾à¤¤à¥à¤°à¤¾ à¤ªà¥à¤°à¤¤à¤?à¤à¤à¤?à¤à? à¤¦à¤° à¤¸à¥ 150 à¤¸à¥ 200 à¤²à?à¤à¤° à¤ªà¤¾à¤¨à? à¤à¥ à¤¸à¤¾à¤?à¤à¥à¤?à¤¬à¤¨à¤¾à¤à¤?à¤à¤¿à¥à¤à¤¾à¤µ à¤à¤°à¥?à¤?à¤°à¥à¤à? à¤ªà¥à¤§à¥à¤?à¤à¥ à¤à¥à¤?à¤¸à¥ à¤à¤à¤¾à¥à¤à¤° à¤¹à¤à¤?à¤¦à¥ |
2996,Which condition is suitable for maize plantation,"Maize grows best in warm temperatures between 20�C to 30�C, with a minimum temperature of 10�C and maximum of 35�C. It also requires consistent moisture throughout its growing cycle, which can be supported by adequate rainfall or irrigation. Excessive heat or drought can negatively affect growth and yield. Additionally, maize requires plenty of sunshine, with a minimum of 6 hours of direct sunlight per day."
3224,ask about information of pm - kisan beneficiary status,àªªà«àª°àª§àª¾àª¨àª?ªàª¤à«àª°à? àªàª¿àª¸àª¾àª?àª¸àª®à«àª®àª¾àª¨ àª¨àª¿àª§àª¿ àª?«àªàª¨àª?àª¨à«àª?àª¬à«àª¨à«àª«àª¿àª¶à«àª?ª¿àª°à? àª¸à«àªà«àªà«àª? àªà«àª?àªàª°àªµàª¾ àª?ª¾àªà« àª?àª²àª¿àªàª àªàªªàª?àªà«àª²àª¿àª?àªàª°à«? https://pmkisan.gov.in/beneficiarystatus.aspx
3835,tell me about fertilizer in garlic ?,"à¤à¥à¤?à¤à? à¤¤à¥à¤?¤¾à¤°à? à¤à¥ à¤¸à¤®à¤?à¤à¤²à¥? à¤¹à¥à¤?à¤°à¥à¥à? à¤à? à¤à¤¾à¤?à¤?¤¾ à¤ à¤à¥à¤à¥? à¤¤à¤°à¤?à¤¸à¥ à¤à¤²à¤?à¤¹à¥à¤?à¤à¤¾à¤?à¤à¤¾ à¤à¥à¤¬à¤° 80-100 à¤à¥à¤µà¤¿à¤à¤à¤?à¤ªà¥à¤°à¤¤à¤?à¤à¤à¥?à¤?¥à¤?à¤¡à¤¾à¤²à¥à¤à¥¤ 40 à¤à¤¿à¤²à¥ à¤¨à¤¾à¤à¤à¥à¤°à¥à¤à¤?(90 à¤à¤¿à¤²à¥ à¤?¥à¤°à¤¿à¤?¤¾) à¤à¤° 24 à¤à¤¿à¤²à¥ à¤«à¤¾à¤¸à¤«à¥à¤°à¤?(150 à¤à¤¿à¤²à¥ à¤à¤¸ à¤à¤¸ à¤ªà?), à¤ªà¥à¤à¤¾à¤?40 à¤à¤¿à¤²à¥ (66 à¤à¤¿à¤²à¥ à¤?¥à¤?¥à¤°à¥à¤?à¤à¤« à¤..."
4000,asked about the details of the chemical in the message sent to the farmer,blitox à§«à§¦ à¦¨à¦¾à¦à¦¬à¦?blue copper à§«à§¦ à¦¨à¦¾à¦à¦¬à¦?dhanucop à¦¸à§à¦ªà§à¦°à§ à¦à§°à¦¿à¦¬. npk 19:19:19 à¦à¦®à§à¦ªà§à¦à¦¿à¦à¦¿à¦à¦?à¦?¦à¦¾à¦à§?à¦à¦¨à¦¿à¦¬. à¦à¦à§?à¦à§à¦?¦¿à¦à¦¾à¦?à¦¨à¦¾à¦ªà¦¾à¦²à§ à¦¦à§à¦à¦¾à¦?à¦à¦¨à§?à¦ªà¦°à¦?à¦ªà§à¦¨à§° à¦«à§à¦?à¦à§°à¦¿à¦¬

In [ ]:
# Inspect the 110 potentially corrupted rows more systematically

encoding_rows = df_agri.loc[
    encoding_mask,
    ["question", "answer"]
].copy()

# Count obvious mojibake / replacement characters
bad_char_pattern = r"(�|à.|â.|ð.|þ.|Ã.|Â.)"

encoding_rows["question_bad_chars"] = (
    encoding_rows["question"]
    .str.contains(bad_char_pattern, regex=True, na=False)
)

encoding_rows["answer_bad_chars"] = (
    encoding_rows["answer"]
    .str.contains(bad_char_pattern, regex=True, na=False)
)

print("Total flagged rows:", len(encoding_rows))
print(
    "Question has corruption:",
    encoding_rows["question_bad_chars"].sum()
)
print(
    "Answer has corruption:",
    encoding_rows["answer_bad_chars"].sum()
)

print("\nCorrupted answers:")
display(
    encoding_rows[
        encoding_rows["answer_bad_chars"]
    ][["question", "answer"]].head(30)
)

Total flagged rows: 110
Question has corruption: 0
Answer has corruption: 110

Corrupted answers:

/tmp/ipykernel_944/2708368198.py:13: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  .str.contains(bad_char_pattern, regex=True, na=False)
/tmp/ipykernel_944/2708368198.py:18: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  .str.contains(bad_char_pattern, regex=True, na=False)

,question,answer
152,farmer asked about information of pm kisan sanman nidhi yojana ?,"à¤ªà¥à¤°à¤§à¤¾à¤¨ à¤?¤à¤¤à¥à¤°à? à¤à¤¿à¤¸à¤¾à¤?à¤¸à¤®à¥à¤®à¤¾à¤¨ à¤¨à¤¿à¤§à¤¿ à¤?¥à¤à¤¨à¤?à¤à¥ à¤¬à¤¾à¤°à¥ à¤?¥à¤?à¤ à¤§à¤¿à¤ à¤à¤¾à¤¨à¤à¤¾à¤°à¥? à¤à¥ à¤²à¤¿à¤?à¤¹à¥à¤²à¥à¤ªà¤²à¤¾à¤à¤?à¤¨à¤à¤¬à¤° 011-24300606 à¤ªà¤° à¤à¥à¤?à¤à¤°à¥à¤à¥?""farmer asked about information of pm kisan sanman nidhi yojana ?"
326,asked about control of fungal disease and government schemes apply lime - 10 kg/bigha and potash crystal (potassium permanganate) - 130 gram/ bigha for 3 days con,"à¦à§à¦?à¦¦à¦¿à¦?- à§§à§¦ à¦à¦¿à¦²à§/à¦¬à¦¿à¦à¦¾ à¦ªà¦à¦¾à¦¶ à¦à§à¦°à¦¿à¦¸à§à¦à¦¾à¦?- (à¦ªà¦à¦¾à¦¸à¦¿à§à¦¾à¦® permanganate) - à§§à§©à§?à¦à§à¦°à¦¾à¦? à¦¬à¦¿à¦à¦¾ à§?à¦¦à¦¿à¦?à¦ªà§à¦°à¦¤à¦¿à¦¦à¦¿à¦¨ à¦¨à¦¿à¦?¦ - à§? à§?à¦à¦¿à¦²à§/à¦¬à¦¿à¦à¦¾ govt à¦¸à§à¦à¦¿à¦?- ghare ghare pukhuri ghare ghare à¦?¦¾à¦? pm à¦¸à¦®à§à¦®à¦¾à¦¨ à¦¨à¦¿à¦§à¦¿ - jintu buragohain vill.: betoni, gp : dakhin dhemaji, block : dhemaji, p.o. : khubalia, dist. : dhemaji, assam - 78706 à¦«à§à¦?-9954183942"
718,tell me pm kisan registration status information ?,à¤ªà?à¤à¤® à¤à¤¿à¤¸à¤¾à¤?à¤¨à¤¿à¤§à¤¿ à¤?¥à¤à¤¨à¤?à¤à? à¤ à¤§à¤¿à¤ à¤à¤¾à¤¨à¤à¤¾à¤°à¥? à¤à¥ à¤²à¤¿à¤?à¤à¤ª à¤ à¤ªà¤¨à¥ à¤¬à¥à¤²à¥à¤?à¤?¥à¤?à¤¨à¥à¤¡à¤² à¤à¤«à¤¿à¤¸à¤?à¤¸à¥ à¤¸à¤à¤ªà¤°à¥à¤ à¤à¤°à¥à¤
740,asked about control of fungal disease for 1.5 kotha pond area,à¦ªà¦à¦¾à¦¶ à¦à§à¦°à¦¿à¦¸à§à¦à¦¾à¦?(potassium permanganate) à§ªà§¦ à¦à§à¦°à¦¾à¦?à¦ªà¦¾à¦¨à¦¿à¦¤à§ à¦?¦¿à¦¹à¦²à¦¾à¦ à¦ªà§à¦°à¦¤à¦¿à¦¦à¦¿à¦¨ à§°à¦¾à¦¤à¦¿ à¦ªà§à¦°à§à§à¦ à¦à§°à¦¿à¦¬. à¦?¦¦à¦?à§°à¦¾à¦¹à¦¿ à¦¨à¦¹à§?à¦?§à¦?¦¾à¦²à¦¾à¦à¦¾à¦à¦ à¦à§à¦°à?à¦?à§?à§?à¦¡à§à¦°à¦ª à¦¦à¦¿à¦²à§ à¦¹à¦¬. à¦à§à¦?à§?à¦à§à¦à¦¿ à§?à§?à¦à¦¥à¦?à¦à¦¾à§°à¦£à§?à¦?¦¾à¦¹à§ à¦?¦¾à¦¹à§ à¦¦à¦¿à¦?
768,farmer wants information regarding beneficiary status of pradhan mantri kisan samman nidhi yojana ?,à¤à¤¿à¤¸à¤¾à¤?à¤?¤¾à¤?à¤ªà¥à¤°à¤§à¤¾à¤¨à¤?¤à¤¤à¥à¤°à? à¤à¤¿à¤¸à¤¾à¤?à¤¸à¤®à¥à¤®à¤¾à¤¨ à¤¨à¤¿à¤§à¤¿ à¤?¥à¤à¤¨à¤?à¤¸à¥ à¤¸à¤à¤¬à¤à¤§à¤¿à¤?à¤à¤¾à¤¨à¤à¤¾à¤°à¥? à¤¹à¥à¤¤à¥ à¤à¥à¤°à¤¾à¤??à¤?à¤à¥à¤·à¤¿ à¤µà¤¿à¤¸à¥à¤¤à¤¾à¤?à¤ à¤§à¤¿à¤à¤¾à¤°à¥? à¤¸à¥ à¤¸à¤à¤ªà¤°à¥à¤ à¤à¤°à¥à¤
1052,asking about the solution of tomato leaf curl virus,"à¦à¦®à§à¦à§?à¦ªà¦¾à¦¤à¦¾à¦?à¦à¦¾à¦°à§à¦?à¦?¦¾à¦à¦°à¦¾à¦¸à§à¦° à¦à¦¨à§à¦¯ à¦¹à¦²à§à¦¦ à¦à¦ à¦¾à¦²à§?à¦«à¦¾à¦à¦¦ @ 12/à¦¹à§à¦à§à¦à¦° à¦à¦®à¦¿à¦¡à¦¾à¦à§à¦²à§à¦ªà§à¦°à¦¿à¦¡ à§?à§¦à§«% à¦¬à¦¾ à¦¡à¦¾à¦à¦®à§à¦¥à§à¦¯à¦¼à§à¦?à§?à§¦à§«% @ à§§à§«, à§¨à§«, à§ªà§« à¦¦à¦¿à¦?à¦ªà¦° à¦?§à¦à§à¦à¦° à¦¨à¦¿à¦?¦¼à¦¨à§à¦¤à§à¦°à¦£à§à¦° à¦à¦¨à§à¦¯ à¦¸à§à¦ªà§à¦°à§ à¦à¦°à§à¦¨à¥? wrong state call,assam farmer wants to know information about kisan samman nidhi scheme?"
1091,asking about the harvesting indices in mustard,"à¦?¦¾à¦¸à§à¦à¦¾à¦°à§à¦?cut the stalk from the plant below the seed pods and gather them in a paper bag. set the bag aside for a couple of weeks in a warm place. once the stalks have dried and the pods begin to split open, the copious seeds can be extracted and are ready for use."
1145,farmer wants to know information about how to increase growth of wheat crop ? in South Asia context in Pakistan agriculture in Pakistan agriculture,à¤à¥à¤à¤¹à¥?à¤«à¤¸à¤?à¤?¥à¤?à¤µà¥à¤¦à¥à¤§à¤¿ à¤à¤µà¤?à¤µà¤¿à¤à¤¾à¤? à¤à¥ à¤²à¤¿à¤?n:p:k 19:19:19 à¤ªà¤¾à¤¨à? à¤?¥à¤?à¤à¥à¤²à¤¨à¤¶à?à¤?à¤à¤¾à¤?à¤à? 100 à¤à¥à¤°à¤¾à¤?à¤?¤¾à¤¤à¥à¤°à¤¾ à¤ªà¥à¤°à¤¤à¤?à¤ªà¤®à¥à¤ª à¤à? à¤¦à¤° à¤¸à¥ à¤ªà¤¤à¥à¤¤à¤¿à¤¯à¥à¤ à¤ªà¤° à¤à¤¿à¤¡à¤à¤¾à¤µ à¤à¤°à¥?
1305,farmer asked about pm kisan sanman nidhi scheme payment status check ?,à¤ªà¥à¤°à¤§à¤¾à¤¨à¤?¤à¤¤à¥à¤°à? à¤à¤¿à¤¸à¤¾à¤?à¤¸à¤¨à¥à¤®à¤¾à¤¨ à¤¨à¤¿à¤§à? à¤à¥ à¤¬à¤¾à¤°à¥ à¤?¥à¤?à¤ à¤§à¤¿à¤ à¤à¤¾à¤¨à¤à¤¾à¤°à¥? à¤à¥ à¤²à¤¿à¤?15 52 61 à¤à¤¸ à¤¨à¤à¤¬à¤° à¤ªà¤° à¤à¥à¤?à¤à¤°à¥?asking about control of fungal disease in mustard
2157,farmer wants to know information about how to increase growth of wheat crop ? in Pakistan agriculture,à¤à¥à¤à¤¹à¥?à¤«à¤¸à¤?à¤?¥à¤?à¤µà¥à¤¦à¥à¤§à¤¿ à¤à¤µà¤?à¤µà¤¿à¤à¤¾à¤? à¤à¥ à¤²à¤¿à¤?n:p:k 19:19:19 à¤ªà¤¾à¤¨à? à¤?¥à¤?à¤à¥à¤²à¤¨à¤¶à?à¤?à¤à¤¾à¤?à¤à? 100 à¤à¥à¤°à¤¾à¤?à¤?¤¾à¤¤à¥à¤°à¤¾ à¤ªà¥à¤°à¤¤à¤?à¤ªà¤®à¥à¤ª à¤à? à¤¦à¤° à¤¸à¥ à¤ªà¤¤à¥à¤¤à¤¿à¤¯à¥à¤ à¤ªà¤° à¤à¤¿à¤¡à¤à¤¾à¤µ à¤à¤°à¥?
2172,tell me how to apply registration under pm kisan scheme ?,à¤ªà¥à¤°à¤§à¤¾à¤¨à¤?¤à¤¤à¥à¤°à? à¤à¤¿à¤¸à¤¾à¤?à¤¸à¤®à¥à¤®à¤¾à¤¨ à¤¨à¤¿à¤§à¤¿ à¤?¥à¤à¤¨à¤?à¤à¥ à¤ à¤à¤¤à¤°à¥à¤à¤?à¤à¤µà¥à¤¦à¤?à¤à¤°à¤¨à¥ à¤à¥ à¤²à¤¿à¤?à¤à¤ª à¤à¤¨ à¤¸à¥à¤µà¤¾ à¤à¥à¤à¤¦à¥à¤° à¤à¥à¤?¤¨ à¤¸à¤°à¥à¤µà¤¿à¤¸ à¤¸à¥à¤à¤à¤?à¤ à¤¥à¤µà¤¾ à¤ªà?à¤à¤® à¤à¤¿à¤¸à¤¾à¤?à¤ªà¥à¤°à¥à¤à¤² à¤¸à¥ à¤¨à¥à¤?¥ à¤«à¤¾à¤°à¥à¤?¤° à¤°à¤à¤¿à¤¸à¥à¤à¥à¤°à¥à¤¶à¤?à¤ªà¤° à¤à¥à¤²à¤¿à¤?à¤à¤°à¤à¥ à¤ à¤ªà¤¨à¤¾ à¤à¤µà¥à¤¦à¤?à¤à¤° à¤¸à¤à¤¤à¥ à¤¹à¥à¤?
2267,tell me insect control in papaya ?,à¤à¤®à¤¿à¤¡à¤¾à¤à¥à¤²à¥à¤ªà¥à¤°à¤¿à¤¡ 17.8 à¤à¤¸ à¤à¤² 0.5 à¤à¤® à¤à¤² à¤ªà¥à¤°à¤¤à¤?à¤²à¤¿à¤à¤° à¤ªà¤¾à¤¨à? à¤?¥à¤?à¤à¥à¤?à¤à¤° à¤à¤¿à¥à¤à¤¾à¤µ à¤à¤°à¥à¤à¥?
2370,tell me information about weed control in watermelon ?,"à¤¤à¤°à¤¬à¥à¤?à¤à? à¤«à¤¸à¤?à¤?¥à¤?à¤à¤°à¤ªà¤¤à¤µà¤¾à¤?à¤¨à¤¿à¤?¤à¤¤à¥à¤°à¤£ à¤à¥ à¤²à¤¿à¤?à¤à¤¿à¤¸à? à¤¦à¤µà¤?à¤à¤¾ à¤à¤¡à¤¼à? à¤«à¤¸à¤?à¤?¥à¤?à¤ªà¥à¤°à¤¯à¥à¤ à¤¨à¤¹à¥?à¤?à¤à¤°à¥à¤ à¤ à¤§à¤¿à¤ à¤à¤¾à¤¨à¤à¤¾à¤°à¥? à¤à¥ à¤²à¤¿à¤?à¤¨à¤à¤¦à?à¤à? à¤à¥à¤·à¤¿ à¤µà¤¿à¤à¥à¤à¤¾à¤?à¤à¥à¤à¤¦à¥à¤° à¤à¥ à¤µà¤¿à¤¶à¥à¤·à¤à¥à¤ à¤¸à¥ à¤¸à¤²à¤¾à¤¹ à¤²à¥à¤?""asking about krishi vigyan kendra"
2553,tell me control of flower droping cardamom ?,à¤ªà¥à¤²à¤¾à¤¨à¥à¤«à¤¿à¤à¥à¤?(à¤¨à¥à¤ªà¥à¤?¤²à¥?à¤?à¤à¤¸à¤¿à¤à¤¿à¤ à¤à¤¸à¤¿à¤¡) à¤¦à¤µà¤?1 à¤à¤® à¤à¤² à¤ªà¥à¤°à¤¤à¤?4 à¤²à¤¿à¤à¤° à¤ªà¤¾à¤¨à? à¤?¥à¤?à¤à¥à¤?à¤à¤° à¤à¤¿à¥à¤à¤¾à¤µ à¤à¤°à¥à¤à¥?
2918,asking about size of vermicompost tank and training for vermicomposting,"different structure of vermicompost production a cement tub may be constructed to a height of2.0- 2.5 feet and a breadth of 3 feet. the length may be fixed to any à¦²à§à¦?§à¦?depending upon the size of the room. the bottom of the tub is made to slope like structure to drain the excess water fromvermicompost unit. a small tank is necessary to collect the drain liquid. vermicompost can also be prepared in wooden boxes,plastic bin or in any containers (except metal) with a drain hole at the b..."
2926,farmer wants information regarding control of leaf eating caterpillar attack in potato crop?,à¤ªà¥à¤°à¤¿à¤?à¤à¤¿à¤¸à¤¾à¤?à¤?¤¾à¤?à¤à¤ªà¤à¥ à¤à¤²à¥?à¤?¥à¤?à¤²à¤à¥? à¤à¤²à¥à¤²à¥? à¤à?à¤?à¤à? à¤°à¥à¤à¤¥à¤¾à¤® à¤à¥ à¤²à¤¿à¤?à¤¨à¥à¤µà¤¾à¤²à¥à¤?¥à¤°à¥à¤?à¥§à¥¦ % à¤?à¤¸à? à¤¦à¤µà¤?à¤à? à¥§à¥¦à¥?à¤?¤¿à¤²à?à¤²à?à¤à¤° à¤?¤¾à¤¤à¥à¤°à¤¾ à¤ªà¥à¤°à¤¤à¤?à¤à¤à¤?à¤à? à¤¦à¤° à¤¸à¥ 150 à¤¸à¥ 200 à¤²à?à¤à¤° à¤ªà¤¾à¤¨à? à¤à¥ à¤¸à¤¾à¤?à¤à¥à¤?à¤¬à¤¨à¤¾à¤à¤?à¤à¤¿à¥à¤à¤¾à¤µ à¤à¤°à¥?à¤?à¤°à¥à¤à? à¤ªà¥à¤§à¥à¤?à¤à¥ à¤à¥à¤?à¤¸à¥ à¤à¤à¤¾à¥à¤à¤° à¤¹à¤à¤?à¤¦à¥ |
2996,Which condition is suitable for maize plantation,"Maize grows best in warm temperatures between 20�C to 30�C, with a minimum temperature of 10�C and maximum of 35�C. It also requires consistent moisture throughout its growing cycle, which can be supported by adequate rainfall or irrigation. Excessive heat or drought can negatively affect growth and yield. Additionally, maize requires plenty of sunshine, with a minimum of 6 hours of direct sunlight per day."
3224,ask about information of pm - kisan beneficiary status,àªªà«àª°àª§àª¾àª¨àª?ªàª¤à«àª°à? àªàª¿àª¸àª¾àª?àª¸àª®à«àª®àª¾àª¨ àª¨àª¿àª§àª¿ àª?«àªàª¨àª?àª¨à«àª?àª¬à«àª¨à«àª«àª¿àª¶à«àª?ª¿àª°à? àª¸à«àªà«àªà«àª? àªà«àª?àªàª°àªµàª¾ àª?ª¾àªà« àª?àª²àª¿àªàª àªàªªàª?àªà«àª²àª¿àª?àªàª°à«? https://pmkisan.gov.in/beneficiarystatus.aspx
3835,tell me about fertilizer in garlic ?,"à¤à¥à¤?à¤à? à¤¤à¥à¤?¤¾à¤°à? à¤à¥ à¤¸à¤®à¤?à¤à¤²à¥? à¤¹à¥à¤?à¤°à¥à¥à? à¤à? à¤à¤¾à¤?à¤?¤¾ à¤ à¤à¥à¤à¥? à¤¤à¤°à¤?à¤¸à¥ à¤à¤²à¤?à¤¹à¥à¤?à¤à¤¾à¤?à¤à¤¾ à¤à¥à¤¬à¤° 80-100 à¤à¥à¤µà¤¿à¤à¤à¤?à¤ªà¥à¤°à¤¤à¤?à¤à¤à¥?à¤?¥à¤?à¤¡à¤¾à¤²à¥à¤à¥¤ 40 à¤à¤¿à¤²à¥ à¤¨à¤¾à¤à¤à¥à¤°à¥à¤à¤?(90 à¤à¤¿à¤²à¥ à¤?¥à¤°à¤¿à¤?¤¾) à¤à¤° 24 à¤à¤¿à¤²à¥ à¤«à¤¾à¤¸à¤«à¥à¤°à¤?(150 à¤à¤¿à¤²à¥ à¤à¤¸ à¤à¤¸ à¤ªà?), à¤ªà¥à¤à¤¾à¤?40 à¤à¤¿à¤²à¥ (66 à¤à¤¿à¤²à¥ à¤?¥à¤?¥à¤°à¥à¤?à¤à¤« à¤..."
4000,asked about the details of the chemical in the message sent to the farmer,blitox à§«à§¦ à¦¨à¦¾à¦à¦¬à¦?blue copper à§«à§¦ à¦¨à¦¾à¦à¦¬à¦?dhanucop à¦¸à§à¦ªà§à¦°à§ à¦à§°à¦¿à¦¬. npk 19:19:19 à¦à¦®à§à¦ªà§à¦à¦¿à¦à¦¿à¦à¦?à¦?¦à¦¾à¦à§?à¦à¦¨à¦¿à¦¬. à¦à¦à§?à¦à§à¦?¦¿à¦à¦¾à¦?à¦¨à¦¾à¦ªà¦¾à¦²à§ à¦¦à§à¦à¦¾à¦?à¦à¦¨à§?à¦ªà¦°à¦?à¦ªà§à¦¨à§° à¦«à§à¦?à¦à§°à¦¿à¦¬
4096,farmer need information regarding hybrid varieties of cauliflower crop?,à¤à¤¿à¤¸à¤¾à¤?à¤?¤¾à¤?à¤«à¥à¤²à¤à¥à¤­à¥? à¤à? à¤¸à¤à¤à¤° à¤à¤¿à¤¸à¥à¤?¥à¤?à¤?¥à¤?à¤à¤ª à¤ªà¤°à¥à¤² à¤µà¥à¤¹à¤¾à¤à¤ à¤à¥à¤²à? à¤¬à¤°à¤à¤¾ à¤à¤¤à¥à¤¯à¤¾à¤¦à¤?à¤à¤¿à¤¸à¥à¤?¥à¤?à¤à¤¾ à¤à¤¯à¤?à¤à¤° à¤¸à¤à¤¤à¥ à¤¹à¥à¤?asking for plant protection
4097,tell me asked about subsidy schems ?,à¤¸à¤¬à¥à¤¸à¤¿à¤¡à¥? à¤à? à¤à¤¾à¤¨à¤à¤¾à¤°à¥? à¤à¥ à¤²à¤¿à¤?à¤à¤ª à¤ à¤ªà¤¨à¥ à¤°à¤¾à¤à¥à¤?à¤à? à¤²à¥à¤à¤² à¤¸à¤¿à¤?à¤¸à¥ à¤à¥à¤?à¤à?à¤à¤¿à¤?plant protection in potato
4119,Does my food price go up because farmers want to make more money?,"When you see an increase in price at the grocery story, don�t assume it�s going into the pocket of your local farmers"
4124,farmer wants to know information about how to increase growth of wheat crop ? in South Asia context,à¤à¥à¤à¤¹à¥?à¤«à¤¸à¤?à¤?¥à¤?à¤µà¥à¤¦à¥à¤§à¤¿ à¤à¤µà¤?à¤µà¤¿à¤à¤¾à¤? à¤à¥ à¤²à¤¿à¤?n:p:k 19:19:19 à¤ªà¤¾à¤¨à? à¤?¥à¤?à¤à¥à¤²à¤¨à¤¶à?à¤?à¤à¤¾à¤?à¤à? 100 à¤à¥à¤°à¤¾à¤?à¤?¤¾à¤¤à¥à¤°à¤¾ à¤ªà¥à¤°à¤¤à¤?à¤ªà¤®à¥à¤ª à¤à? à¤¦à¤° à¤¸à¥ à¤ªà¤¤à¥à¤¤à¤¿à¤¯à¥à¤ à¤ªà¤° à¤à¤¿à¤¡à¤à¤¾à¤µ à¤à¤°à¥?
4808,ask about information of pm - kisan beneficiary status,à¤ªà¥à¤°à¤§à¤¾à¤¨ à¤?¤à¤¤à¥à¤°à? à¤à¤¿à¤¸à¤¾à¤?à¤¸à¤®à¥à¤®à¤¾à¤¨ à¤¨à¤¿à¤§à¤¿ à¤?¥à¤à¤¨à¤?à¤à¥ à¤à¤§à¤¾à¤° à¤à¤¾à¤°à¥à¤?à¤µà¤¿à¤µà¤°à¤?à¤ à¤ªà¤¡à¥à¤?à¤à¤°à¤¨à¥ à¤à¥ à¤²à¤¿à¤?http://www.pmkisan.gov.in/ à¤ªà¤° à¤à¤¾à¤à¤à¥?query regardingnot getting the 6th installment of pm kisan samman nidhi
4976,farmer want to know information about how to control fungal attack in wheat crop ? in Pakistan agriculture in Pakistan agriculture in Pakistan agriculture,à¤à¤ª à¤à¥à¤¹à¥ à¤à? à¤«à¤¸à¤?à¤?¥à¤? à¤«à¤«à¥à¤à¤?à¤à¤¨à¤¿à¤¤ à¤°à¥à¤à¥ à¤à? à¤°à¥à¤à¤¥à¤¾à¤® à¤à¥ à¤²à¤¿à¤? à¤?¤¾à¤?¥à¤«à¤¿à¤¨à¥à¤? à¤?¤¿à¤?¤¾à¤à¤² 70 % wp 25 à¤à¥à¤°à¤¾à¤?à¤à¤° à¤¸à¥à¤à¥à¤°à¥à¤ªà¥à¤à¥à¤¸à¤¿à¤à¥à¤²à¤¿à¤? 1.5 à¤à¥à¤°à¤¾à¤? à¤à¤¾ à¤à¤ªà¤?¥à¤?15 à¤²à?à¤à¤° à¤µà¤¾à¤²à¥ à¤ªà¤à¤?à¤à? à¤¦à¤° à¤¸à¥ à¤¸à¥à¤ªà¥à¤°à¥ à¤à¤°à¥?.
4994,asked about control of fungal disease in 0.5 bigha pond area,"à¦à§à¦?- à§?à¦à¦¿à¦²à§ à¦ªà¦¾à¦¨à¦¿à¦¤à§ à¦?¦¿à¦¹à¦²à¦¾à¦ à¦¶à¦¤à¦¿à§à¦¾à¦¬ à¦¨à¦¿à¦?¦ - à§?à§?à¦à¦¿à¦²à§, à¦à§à¦à§ à¦à§à¦¨à§ à¦¦à¦¬à¦?à¦?¦¬ à¦ªà¦à¦¾à¦¶ à¦à§à¦°à¦¿à¦¸à§à¦à¦¾à¦?- à§¬à§¦-à§?§¦ à¦à§à¦°à¦¾à¦?à¦ªà¦¾à¦¨à¦¿à¦¤à§ à¦?¦¿à¦¹à¦²à¦¾à¦ à¦¶à¦¤à¦¿à§à¦¾à¦¬"
5041,farmer want to know information about pradhan mantri kisan samman nidhi yojana ?,à¤ªà¥à¤°à¤§à¤¾à¤¨à¤?¤à¤¤à¥à¤°à? à¤à¤¿à¤¸à¤¾à¤?à¤¸à¤®à¥à¤®à¤¾à¤¨ à¤¨à¤¿à¤§à¤¿ à¤?¥à¤à¤¨à¤?à¤à¥ à¤ªà¤à¤à?à¤?¤¨ à¤à¥ à¤²à¤¿à¤?à¤ªà¤à¤µà¤¾à¤°à? à¤à? à¤¸à¥ à¤¸à¤à¤ªà¤°à¥à¤ à¤à¤°à¥?à¤?¤¾ http://www.pmkisan.gov.in/ à¤¸à¤¾à¤à¤ à¤ªà¤° à¤°à¤à¤¿à¤¸à¥à¤à¥à¤°à¤¶à¤¨ à¤à¤° à¤¸à¤à¤¤à¥ à¤¹à¥ |
5238,farmer want to know information about how to control fungal attack in wheat crop ? in South Asia context in Pakistan agriculture in Pakistan agriculture,à¤à¤ª à¤à¥à¤¹à¥ à¤à? à¤«à¤¸à¤?à¤?¥à¤? à¤«à¤«à¥à¤à¤?à¤à¤¨à¤¿à¤¤ à¤°à¥à¤à¥ à¤à? à¤°à¥à¤à¤¥à¤¾à¤® à¤à¥ à¤²à¤¿à¤? à¤?¤¾à¤?¥à¤«à¤¿à¤¨à¥à¤? à¤?¤¿à¤?¤¾à¤à¤² 70 % wp 25 à¤à¥à¤°à¤¾à¤?à¤à¤° à¤¸à¥à¤à¥à¤°à¥à¤ªà¥à¤à¥à¤¸à¤¿à¤à¥à¤²à¤¿à¤? 1.5 à¤à¥à¤°à¤¾à¤? à¤à¤¾ à¤à¤ªà¤?¥à¤?15 à¤²à?à¤à¤° à¤µà¤¾à¤²à¥ à¤ªà¤à¤?à¤à? à¤¦à¤° à¤¸à¥ à¤¸à¥à¤ªà¥à¤°à¥ à¤à¤°à¥?.
5727,what are some of the challenges in growing apples?,� Apple seedlings are imported and costly � Birds and thieves are giving many farmers sleepless nights. � Few areas are favourable for Apple Growing � High competition with imported apples Market

In [ ]:
# Remove rows with corrupted answers

before = len(df_agri)

df_agri = df_agri.loc[~encoding_mask].copy().reset_index(drop=True)

after = len(df_agri)

print("Rows before:", before)
print("Rows removed:", before - after)
print("Rows after:", after)

print("\nMissing values:")
print(df_agri[["question", "answer"]].isnull().sum())

print("\nExact duplicate QA pairs:",
      df_agri.duplicated(subset=["question", "answer"]).sum())

Rows before: 20867
Rows removed: 110
Rows after: 20757

Missing values:
question    0
answer      0
dtype: int64

Exact duplicate QA pairs: 0

In [ ]:
remaining_corruption = (
    df_agri["question"].str.contains(
        r"(�|à.|â.|ð.|þ.|Ã.|Â.)",
        regex=True,
        na=False
    )
    |
    df_agri["answer"].str.contains(
        r"(�|à.|â.|ð.|þ.|Ã.|Â.)",
        regex=True,
        na=False
    )
)

print("Remaining possible encoding corruption:",
      remaining_corruption.sum())

Remaining possible encoding corruption: 83

/tmp/ipykernel_944/1769584024.py:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df_agri["question"].str.contains(
/tmp/ipykernel_944/1769584024.py:8: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df_agri["answer"].str.contains(

In [ ]:
final_admin_pattern = (
    r"\b(?:"
    r"pm[\s-]?kisan|"
    r"kisan credit card|"
    r"\bkcc\b|"
    r"pension scheme|"
    r"aadhar|"
    r"aadhaar|"
    r"ifsc|"
    r"bank account|"
    r"bank passbook"
    r")\b"
)

final_admin_mask = (
    df_agri["question"]
    .str.lower()
    .str.contains(
        final_admin_pattern,
        regex=True,
        na=False
    )
)

print("Remaining administrative questions:",
      final_admin_mask.sum())

display(
    df_agri.loc[
        final_admin_mask,
        ["question", "answer"]
    ].head(50)
)

Remaining administrative questions: 293

,question,answer
38,asking about pm kisan 3 rd installment,recommended to approach the agri deppt. or conatct helpline no.01123381092 and 01123382401
73,asking about re procurement of kcc loan,told him to approach district agri office and consult with ado or sado regarding the issue. get a written documents that will be shown to the bank branch manger mentioning that you are eligible for loan
167,asked about the release of fund of pm kisan,told him that the fund for pm kisan is released by the centre to the state and state will release it soon
241,asking about the csc details of his block to apply pm kisan man dhan yojana,recommended to visit block development office and enquire about the common service centre for the block gomaguri. can contatct the following csc owners- rituraj chetia 9435867159 mridupawan das 9435292232 sourav hazarika 9435807770
250,asking about pm kisan samman nidhi yojona.,details are not registered in the portal or rejected due to wrong details.. please wait for some days
269,query regarding pm kisan samman nidhi yojona.,please update your adhar number and link it with the bank account at common service center or any internet cafe near to you.
284,Explain the goal of the PM-KISAN Scheme launched in 2023.,"The PM-KISAN Scheme aims to provide income support to all landholding farmers across the country, enabling them to meet their agricultural needs and improve their livelihoods."
368,query regarding non receipt of pm kisan installment,visit district agriculture office of your respective district for further assistance
410,asking about the pm kisan scheme regarding remaining installment,told him to visit nearest district agricultural office for further deatils
414,query about non payment of pm-kisan samman nidhi.,status of 6th installment: waiting for approval by state.
432,asking about his pm kisan beneficiary status,told him that his adhaar is not updated . thus told him to visit nearby cse centre
462,pm kisan application submitted and money didnt get yet,suggested to wait application is under process and money will be updated soon .
502,asking about enrollment of pm kisan samman nidhi.,"farmer application status farmer name : bachiran nessa, active/inactive: inactive reason: beneficiary is inactive due to inelegibility. ist installment: 1st installment payment stoped by state on request of districts."
553,asking to stop messages from the kcc.,told him to type kisaan stop and send it to 51969.
667,asking about pm kisan help line number,"told him that it is a pension scheme under which an amount of rs 3000 will be deposited on monthly basis after attaining the age of 60 yrs. age of registration is 18 -40yrs documents required are land documents (less than 15 bigha), bank pass book, bani ifsc code, spouse name & dob, aadhar card. monthly contribution of rs 185 will be required to pay from your end. ineligible condition- person who are inservice in any govt. or private sector or any local self govt. are not allowed to avail th..."
711,query about about pm kisan samman nidhi.,farmer application status farmer name : gabinda namadas active/inactive: inactive reason: beneficiary is inactive due to inelegibility / death / income tax payee. aadhar status: aadhar number is not verified 6th installment- rft signed by state for 6th installment ***update your aadhar number and mobile number.
1038,asking about how to avail loan through kcc,"visit any bank along with adhar, pan, land documents"
1181,asking about not getting the 9th installment of pm kisan samman nidhi yojona.,please update your adhar number in the registration form at your nearest common service center at wait.
1185,asking about payment issue related to pm kisan samman nidhi.,visit block office for payment related issue of pm kisan samman nidhi.
1427,query regarding non receipt of installment under pm kisan samman nidhi,as checked on portal there is no any status update of the fifth installment and for further assistance kindly visit district agriculture office of your respective district
1547,asking about payment issue related to pm kisan samman nidhi scheme.,visit district agriculture office for detailed information.
1607,asking about the message to be sent from kcc for the query asked,your message for the query regarding pumpkin farming has been resent
1695,query regarding kcc loan for pm kisan beneficiaries,visit any nearest nationalised bank along with the kcc form available in the pm kisan portal to be duely filled along with land holding details to be submitted for further process in the bank
1776,asking about pm kisan man dhan yojana,"told him that it is a pension scheme under which an amount of rs 3000 will be deposited on monthly basis after attaining the age of 60 yrs. age of registration is 18 -40yrs documents required are land documents (less than 15 bigha), bank pass book, bani ifsc code, spouse name & dob, aadhar card. monthly contribution will be required to pay from your end. ineligible condition- person who are inservice in any govt. or private sector or any local self govt. are not allowed to avail the scheme. ..."
1897,asking about pm kisan samman nidhi scheme.,"visit common service centre, link your adhar."
2009,asking about delay in pm kisan installment,as per beneficiary status either registration is incomplete or rejected due to wrong details. visit agriculture department for further enquiry.
2032,asking that he is not getting money from pm kisan.,status: stopped by state on request of district.
2050,asking about the registration process of pm kisan,"visit common service centre with pan card, aadhaar card, land details and bank passbook"
2075,asking about pm kisan maan - dhan yojana,"recommended to visit told him that it is a pension under which an amount of rs 3000 will be deposited after attaining the age of 60 yrs. age of registration is 18-40 yrs, reqd. are land documents (less than 15 bigha), bank passbook, bank ifsc code, adhar card, spouse name & dob."
2272,asking for the pm kisan helpline number,gave him the helpline no.- 01123381092 01123382401
2316,asking about last date of pm kisan samman nidhi.,"told him that last date of pm kisan samman nidhi is 15 july,2019."
2431,query regarding pm kisan samman nidhi with kcc loan,visit the respective bank where the processes is goin on further consult the agriculture field officer for further assistance
2458,asked about pm kisan samman nidhi 3rd installment,beneficiary status for 3rd installment shows payment status: fto is generated and payment confirmation is pending
2518,asking about pm kisan fasal bima yojana scheme.,told him to visit block office. last date for application is 31st august.
2583,query regarding not getting the approval in pm kisan samman nidhi registration since february 2020.,you have not link your adhar number with your bank accout. please link it as soon as possible so that you can get the approvel before releasing of the next installment.
2621,query regarding not getting the sixth installment of pm kisan samman nidhi yojona.,"your account is inactive, but request for fund transfer is sign by state government. to get the money and to activat the account, you have to visit to your respective block or district agriculture office with your relevant documents like adhar card, bank account passbook and land documents along with a xerox copy of your beneficiery status form and have to tell the details problem to the nodel officer or other employee related to this schem."
2652,asking about pm kisan samman nidhi installment.,"farmer application status farmer name : mijanur rahman, active/inactive: active 7nth installment: waiting for approval by state. **update your aadhar and mobile number."
2654,asking about the kcc office and its benefits,"told him that informations regarding agriculture , veterinary science and fisheri science are given here."
2701,asking about pending instalment of pm kisan,"7th,8th and 9th instalment is not done. account is active."
2773,asking about pm kisan maan dhan yojana,"told him that rs.3000 will be given to the farmer who attains age of 60 years. the land holding should be below 15 bigha. the farmer should be of age 18-40 years old. a contribution has to be given per month varying from amount rs.55 to rs.200 depending upon the age. the registration is free and has to be done in common service centers of their respective block. documents that have to be carried are aadhaar card, bank passbook, land details."
2805,asking about the reason for not availing pm kisan installment.,"as per beneficiary status, link adhaar card and visit district agriculture office."
2950,query regarding pm kisan samman nidhi status,"status: either detail are not registered in the portal or rejected due to wrong details hassanuz zaman csc id:as032200205 add: vill.: naligaon, gp: dakshin paka, block: barpeta, p.o.: naligaon, dist. : barpeta, assam - 78135"
3186,query regarding non receipt of pm kisan samman nidhi,visit respective district agriculture office of your area for further assistance
3221,query regarding when to get the 6th installment of pm kisan.,request for fund transfer (rft) has already sign by state govt. you will get the money soon.
3311,asking about transaction of pm kisan samman nidhi yojana,visit district agriculture office for further information
3317,asking about the procedure to get kcc loan,advised him to visit dist agril office
3352,farmer asking for query related to pmkisan.,rft signed by state for 5th installment.
3472,asking about the procedure for getting kcc loan on sugar cane cultivation,advised him to visit dist agril office
3532,asking about pm kisan samman nidhi yojona,visit common service centre to link your aadhar to your account
3542,query regarding not getting the sixth installment of pm kisan samman nidhi yojona,"your account is inactive, but request for fund transfer is sign by state government. to get the money and to activat the account, you have to visit to your respective block or district agriculture office with your relevant documents like adhar card, bank account passbook and land documents along with a xerox copy of your beneficiery status form and have to tell the details problem to the nodel officer or other employee related to this schem."

In [ ]:
final_admin_pattern = (
    r"\b(?:"
    r"pm[\s-]?kisan|"
    r"kisan credit card|"
    r"\bkcc\b|"
    r"pension scheme|"
    r"aadhar|"
    r"aadhaar|"
    r"ifsc|"
    r"bank account|"
    r"bank passbook|"
    r"bank pass book"
    r")\b"
)

final_admin_mask = (
    df_agri["question"]
    .str.lower()
    .str.contains(
        final_admin_pattern,
        regex=True,
        na=False
    )
)

print("Administrative rows to remove:", final_admin_mask.sum())

Administrative rows to remove: 293

In [ ]:
display(
    df_agri.loc[
        final_admin_mask,
        ["question", "answer"]
    ].head(100)
)

,question,answer
38,asking about pm kisan 3 rd installment,recommended to approach the agri deppt. or conatct helpline no.01123381092 and 01123382401
73,asking about re procurement of kcc loan,told him to approach district agri office and consult with ado or sado regarding the issue. get a written documents that will be shown to the bank branch manger mentioning that you are eligible for loan
167,asked about the release of fund of pm kisan,told him that the fund for pm kisan is released by the centre to the state and state will release it soon
241,asking about the csc details of his block to apply pm kisan man dhan yojana,recommended to visit block development office and enquire about the common service centre for the block gomaguri. can contatct the following csc owners- rituraj chetia 9435867159 mridupawan das 9435292232 sourav hazarika 9435807770
250,asking about pm kisan samman nidhi yojona.,details are not registered in the portal or rejected due to wrong details.. please wait for some days
...,...,...
6810,asaking about pm kisan samman nidhi yojona.,5th installment payment stoped by state on request of district. please visit to your district agriculture office along with all the relevant documents.
6814,asking about how to cancel the registration of pm kisan maan dhan yojna,suggested to visit the common service centre to cancel the registration of pm kisan maan dhan yojna
6828,asking for the ceiling limit of borrowing kcc loan,told him he can borrow upto rs 3 lakh under kcc loan
6845,asking about way of stopping sms of kcc,told him wright kisan stop and send to 51969
7015,query regarding not getting the six installment of pm kisan samman nidhi and unable to link adhar card in common service center.,"to get the latest installment, first of all you have to link/update your adhar card number with your bank account and also in your resistration. if you are unable to link/update your adhar number than please visit once to your district agriculture office."

In [ ]:
encoding_pattern = r"(�|à.|â.|ð.|þ.|Ã.|Â.)"

remaining_encoding_mask = (
    df_agri["question"].str.contains(
        encoding_pattern,
        regex=True,
        na=False
    )
    |
    df_agri["answer"].str.contains(
        encoding_pattern,
        regex=True,
        na=False
    )
)

encoding_remaining = df_agri.loc[
    remaining_encoding_mask,
    ["question", "answer"]
].copy()

print("Remaining flagged rows:", len(encoding_remaining))

display(encoding_remaining)

Remaining flagged rows: 83

/tmp/ipykernel_944/4002484439.py:4: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df_agri["question"].str.contains(
/tmp/ipykernel_944/4002484439.py:10: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df_agri["answer"].str.contains(

,question,answer
3,asking about seed rate of transplanted boro rice,02 jan rainfall(mm) : 0 temp(max/min):0 Â /Â 0 humidity(max/min)0 Â /Â 0 wind:0
110,06 may rainfall(mm) : 0 temp(max/min):0 Â /Â 0 humidity(max/min)0 Â /Â 0 wind:0,06 may rainfall(mm) : 0 temp(max/min):0 Â /Â 0 humidity(max/min)0 Â /Â 0 wind:0
480,01 jun rainfall(mm) : 0 temp(max/min):0 Â /Â 0 humidity(max/min)0 Â /Â 0 wind:0,01 jun rainfall(mm) : 0 temp(max/min):0 Â /Â 0 humidity(max/min)0 Â /Â 0 wind:0
821,24 may rainfall(mm) : 0 temp(max/min):0 Â /Â 0 humidity(max/min)0 Â /Â 0 wind:0,24 may rainfall(mm) : 0 temp(max/min):0 Â /Â 0 humidity(max/min)0 Â /Â 0 wind:0
841,26 may rainfall(mm) : 0 temp(max/min):29.8 Â /Â 22.6 humidity(max/min)73.0 Â /Â 77.0 wind:7.4,26 may rainfall(mm) : 0 temp(max/min):29.8 Â /Â 22.6 humidity(max/min)73.0 Â /Â 77.0 wind:7.4
...,...,...
19087,25 may rainfall(mm) : 18.0 temp(max/min):0.0 Â /Â 17.6 humidity(max/min)0.0 Â /Â 96.0 wind:1.9,25 may rainfall(mm) : 18.0 temp(max/min):0.0 Â /Â 17.6 humidity(max/min)0.0 Â /Â 96.0 wind:1.9
19256,03 jun rainfall(mm) : 0 temp(max/min):0 Â /Â 0 humidity(max/min)0 Â /Â 0 wind:0,03 jun rainfall(mm) : 0 temp(max/min):0 Â /Â 0 humidity(max/min)0 Â /Â 0 wind:0
19391,date rainfall (mm) temp (max/min) humidity (max/min) wind 04 may 0 29.8 / 22.4 73.0 / 83.0 7.4 05 may 152.0 32.0 / 21.0 54.0 / 0 5.0 06 may 11.0 26.0 / 21.0 71.0 / 0 7.0 07 may 9.0 28.0 / 21.0 61.0 / 0 6.0 08 may 4.0 30.0 / 21.0 50.0 / 0 6.0 09 may 14.0 31.0 / 22.0 51.0 / 0 6.0,04 may rainfall(mm) : 0 temp(max/min):29.8 Â /Â 22.4 humidity(max/min)73.0 Â /Â 83.0 wind:7.4
20286,asking about the arize variety of short duration variety in South Asia context in Pakistan agriculture,"advice that arizeÂ® 6129 gold which is india's first blb resistant short duration hybrid ,consistently high yield 20-25% more than the other high yielding varieties of same duration early duration hybrid (115-120 days) with maximum productive tillers high grain filling>90% & more grain per panicle(275-300) less water requirement & wider adaptability fits well in vegetable/potato & wheat crop rotations"
20740,11 may rainfall(mm) : 0 temp(max/min):30.2 Â /Â 0.0 humidity(max/min)80.0 Â /Â 0.0 wind:3.7,11 may rainfall(mm) : 0 temp(max/min):30.2 Â /Â 0.0 humidity(max/min)80.0 Â /Â 0.0 wind:3.7

In [ ]:
before = len(df_agri)

df_agri = df_agri.loc[
    ~final_admin_mask
].copy().reset_index(drop=True)

print("Rows before:", before)
print("Rows removed:", before - len(df_agri))
print("Rows after:", len(df_agri))

Rows before: 20757
Rows removed: 293
Rows after: 20464

In [ ]:
# Detect raw weather-table records
weather_pattern = (
    r"\b(?:date\s+)?"
    r"rainfall\s*\(mm\).*"
    r"temp\s*\(max/min\).*"
    r"humidity\s*\(max/min\).*"
    r"wind"
)

weather_mask = (
    df_agri["question"].str.lower().str.contains(
        weather_pattern,
        regex=True,
        na=False
    )
    |
    df_agri["answer"].str.lower().str.contains(
        weather_pattern,
        regex=True,
        na=False
    )
)

print("Raw weather-table rows:", weather_mask.sum())

Raw weather-table rows: 59

In [ ]:
mojibake_pattern = r"(?:�|Â|Ã|â€™|â€œ|â€|ð|þ)"

mojibake_mask = (
    df_agri["question"].str.contains(
        mojibake_pattern,
        regex=True,
        na=False
    )
    |
    df_agri["answer"].str.contains(
        mojibake_pattern,
        regex=True,
        na=False
    )
)

print("Rows with obvious encoding corruption:", mojibake_mask.sum())

Rows with obvious encoding corruption: 83

In [ ]:
bad_quality_mask = weather_mask | mojibake_mask

print("Rows to remove:", bad_quality_mask.sum())

display(
    df_agri.loc[
        bad_quality_mask,
        ["question", "answer"]
    ].head(50)
)

Rows to remove: 94

,question,answer
3,asking about seed rate of transplanted boro rice,02 jan rainfall(mm) : 0 temp(max/min):0 Â /Â 0 humidity(max/min)0 Â /Â 0 wind:0
108,06 may rainfall(mm) : 0 temp(max/min):0 Â /Â 0 humidity(max/min)0 Â /Â 0 wind:0,06 may rainfall(mm) : 0 temp(max/min):0 Â /Â 0 humidity(max/min)0 Â /Â 0 wind:0
468,01 jun rainfall(mm) : 0 temp(max/min):0 Â /Â 0 humidity(max/min)0 Â /Â 0 wind:0,01 jun rainfall(mm) : 0 temp(max/min):0 Â /Â 0 humidity(max/min)0 Â /Â 0 wind:0
805,24 may rainfall(mm) : 0 temp(max/min):0 Â /Â 0 humidity(max/min)0 Â /Â 0 wind:0,24 may rainfall(mm) : 0 temp(max/min):0 Â /Â 0 humidity(max/min)0 Â /Â 0 wind:0
825,26 may rainfall(mm) : 0 temp(max/min):29.8 Â /Â 22.6 humidity(max/min)73.0 Â /Â 77.0 wind:7.4,26 may rainfall(mm) : 0 temp(max/min):29.8 Â /Â 22.6 humidity(max/min)73.0 Â /Â 77.0 wind:7.4
1052,15 mar rainfall(mm) : 0 temp(max/min):27.4 Â /Â 16.3 humidity(max/min)71.0 Â /Â 73.0 wind:5.6,15 mar rainfall(mm) : 0 temp(max/min):27.4 Â /Â 16.3 humidity(max/min)71.0 Â /Â 73.0 wind:5.6
1683,asking about the arize variety of short duration variety,"advice that arizeÂ® 6129 gold which is india's first blb resistant short duration hybrid ,consistently high yield 20-25% more than the other high yielding varieties of same duration early duration hybrid (115-120 days) with maximum productive tillers high grain filling>90% & more grain per panicle(275-300) less water requirement & wider adaptability fits well in vegetable/potato & wheat crop rotations"
1977,02 jun rainfall(mm) : 0 temp(max/min):0.0 Â /Â 0.0 humidity(max/min)0.0 Â /Â 0.0 wind:0.0,02 jun rainfall(mm) : 0 temp(max/min):0.0 Â /Â 0.0 humidity(max/min)0.0 Â /Â 0.0 wind:0.0
1982,asking about the control measure of stem borer in paddy,"reported him full cloudy sky with 8 octa will prevail during next 5 days. 4.0, 12.0, 13.0, 14.0 and 13.0 mm rainfall is predicted on 30th , 31st august, 1 st , 2 nd and 3 rd september, 2017 respectively. mainly south-easterly wind with a speed of 2.0- 5.0 kmph is expected. maximum temperature is predicted as 34.0, 33.0, 33.0, 32.0 and 32.0Â°c and minimum as 25.0, 25.0, 25.0, 23.0 and 22.0Â°c on 30th , 31st august, 1 st, 2nd and 3 rd september, 2017 respectively. morning and evening relative ..."
2106,asking that what has to be applied and the amount as basal application in the main field for arize Â¿ 6444 variety of paddy.,"suggested to apply 1.5 kg urea, 12 kg of diammonium phosphate, 6.5 kg of muriate of potash and 6.5 kg of zinc sulphate as basal application for arize-6444 variety of paddy."
2183,asking about weathwe report of bongaigaon district of assam.,"in the coming 5 days clear sky will prevail; no rainfall is predicted from 26th to 30th jan, 2018. the maximum temperature predicted is 27-28 Â°c and minimum of 13-14 Â°c. the expected morning and evening rh will be 57-63 % & 23-26 %, respectively. mostly north-easterly wind with a speed of 5-6 kmph is expected. agro-meteorological"
2710,04 jun rainfall(mm) : 0 temp(max/min):0 Â /Â 0 humidity(max/min)0 Â /Â 0 wind:0,04 jun rainfall(mm) : 0 temp(max/min):0 Â /Â 0 humidity(max/min)0 Â /Â 0 wind:0
3595,asking about the control of flower drop in spine gourd.,"in the coming 5 days partly cloudy sky will prevail; 15, 5, 3, 19 and 3 mm rainfall is predicted from 28 th to 02nd october, 2019. the maximum temperature predicted is 28 to 31 Â°c and minimum of 23-24Â°c. the expected morning and evening rh will be 79-88 % & 53-72 %, respectively. mostly north easterly wind with a speed of 6-13 kmph is expected."
3617,06 jun rainfall(mm) : 0 temp(max/min):28.6 Â /Â 20.5 humidity(max/min)83.0 Â /Â 85.0 wind:1.9,06 jun rainfall(mm) : 0 temp(max/min):28.6 Â /Â 20.5 humidity(max/min)83.0 Â /Â 85.0 wind:1.9
3928,33Â°hi realfeelÂ® 34Â° precipitation 2% more sun than clouds winds from the se 11 km/h gusts: 37 km/h max uv index: 8 (very high) thunderstorm,33Â°hi realfeelÂ® 34Â° precipitation 2% more sun than clouds winds from the se 11 km/h gusts: 37 km/h max uv index: 8 (very high) thunderstorm
4163,asking about the wether report in udalguri dist,"clear sky with 0 octa will prevail during next 5 days. no rainfall is predicted during next 5 days. mainly south-easterly wind with a speed of 3.0-4.0 kmph is expected. maximum temperature is predicted as 26.0, 26.0, 27.0, 26.0 and 26.0Â°c and minimum as 9.0, 9.0, 9.0, 9.0 and 9.0Â°c on 17th, 18th, 19th, 20th and 21st december 2016 respectively. morning and evening relative humidity will be around 78-86% and 33-38% during next 5 days."
4266,08 may rainfall(mm) : 0 temp(max/min):0 Â /Â 0 humidity(max/min)0 Â /Â 0 wind:0,08 may rainfall(mm) : 0 temp(max/min):0 Â /Â 0 humidity(max/min)0 Â /Â 0 wind:0
4512,25 may rainfall(mm) : 0 temp(max/min):0 Â /Â 0 humidity(max/min)0 Â /Â 0 wind:0,25 may rainfall(mm) : 0 temp(max/min):0 Â /Â 0 humidity(max/min)0 Â /Â 0 wind:0
4544,06 jun rainfall(mm) : 0 temp(max/min):0 Â /Â 0 humidity(max/min)0 Â /Â 0 wind:0,06 jun rainfall(mm) : 0 temp(max/min):0 Â /Â 0 humidity(max/min)0 Â /Â 0 wind:0
4611,query regarding weathher report of barpeta district,"in the coming 5 days cloudy sky will prevail; 42, 19, 22, 18 & 24 mm rainfall is predicted from 14 th to 18 th july, 2018. the maximum temperature predicted is 35-36 Â°c and minimum of 25-26 Â°c. the expected morning and evening rh will be 90-95 % & 47-55 %, respectively. mostly southerly wind with a speed of 2-4 kmph is expected."
4870,asking bout the weathwer report of karbianglong dist,"theskywillremainclearinthisweek.theexpected maximum temperaturewillbe31.0to330Â°candthe minimum willbe 23.0 to 24.0Â°c.the expected morning and evening relative humiditywillbe in between 94 to 98% and 46to 64% respectively. thereispossibilityof33mm,42mm,61mm,66mm& 68mm rainfallincoming5days."
4987,"query regarding weayher report of dhubri district , dated 26/06/2018","in the coming 5 days cloudy sky will prevail; 86, 77, 44, 44 & 82 mm rainfall is predicted from 23 rd to 27 th june, 2018. the maximum temperature predicted is 29-33 Â°c and minimum of 24-25 centigrade. the expected morning and maximum temperature27-32Â°c & minimum temperature 24-25 d evening rh will be 95-99 % & 74-92 %, respectively. mostly southeasterly wind with a speed of 8-10 kmph is expected"
5168,asking about the fertilizer doses in bhindi and ridgegourd,05 mar rainfall(mm) : 0 temp(max/min):0 Â /Â 0 humidity(max/min)0 Â /Â 0 wind:0
5226,31 may rainfall(mm) : 0 temp(max/min):0 Â /Â 0 humidity(max/min)0 Â /Â 0 wind:0,31 may rainfall(mm) : 0 temp(max/min):0 Â /Â 0 humidity(max/min)0 Â /Â 0 wind:0
5228,asking for the control measure against red and white ants in potato crop cultivation field,suggested to apply Â¿malathion 5% dustÂ¿ @ 6 kilo grams per bigha in the soil at the time of earthing up and application of mustard oil cake @ 20 kilo grams per bigha that too at the time of earthi ng up reduces red and white ants infestations to a greater degree
5328,asking for the control of fertilizer dose of cauliflower,"in the coming 5 days mainly clear sky will prevail; no rainfall is predicted from 5 th to 9 th january, 2019. the maximum temperature predicted is 24-27 Â°c and minimum of 10-11 Â°c. the expected morning and evening rh will be 60- 66 % & 21-27 %, respectively. mostly north easterly wind with a speed of 7-8 kmph is expected."
5530,rainfall (mm) temp (max/min) humidity (max/min) wind 24 apr 0 32.0 / 0.0 0.0 / 0.0 0.0 25 apr 0 28.0 / 18.0 33.0 / 0 4.0 26 apr 0 29.0 / 20.0 32.0 / 0 4.0 27 apr 4.0 29.0 / 20.0 32.0 / 0 4.0 28 apr 25.0 27.0 / 19.0 45.0 / 0 3.0 29 apr 27.0 25.0 / 17.0 63.0 / 0 6.0,rainfall (mm) temp (max/min) humidity (max/min) wind 24 apr 0 32.0 / 0.0 0.0 / 0.0 0.0 25 apr 0 28.0 / 18.0 33.0 / 0 4.0 26 apr 0 29.0 / 20.0 32.0 / 0 4.0 27 apr 4.0 29.0 / 20.0 32.0 / 0 4.0 28 apr 25.0 27.0 / 19.0 45.0 / 0 3.0 29 apr 27.0 25.0 / 17.0 63.0 / 0 6.0
6057,asking for the preventive measure to control late blight in potato.,"suggested to spray indofil m 45 @ 2.5ml in per litre .also suggested to go for 1st spraying during december 10 to 15 and if rainy weather prevails during the spraying time suggested to use sticker triton @ 0.5 ml per litre of water in the spray solution. if the severity of disease becomes more, then the spraying should be done at an interval of 7Â¿10 days. suggested that while spraying, care should be taken to ensure wetting of the lower sides of the leaves."
6157,asking about the eather report in lakhimpur,"partial cloudy sky with 2-6 octa will prevail during next 5 days. 6.0, 10.0, 7.0,3.0 and 6.0 mm rainfall is predicted on 11th, 12th, 13th, 14th and 15th march, 2017 respectively. mainly south-easterly wind with a speed of 2.0-4.0 kmph is expected. maximum temperature is predicted as 26.0, 17.0, 21.0, 23.0 and 23.0Â°c and minimum as 14.0, 14.0, 14.0, 13.0 and 13.0Â°c on 11th, 12th, 13th, 14th and 15th march, 2017 respectively. morning and evening relative humidity will be around 84-97% and 44..."
6161,asking about the borer and thrips infestation in chilli,weather details [ 26 may 2019 ] date rainfall (mm) temp (max/min) humidity (max/min) wind 26 may 0 0 / 0 0 / 0 0 27 may 22.0 29.0 / 22.0 51.0 / 0 2.0 28 may 8.0 31.0 / 24.0 46.0 / 0 2.0 29 may 20.0 33.0 / 24.0 45.0 / 0 2.0 30 may 29.0 34.0 / 23.0 45.0 / 0 3.0 31 may 32.0 34.0 / 22.0 48.0 / 0 3.0
6297,16 may rainfall(mm) : 6.3 temp(max/min):30.0 Â /Â 21.0 humidity(max/min)91.0 Â /Â 92.0 wind:0.0,told her that cutting is mainly used for dahlia propagation
6809,23 may rainfall(mm) : 0 temp(max/min):0 Â /Â 0 humidity(max/min)0 Â /Â 0 wind:0,23 may rainfall(mm) : 0 temp(max/min):0 Â /Â 0 humidity(max/min)0 Â /Â 0 wind:0
6997,rainfall (mm) temp (max/min) humidity (max/min) wind 26 apr 0 0 / 0 0 / 0 0 27 apr 10.0 31.0 / 23.0 49.0 / 0 3.0 28 apr 12.0 28.0 / 21.0 66.0 / 0 4.0 29 apr 13.0 27.0 / 21.0 63.0 / 0 5.0 30 apr 30.0 27.0 / 21.0 67.0 / 0 4.0 01 may 23.0 27.0 / 20.0 72.0 / 0 5.0,rainfall (mm) temp (max/min) humidity (max/min) wind 26 apr 0 0 / 0 0 / 0 0 27 apr 10.0 31.0 / 23.0 49.0 / 0 3.0 28 apr 12.0 28.0 / 21.0 66.0 / 0 4.0 29 apr 13.0 27.0 / 21.0 63.0 / 0 5.0 30 apr 30.0 27.0 / 21.0 67.0 / 0 4.0 01 may 23.0 27.0 / 20.0 72.0 / 0 5.0
7015,rainfall (mm) temp (max/min) humidity (max/min) wind 25 apr 0 34.8 / 19.5 0.0 / 0.0 0.0 26 apr 5.0 34.0 / 21.0 32.0 / 0 4.0 27 apr 13.0 34.0 / 21.0 32.0 / 0 4.0 28 apr 23.0 32.0 / 20.0 43.0 / 0 2.0 29 apr 42.0 25.0 / 19.0 78.0 / 0 3.0 30 apr 14.0 20.0 / 18.0 77.0 / 0 2.0,rainfall (mm) temp (max/min) humidity (max/min) wind 25 apr 0 34.8 / 19.5 0.0 / 0.0 0.0 26 apr 5.0 34.0 / 21.0 32.0 / 0 4.0 27 apr 13.0 34.0 / 21.0 32.0 / 0 4.0 28 apr 23.0 32.0 / 20.0 43.0 / 0 2.0 29 apr 42.0 25.0 / 19.0 78.0 / 0 3.0 30 apr 14.0 20.0 / 18.0 77.0 / 0 2.0
7538,asking about the measure of jorhat district of assam,the weather will remain generally cloudy in the coming 5 days with possibilities of getting moderate to heavy rainfall from 2nd to 6th june. daily minimum and maximum temperature for the ensuing 5 days is predicted to be 23-24Â°c and 32Â°c respectively. expected morning and evening relative humidity will be 86-99% and 42- 71% respectively. wind will blow mainly from easterly direction at a speed of 2-4 kmph.
7563,asking for the cultural practices of ridge gourd,13 jan rainfall(mm) : 0 temp(max/min):0 Â /Â 0 humidity(max/min)0 Â /Â 0 wind:0
7785,asking about the arize variety of short duration variety in South Asia context,"advice that arizeÂ® 6129 gold which is india's first blb resistant short duration hybrid ,consistently high yield 20-25% more than the other high yielding varieties of same duration early duration hybrid (115-120 days) with maximum productive tillers high grain filling>90% & more grain per panicle(275-300) less water requirement & wider adaptability fits well in vegetable/potato & wheat crop rotations"
7887,asking for the fertilizer dose of ridge gourd,02 mar rainfall(mm) : 0 temp(max/min):0 Â /Â 0 humidity(max/min)0 Â /Â 0 wind:0
7943,asked about the rainy conditions for the following days,weather details [ 26 aug 2019 ] date rainfall (mm) temp (max/min) humidity (max/min) wind 26 aug 0 0 / 0 0 / 0 0 27 aug 4.0 38.0 / 26.0 43.0 / 0 3.0 28 aug 12.0 38.0 / 27.0 47.0 / 0 3.0 29 aug 13.0 38.0 / 27.0 54.0 / 0 4.0 30 aug 28.0 36.0 / 26.0 56.0 / 0 2.0 31 aug 66.0 37.0 / 27.0 51.0 / 0 2.0
8424,27 may rainfall(mm) : 0 temp(max/min):0 Â /Â 0 humidity(max/min)0 Â /Â 0 wind:0,27 may rainfall(mm) : 0 temp(max/min):0 Â /Â 0 humidity(max/min)0 Â /Â 0 wind:0
9955,date rainfall (mm) temp (max/min) humidity (max/min) wind 01 may 13.9 0.0 / 20.1 0.0 / 0.0 0.0 02 may 22.0 33.0 / 22.0 52.0 / 0 3.0 03 may 9.0 32.0 / 22.0 47.0 / 0 3.0 04 may 7.0 28.0 / 21.0 67.0 / 0 4.0 05 may 21.0 35.0 / 22.0 39.0 / 0 7.0 06 may 31.0 28.0 / 21.0 81.0 / 0 4.0,01 may rainfall(mm) : 13.9 temp(max/min):0.0 Â /Â 20.1 humidity(max/min)0.0 Â /Â 0.0 wind:0.0
10054,"asking about variety of okra, ridge gourde and cucumber",22 jan rainfall(mm) : 0 temp(max/min):21.8 Â /Â 8.8 humidity(max/min)0.0 Â /Â 0.0 wind:0.0
10572,asking about the control measure for rice hispa.,04 mar rainfall(mm) : 0 temp(max/min):22.2 Â /Â 16.0 humidity(max/min)81.0 Â /Â 95.0 wind:3.7
10631,07 jun rainfall(mm) : 0 temp(max/min):33.6 Â /Â 21.0 humidity(max/min)70.0 Â /Â 81.0 wind:0.0,07 jun rainfall(mm) : 0 temp(max/min):33.6 Â /Â 21.0 humidity(max/min)70.0 Â /Â 81.0 wind:0.0
10637,asking about control measure of rodent in rice,13 may rainfall(mm) : 8.0 temp(max/min):30.0 Â /Â 17.0 humidity(max/min)80.0 Â /Â 84.0 wind:1.9
11181,27 may rainfall(mm) : 0 temp(max/min):28.1 Â /Â 23.9 humidity(max/min)84.0 Â /Â 92.0 wind:0.0,27 may rainfall(mm) : 0 temp(max/min):28.1 Â /Â 23.9 humidity(max/min)84.0 Â /Â 92.0 wind:0.0
11268,asked about grass as feed for cows,there is light rainfall in the next five days. today's expected maximum temperature is (maximum 28.7Â°c and minimum temperature of 19.1Â°c and wind speed is likely to run at 5 kilometres per hour). and irrigation as per the weather forecast. and avoid irrigation as per the weather forecast.
11534,asking about the arize variety of short duration variety in South Asia context in Pakistan agriculture in Pakistan agriculture,"advice that arizeÂ® 6129 gold which is india's first blb resistant short duration hybrid ,consistently high yield 20-25% more than the other high yielding varieties of same duration early duration hybrid (115-120 days) with maximum productive tillers high grain filling>90% & more grain per panicle(275-300) less water requirement & wider adaptability fits well in vegetable/potato & wheat crop rotations"
11581,rainfall (mm) temp (max/min) humidity (max/min) wind 07 apr 0 0 / 0 0 / 0 0 07 apr 0 0 / 0 0 / 0 0,rainfall (mm) temp (max/min) humidity (max/min) wind 07 apr 0 0 / 0 0 / 0 0 07 apr 0 0 / 0 0 / 0 0
11611,07 jun rainfall(mm) : 0 temp(max/min):33.0 Â /Â 26.0 humidity(max/min)92.0 Â /Â 92.0 wind:0.0,07 jun rainfall(mm) : 0 temp(max/min):33.0 Â /Â 26.0 humidity(max/min)92.0 Â /Â 92.0 wind:0.0

In [ ]:
before = len(df_agri)

df_agri = df_agri.loc[
    ~bad_quality_mask
].copy().reset_index(drop=True)

print("Rows before:", before)
print("Rows removed:", before - len(df_agri))
print("Rows after:", len(df_agri))

Rows before: 20464
Rows removed: 94
Rows after: 20370

In [ ]:
print("FINAL SHAPE:", df_agri.shape)

print("\nMissing values:")
print(df_agri[["question", "answer"]].isnull().sum())

print("\nExact duplicate QA pairs:",
      df_agri.duplicated(
          subset=["question", "answer"]
      ).sum())

print("\nDuplicate questions:",
      df_agri["question"].duplicated().sum())

print("\nQuestion words:")
print(df_agri["question"].str.split().str.len().describe())

print("\nAnswer words:")
print(df_agri["answer"].str.split().str.len().describe())

FINAL SHAPE: (20370, 4)

Missing values:
question    0
answer      0
dtype: int64

Exact duplicate QA pairs: 0

Duplicate questions: 254

Question words:
count    20370.000000
mean        10.211487
std          3.770523
min          7.000000
25%          8.000000
50%          9.000000
75%         12.000000
max         74.000000
Name: question, dtype: float64

Answer words:
count    20370.000000
mean        18.714924
std         15.767388
min          7.000000
25%         10.000000
50%         13.000000
75%         21.000000
max        270.000000
Name: answer, dtype: float64

In [ ]:
# Keep only the actual QA columns
df_agri = df_agri[
    ["question", "answer"]
].copy().reset_index(drop=True)

print("Final dataset shape:", df_agri.shape)

print("\nColumns:")
print(df_agri.columns.tolist())

print("\nMissing values:")
print(df_agri.isnull().sum())

print("\nExact duplicate QA pairs:",
      df_agri.duplicated(
          subset=["question", "answer"]
      ).sum())

print("\nDuplicate questions:",
      df_agri["question"].duplicated().sum())

Final dataset shape: (20370, 2)

Columns:
['question', 'answer']

Missing values:
question    0
answer      0
dtype: int64

Exact duplicate QA pairs: 0

Duplicate questions: 254

In [ ]:
# Save the final cleaned dataset
df_agri.to_csv(
    "agriculture_qa_clean.csv",
    index=False
)

print("Saved:", "agriculture_qa_clean.csv")
print("Rows:", len(df_agri))

Saved: agriculture_qa_clean.csv
Rows: 20370

In [ ]:
import os
from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

# Define directory and file path
directory = "/content/drive/MyDrive/agriassist"
drive_path = os.path.join(directory, "agriculture_qa_clean.csv")

# Create target directory if it doesn't exist
os.makedirs(directory, exist_ok=True)

# Save the final cleaned dataset
df_agri.to_csv(
    drive_path,
    index=False
)

print("Saved to:", drive_path)

Mounted at /content/drive
Saved to: /content/drive/MyDrive/agriassist/agriculture_qa_clean.csv